### ISSUE TITLE
Palette issues with Super Sonic underwater and graphical errors in Aquatic Ruin Zone in Sonic 2

### ISSUE THREAD

**Issue by Sunlitspace542** [Rubberduckycooly/Sonic-1-2-2013-Decompilation#10]
[Aquatic Ruin](https://cdn.discordapp.com/attachments/762015016324431903/800574834257035304/unknown.png)
There's also a similar problem with water splashes in ARZ [see here](https://media.discordapp.net/attachments/762015016324431903/800584708814536724/unknown.png)

**Comment by FreshRoyal** [comment]
Eggman's sprites in ARZ2 also have issues when playing as Super Sonic
