### ISSUE TITLE
Question about crashes

### ISSUE THREAD

**Issue by trayfellow** [Rubberduckycooly/Sonic-1-2-2013-Decompilation#100]
i've heard crashes are a common thing and they're pretty normal, so just to make sure, is this what a crash should look like?
yesterday my game crashed and i got this error
![theerror](https://user-images.githubusercontent.com/48515908/105456519-e07d2300-5cb7-11eb-8b1d-e695715de209.PNG)

**Comment by danielh05** [comment]
are you playing on initial release and if so where did the crash happen? i remember i had this exact type of crash on the initial release version when grabbing the invincibility shield in sonic 1

**Comment by Sasytoremember** [comment]
for me, crashes freeze up the game, and don't pop up.

**Comment by Rubberduckycooly** [comment]
these are likely audio crashes, as others have reported the same screen when it crashed for them. Most of these have been fixed since the initial build and the fixes will be in the next build
