### ISSUE TITLE
Camera Bug

### ISSUE THREAD

**Issue by zenoncrow** [Rubberduckycooly/Sonic-1-2-2013-Decompilation#102]
When you perform the spindash and jump straight afterwards the camera will spaz out. Here's the video for demonstration.

https://youtu.be/dwgnB2tJgss

This issue is present in both Sonic 1 and Sonic 2.

**Comment by harper6202** [comment]
When I did this after beating the Emerald Hill Boss the game crashed.

**Comment by Rubberduckycooly** [comment]
this has been fixed in master, and will be in the next build which will release soon
