### ISSUE TITLE
Controls Settings? (Suggestion)

### ISSUE THREAD

**Issue by Sasytoremember** [Rubberduckycooly/Sonic-1-2-2013-Decompilation#105]
It would be nice to be able to set your controls to whatever you want.

**Comment by ToruTheRedFox** [comment]
You can manually in the ini

I assume the option to remap controls ingame will be added once the menus will be properly implemented

**Comment by Rubberduckycooly** [comment]
> You can manually in the ini
> 
> I assume the option to remap controls ingame will be added once the menus will be properly implemented

this is very much correct, we didn't really plan on ingame control remappings but its a good idea so we'll add it
