### ISSUE TITLE
B Button also opens Pause Menu

### ISSUE THREAD

**Issue by harper6202** [Rubberduckycooly/Sonic-1-2-2013-Decompilation#106]
Trying to Jump with the B Button also brings up the Pause Menu. I checked the settings.ini file, Start and B are mapped to separate buttons. This happens with both Keyboard and Controller. Pressing B while in the Pause Menu will close the menu and open it up again, unless you lightly tap the button, in which case it just closes the menu. https://www.youtube.com/watch?v=JtR6yahj51g

**Comment by Rubberduckycooly** [comment]
this is an intentional "feature" the sega forever versions added to the game scripts, either use an older data.rsdk file, or wait for someone to use script mods to mod it out
