### ISSUE TITLE
Freeze/softlock in Dev Menu on Vita

### ISSUE THREAD

**Issue by ToruTheRedFox** [Rubberduckycooly/Sonic-1-2-2013-Decompilation#107]
it either freezes or doesn't accept input, softlocking the game, can't really tell

dev menu works perfectly fine in SCD

**Comment by Rubberduckycooly** [comment]
this is a bug that's been fixed in the master, it happened due to a bug in the pause menu code, it will be in the next PC build and hopefully the next vita one

**Comment by ToruTheRedFox** [comment]
ah ok
