### ISSUE TITLE
dev menu crashes the game 

### ISSUE THREAD

**Issue by fgm3209** [Rubberduckycooly/Sonic-1-2-2013-Decompilation#109]
when i go into the dev menu the game freezes and i cant select anything, sometimes its even corrupted sonic sprites.

**Comment by ViperAcidZX** [comment]
I had this issue too with both games, and the only I could get out of it was to force close the game.

**Comment by Rubberduckycooly** [comment]
this happened with the pause menu not calling the dev menu correctly, it has been fixed and the next build will include the fix
