### ISSUE TITLE
1up jingle cuts short

### ISSUE THREAD

**Issue by JakeNagare** [Rubberduckycooly/Sonic-1-2-2013-Decompilation#11]
If you end up getting 50000 as a result of a score tally from the zone or special stage results screen it'll cut the 1up jingle short and sometimes this also makes further 1up jingles cutting short too.

**Comment by FayneAldan** [comment]
Can reproduce

**Comment by MGRich** [comment]
#2 potentially fixes this, but I have to verify later.

**Comment by Rubberduckycooly** [comment]
this has been properly fixed now, the fix will be in the next build
