### ISSUE TITLE
Updated to latest build and Start Button won't work (Xbox One S Controller)

### ISSUE THREAD

**Issue by FrostGamer98** [Rubberduckycooly/Sonic-1-2-2013-Decompilation#110]
I updated to the latest build (using the automatic building feature of GitHub) and now my Start button is not recognised by the game. I am using same controller mappings from the initial release on the 17th of January.

I am using an Xbox One S Controller with no external mapping programs (e.g. Steam Controller mapping, joy2key ect.)

**Comment by MGRich** [comment]
Fixed in 4511ae5eb10872739f398c9d14ac67638e58333c.
