### ISSUE TITLE
Sonic 2: Game crashed and lost progress with Chaos Emeralds

### ISSUE THREAD

**Issue by ViperAcidZX** [Rubberduckycooly/Sonic-1-2-2013-Decompilation#111]
A few days ago I was playing Sonic 2 with the 2013 decompilation, I got about 5 Chaos Emeralds, 3 in Emerald Hill Zone, and 2 when I got to Chemical Plant Zone. Midway through Chemical Plant Zone, Act 1 the game crashed out of nowhere, I tried to reload my save file, loaded it back to Chemical Plant Zone, and when I attempted to resume my progress with the Special Stages, it sent me back to where I had only 3 from Emerald Hill Zone. I have these two logs when the crashed happened and another where I lost my Chaos Emerald progress after the crash.

[log-012221_crash.txt](https://github.com/Rubberduckycooly/Sonic-1-2-2013-Decompilation/files/5860633/log-012221_crash.txt)
[log-012221_loadingaftercrash.txt](https://github.com/Rubberduckycooly/Sonic-1-2-2013-Decompilation/files/5860634/log-012221_loadingaftercrash.txt)

**Comment by MGRich** [comment]
Probably an audio bug? If you downloaded from the releases tab, it's likely it's an audio bug. If you didn't, then please request to reopen this and state exactly when you downloaded it, if possible.
