### ISSUE TITLE
[Question] How are the scripts supposed to be formatted?

### ISSUE THREAD

**Issue by ToruTheRedFox** [Rubberduckycooly/Sonic-1-2-2013-Decompilation#112]
I'm trying to mod some scripts but can't because no matter what I try, it can't get past parsing the alias
![image](https://user-images.githubusercontent.com/15708278/105611052-0a634200-5dab-11eb-9968-4c010081c29d.png)
(yes, I've tried the publicalias thing, but I'm fairly sure that I'm either doing it wrong or script parsing is broken)

**Comment by MGRich** [comment]
The RSDKv4 scripts are being COMPLETELY redone. All variables are different, all aliases are different, all function declarations are different, etc. You have yo wait for the script decomp to be finished.

**Comment by ToruTheRedFox** [comment]
kk
