### ISSUE TITLE
refresh rate setting resets itself back to 60

### ISSUE THREAD

**Issue by ymypl** [Rubberduckycooly/Sonic-1-2-2013-Decompilation#113]
so i was trying to get 144 fps in the game, so i edited settings.ini so refresh rate is 144, i start the game, and it just doesnt work and resets itself.

**Comment by MGRich** [comment]
Known and intentional for right now. The logic for different FPSs isn't done.

**Comment by ToruTheRedFox** [comment]
I mean, right now, why would you want the game to run at 2.4x speed?
