### ISSUE TITLE
can't finish stage in Ultrawide 

### ISSUE THREAD

**Issue by scottjco** [Rubberduckycooly/Sonic-1-2-2013-Decompilation#114]
![stagewontend](https://user-images.githubusercontent.com/59264362/105612350-6631c900-5db3-11eb-898e-2ab4f944ddca.png)
So I built the latest binary with MSYS2 and its running perfectly.

I decided to mess around with the ScreenWidth setting, setting it to 580 fills my 3440x1440 screen. And it was working wonderfully until I got to the end of the stage and Tails kept running in place at the end

Stage won't end

I got the idea to try Ultrawide when noticing it fills my phone screen, which happens to be ultrawide. Its pretty nice and hopefully it can work later

![Screenshot_20210123-195634_Sonic_2](https://user-images.githubusercontent.com/59264362/105612612-4a2f2700-5db5-11eb-991a-5df46e4a1561.jpg)
Here's a screenshot from my phone, in this version it allows Tails to keep on moving and the act ends. Dunno whats up with that to be honest, but rest assured, Ultrawide does work on the Android version. Its not AS ultrawide mind you, i'll have to look into smaller resolutions.

Found that Screenwidth of 500 allows me to complete the first stage, at least.

**Comment by MGRich** [comment]
Script bug that we sadly can't do anything about. I've heard the farthest you can go is 504 without the hanging.
