### ISSUE TITLE
Glitched sprites in the Start/Dev Menu shortly before a stage is loaded

### ISSUE THREAD

**Issue by cnrm** [Rubberduckycooly/Sonic-1-2-2013-Decompilation#116]
In the latest builds, the ↑, ↓, and OK sprites in the Start/Dev Menu appear incorrect for a split second after pressing the confirm button to load a stage through a new game or an existing save file. While this previously wasn't the case, it may have been introduced with https://github.com/Rubberduckycooly/Sonic-1-2-2013-Decompilation/commit/793875761d9db0e91048148af4a908621367e95d.
![image](https://user-images.githubusercontent.com/5803611/105614740-2d84f600-5d99-11eb-814e-4f024375baab.png)

**Comment by Rubberduckycooly** [comment]
this bug has now been fixed in the latest commit
