### ISSUE TITLE
"Couldn't load file"/"Failed to load string"

### ISSUE THREAD

**Issue by SuperAlan64YT** [Rubberduckycooly/Sonic-1-2-2013-Decompilation#120]
![20210123_192032](https://user-images.githubusercontent.com/77908745/105620389-6a5ce700-5db1-11eb-95d3-08e736215c9f.jpg)

Not sure what happend here.

**Comment by MGRich** [comment]
Make sure your Data.rsdk is named exactly. Remove the .xmf if there is one.

**Comment by SuperAlan64YT** [comment]
> Make sure your Data.rsdk is named exactly. Remove the .xmf if there is one.

So do I rename it? And take out the .xmf part?

**Comment by MGRich** [comment]
Yep.

**Comment by SuperAlan64YT** [comment]
> Yep.

Thanks, it worked
