### ISSUE TITLE
S1 : Restarting an act after hitting a signpost doesn't work properly

### ISSUE THREAD

**Issue by trayfellow** [Rubberduckycooly/Sonic-1-2-2013-Decompilation#123]
(Tested using sega forever release of Sonic 1 version 3.6.3)

I was playing act 1 of marble zone and during that time i hit a signpost, i had to restart the level since i screwed up getting 50 rings and it took me to the start of the level instead of the signpost, i then tried testing this again on my mobile phone and it took me to the signpost instead of restarting the whole level

**Comment by MGRich** [comment]
It puts me back at the start on phone for me. Possibly a version difference?
