### ISSUE TITLE
[Sonic 1] Sound issues since version 1.1.0 release

### ISSUE THREAD

**Issue by TopHatHipster** [Rubberduckycooly/Sonic-1-2-2013-Decompilation#125]
I noticed a couple issues with the sound engine struggling. During the following scenarios I encountered bugs:

- When the game switches music, it has often a delay as if the sound engine is muted before jumping back on a few seconds later (Encountered the first time already in Green Hill Zone during regular gameplay)
- When Sonic has both super speed and invincibility, once the effects wear off Sonic still has the sped up music. Starting another music (by another invincibility power up), the proper speed music plays again.
(Encountered in Spring Yard Zone Act 2)

MD5 of the Sonic 1 RSDK I'm using:
F679E87477BBED17FF1BDB9A6793F49C
Using the 1.1.0 release version, on Windows 10

**Comment by BlueSwordM** [comment]
Hmm, interesting.
I can't seem to reproduce both of these issues on a Linux distro.
From a few of the reports that I've seen, it looks like it's either an OS specific related issue, or it might be that the different game versions on Android that people have backed up cause issues.

Tested on 1.1.0-32c1888.

**Comment by Clownacy** [comment]
The first issue could have to do with the game [loading the music file on the audio thread](https://github.com/Rubberduckycooly/Sonic-1-2-2013-Decompilation/blob/main/Sonic12Decomp/Audio.cpp#L348). Previously, it would load the file on the main thread, but that would cause the game itself to pause for a split second instead.

Personally, I think the ideal way would be to load the file on a third, dedicated, thread. That way, music loading doesn't pause the audio thread or the main thread. Once the file is finished loading, the audio thread can start playing it, and unload the previous music data.
