### ISSUE TITLE
[Feature Request] Having the ability to replace the original soundtrack with mp3/ogg files

### ISSUE THREAD

**Issue by Gagert** [Rubberduckycooly/Sonic-1-2-2013-Decompilation#127]
After playing games such as Sonic Mania and the latest alpha of Sonic 2 HD, the unmodified soundtrack of both Sonic 1 & 2 sounds a bit "thin" in my opinion. If we had the ability to replace the soundtrack with either mp3, ogg or some other kind of file formats to get a richer sounding soundtrack for Sonic 1 & 2, that could in my opinion further enhance the experience of playing those Sonic 1 & 2 decompiled mobile versions. 

I've listened to remixes of various different zones from both Sonic 1 & 2 on YouTube, having the ability to switch to your favorite remixes of those tracks would be neat.

**Comment by TrackerTD** [comment]
Theoretically speaking, you can. The game's audio files are stored as ogg, so replacing them is pretty basic; main thing missing right now is adjusting loop points, which will require the scripts being released soon. 

Something like this won't become part of a the decomp as say, a menu option, as the point isn't to add features to the mobile versions but rather to preserve them.

**Comment by JakeNagare** [comment]
I believe this will essentially be added in 1.2.0 when mod support without needing to modify the Data.rdsk file is added.

**Comment by MGRich** [comment]
Yep, this is just through a mod.
