### ISSUE TITLE
[Feature Request] Integer Scaling in Fullscreen

### ISSUE THREAD

**Issue by Gagert** [Rubberduckycooly/Sonic-1-2-2013-Decompilation#128]
Having the option to do Integer Scaling in Fullscreen in this Sonic 1 & 2 decompilation could be great. As of now when I turn on the Fullscreen setting, the image stretches all the way to fill the screen area. With the option of Integer Scaling we could get square pixels which are all equal sized, and a black letterbox around the image itself in Fullscreen mode.

**Comment by ToruTheRedFox** [comment]
While working on enhanced scaling, I've accidentally caused integer scaling. I'll see if I can reproduce it when I have the time.

**Comment by ToruTheRedFox** [comment]
Alright, added integer scaling and regular bilinear. Creating PR for it here, and will create one for SCD in a few minutes.

**Comment by ToruTheRedFox** [comment]
Nevermind, the PR has to wait as integer scaling is crashing the GPU on Vita.

**Comment by Gagert** [comment]
I've added the very same Feature Request to [the Issue tracker of the Sonic CD decompilation](https://github.com/Rubberduckycooly/Sonic-CD-11-Decompilation/issues/63) btw, in case if the same lines of code could in the future add Integer Scaling to both repositories.

**Comment by ToruTheRedFox** [comment]
they in fact can

I just need to fix the vita gpu crash.

**Comment by Gagert** [comment]
I've just compiled and tried the newest build with Integer Scaling enabled, and I can report that it now works as intended (at least in Windows 10 64 bit). One thing to note is that if you have screen scaling enabled in Windows 10 (like I have on my TV), you would need to right click the executable of this decompilation, Properties, Compatibility, Change high DPI settings, and set Override high DPI scaling behavior to Application.

What do you know, I was only going to test Sonic 1 & Sonic 2 with the newest build, and I ended up completing both games with Sonic alone & getting all the emeralds. I don't think I can go back to playing those games in 4:3 aspect ratio ever again.

**Comment by Gagert** [comment]
Should I keep this Issue open until the PS Vita port get its Integer Scaling working? Feel free to close this Issue if not.

**Comment by MGRich** [comment]
We're in the process of removing the Vita repo from the main repo entirely.
