### ISSUE TITLE
Random items boxes aren't actually random.

### ISSUE THREAD

**Issue by JeffRuLz** [Rubberduckycooly/Sonic-1-2-2013-Decompilation#129]
I've tried playing Sonic 2 with the random item boxes (+Sonic 3) option enabled, and every time I launch the game I get the same pattern of items. Robotnik, Robotnik, Speed Shoes, Bubble, Shield, ect.

I believe calling srand(time(0)); at the start of the program should fix it but it may be another issue.

**Comment by JackoboLeChocobo** [comment]
I don't have the issue with Knuckles with this option. I have random items boxes without issue on my side.

**Comment by ooowoothevirtualhowler** [comment]
From what I can remember, this is how it actually behaves normally in the official mobile versions too. It seems to just have a set pattern that repeats every time you boot up the game which is probably a result of using the same seed every time.

**Comment by JeffRuLz** [comment]
I've tried it with every character and got the same result. Also using the plain random option does the same thing but with a different pattern. (Shield, Shield, Speed Shoes, Robotnik, ect)
I also tried calling srand(time(0)); in a custom build and it didn't do anything, so maybe it is built into the scripts.

**Comment by MGRich** [comment]
Closing this, probably handled by scripts.
