### ISSUE TITLE
Could a combined version of Sonic 1 & 2 be feasible with this decompilation?

### ISSUE THREAD

**Issue by Gagert** [Rubberduckycooly/Sonic-1-2-2013-Decompilation#130]
I remember a rom hack called Sonic 1 & 2 that was released some time ago, that as far as I know was a Sonic 2 rom hack with all the levels, enemies and bosses from Sonic 1 imported into that rom hack, combining both those game into a single rom.

Being that the same decompiled executable is used on both Sonic 1 & Sonic 2 here, thereby suggesting that both games were made using the same Retro engine back in 2013 when those mobile ports were made, would combining those two games into one singular game (like the Sonic 1 & 2 rom hack) be a more demanding task, programming wise?

Could this potentially be done once mod support arrives?

**Comment by MGRich** [comment]
With modding, it's definitely possible. You'd just need to make sure every script's compatible.
