### ISSUE TITLE
[Sonic 2] Game softlocks in too high resolutions

### ISSUE THREAD

**Issue by TrashBandatcoot** [Rubberduckycooly/Sonic-1-2-2013-Decompilation#131]
In Sonic 2, if you walk past a signpost in a too high resolution (eg. 1500px), Sonic is never able to walk off-screen, resulting in a softlock. Levels without a signpost work just fine, and this isn't in Sonic 1.

![image](https://user-images.githubusercontent.com/49070403/105639428-92fbe400-5e78-11eb-89a1-43299c7d4b0c.png)

**Comment by MGRich** [comment]
Script error: not something we can fix.

**Comment by scottjco** [comment]
theoretically could we edit the script to solve this problem later?

**Comment by TrashBandatcoot** [comment]
> Script error: not something we can fix.

Dang. Guess I'll just find a resolution that doesn't break.

**Comment by scottjco** [comment]
500 definitely works. 

At least for the moment thats the only option, I assume once we've got access to edit scripts it should be possible to change them and have true ultrawide

**Comment by MGRich** [comment]
You can edit the scripts to support it with a script mod, yes.
