### ISSUE TITLE
New version 1.1.0 doesn't work on Windows 10

### ISSUE THREAD

**Issue by CrostDaergon** [Rubberduckycooly/Sonic-1-2-2013-Decompilation#138]
It's all in the title. The 1.0.0 version worked just fine. When the new version got released, I figured I'd try it.
The window barely opens then closes itself a fraction of a second after.
I tried to reinstall the whole thing but it still doesn't run. I'm using the win_x64 version as I use a 64 bit OS.
Specs : 
CPU : Intel Core i5-8265U @ 1.60ghz (8CPUs) ~1.8ghz
Display GPU : Intel HD 620
Render GPU : Radeon 520
RAM : 8gb
Laptop ref : Dell Inspiron 3583

I'm sorry for the lack of viable information, I know barely anything about how all of this works.

**Comment by danielh05** [comment]
im on windows 10 and its working fine for me

**Comment by CrostDaergon** [comment]
> im on windows 10 and its working fine for me

And ? That doesn't help me, nor does it give me an idea of why it stopped working for me.
The only reason I'm saying this is because it gives more info about what I use to run the game, which is what you'd expect from someone reporting an issue. Of course it works fine for most people on W10, I'm already aware.

**Comment by trayfellow** [comment]
hmm can you try recording your laptop/pc trying to run the game?

**Comment by danielh05** [comment]
> 
> 
> > im on windows 10 and its working fine for me
> 
> And ? That doesn't help me, nor does it give me an idea of why it stopped working for me.
> The only reason I'm saying this is because it gives more info about what I use to run the game, which is what you'd expect from someone reporting an issue. Of course it works fine for most people on W10, I'm already aware.
you could just post the logs the game gives you

**Comment by ToruTheRedFox** [comment]
enable engine debug mode in the ini and post the log here, and if you already have enabled it, then clear the log file, and then launch the game to create a new one

**Comment by MGRich** [comment]
I've been completely unable to replicate this on ANY build (Debug/Release, x86/x64), and my main dev environment is Windows 10. No clue what could be happening here.

**Comment by AtomicPoetryPunk** [comment]
I'm having the same issue (i think) this is the log it gave me...

[log.txt](https://github.com/Rubberduckycooly/Sonic-1-2-2013-Decompilation/files/5878721/log.txt)


seems like it couldn't load the file lol does that mean there's something wrong with my apk extraction? It seemed pretty straight forward idk what I could've messed up.

**Comment by trayfellow** [comment]
> I'm having the same issue (i think) this is the log it gave me...
> 
> [log.txt](https://github.com/Rubberduckycooly/Sonic-1-2-2013-Decompilation/files/5878721/log.txt)
> 
> seems like it couldn't load the file lol does that mean there's something wrong with my apk extraction? It seemed pretty straight forward idk what I could've messed up.

what apk version are u using? did u get it from the playstore?

**Comment by CrostDaergon** [comment]
The latest Windows update + switching to my render GPU seems to have fixed the issue. I recommend manually installing the latest update.
If you wanna keep talking about your issues, create a different thread because I'm going to close this one.
