### ISSUE TITLE
boss music stops when you die in boss attack until you get a life

### ISSUE THREAD

**Issue by madethisjusttoreportanissue** [Rubberduckycooly/Sonic-1-2-2013-Decompilation#140]
self explanatory, go to level select in dev mode, choose any character, go to special and choose any boss attack stage, i recommend 1 and beating the first boss, then die on the second now that the boss music is playing, and the boss music just stops

**Comment by MGRich** [comment]
Intended. Boss attack is supposed to be time-attack only, so the scripts don't have something to start the music back up.
