### ISSUE TITLE
Having problems starting the program 

### ISSUE THREAD

**Issue by MechaMaster** [Rubberduckycooly/Sonic-1-2-2013-Decompilation#141]
Hi, 
I downloaded the decompilation just today and I cannot open the executable. I have the legally obtained .xmf file and placed it with the provided files from version 1.1.0, however, starting up the .exe does absolutely nothing, reinstalling all files does nothing either; I even restarted my computer to perform an update and it still does nothing. This is my first time trying out the decompilation so I am not familiar with anything that goes on, if anyone has any solutions or a similar situation it'll always be greatly appreciated. Thank You!

**Comment by trayfellow** [comment]
did you make sure to rename Data.rsdk.xmf to Data.rsdk ?

**Comment by MechaMaster** [comment]
Thank you so much for the suggestion, unfortunately, one of the tutorials I followed told me not to rename the file extension but I just did now and it works.

**Comment by trayfellow** [comment]
> Thank you so much for the suggestion, unfortunately, one of the tutorials I followed told me not to rename the file extension but I just did now and it works.

epic
