### ISSUE TITLE
[Sonic 2] Player can get stuck under propeller fans in Wing Fortress Zone.

### ISSUE THREAD

**Issue by delta7890** [Rubberduckycooly/Sonic-1-2-2013-Decompilation#144]
![sonic2wingfortressstuck](https://user-images.githubusercontent.com/34465681/105800176-252ce680-5f64-11eb-8646-e69072b35f03.png)
Seen above, jumping up through this propeller fan is meant to be a shortcut in Wing Fortress Zone.  However, the bounding box appears to extend to the fan body's underside, preventing the player from being lifted up through it.  Once stuck, there's no way to get free, and with the shield (or lightning shield with Sonic 3 item boxes) the player is invulnerable to the enemies placed right next to the fan.  This forces the player to either wait out the clock or restart the stage.

Proper behavior can be seen in this Sega Genesis screenshot below:
![Sonic the Hedgehog 2-210125-232003](https://user-images.githubusercontent.com/34465681/105800504-dcc1f880-5f64-11eb-9029-8aefa4dce726.png)

**Comment by trayfellow** [comment]
yep, the propeller is supposed pull you up but instead you get stuck

**Comment by cheatfreak47** [comment]
can confirm this issue, although I don't know if this is a problem in the actual mobile port.
my gut says the actual mobile port behaves the same, and if so, this is an issue that'd need to be corrected with a script mod when 1.2.0 is out.

**Comment by delta7890** [comment]
> 
> 
> can confirm this issue, although I don't know if this is a problem in the actual mobile port.
> my gut says the actual mobile port behaves the same, and if so, this is an issue that'd need to be corrected with a script mod when 1.2.0 is out.

![sonic2mobilewingfortress](https://user-images.githubusercontent.com/34465681/105851499-2afce900-5fb1-11eb-8854-37879951ab86.png)

The mobile port behaves in the proper way, as seen in the above screenshot.

**Comment by Gagert** [comment]
I've also encountered this while playing through Sonic 2 via this decompilation. I managed to somehow float to the right just where the chicken-robot stands and enter through that direction. I may have had a protecting shield equipped then since I managed to pass through the enemy.

**Comment by Radicalicious** [comment]
I also got stuck there on my playthrough, but I somehow died and clipped through the propeller, allowing me to control Sonic while I was supposed to have been sent back to the start.

**Comment by hurvithemeister** [comment]
> I also got stuck there on my playthrough, but I somehow died and clipped through the propeller, allowing me to control Sonic while I was supposed to have been sent back to the start.

I also encountered this issue (as well as the not being able to get through the propellers bug, which is annoying as I love that shortcut) - you're able to move sonic around after the death sound plays, however the screen won't scroll past the propellers and nothing on screen moves (such as enemies). If you go off screen then you can't return to the screen for some reason, and the only way to escape is via restarting the level.

**Comment by delta7890** [comment]
As of the recent updates, this issue is now fixed!
