### ISSUE TITLE
Deleting Savefiles is wonky

### ISSUE THREAD

**Issue by KAZ01-SEN** [Rubberduckycooly/Sonic-1-2-2013-Decompilation#148]
It seems savefiles are only really deleted if you go to the Game Options menu after deleting the save.
If you back out, cancel or anything, it shows up again when you return to the Select a Save File screen.

**Comment by SupakugaiGames** [comment]
Can confirm this happens on my end too. Once deleting a save slot, doing anything except going to Game Options will not actually delete the save file.

**Comment by Rubberduckycooly** [comment]
the next major build (1.2.0) will have a completely revamped menu, and this bug will be fixed in it
