### ISSUE TITLE
Restarting in Time Attack puts you at the last Checkpoint

### ISSUE THREAD

**Issue by harper6202** [Rubberduckycooly/Sonic-1-2-2013-Decompilation#149]
For both Sonic 1 and Sonic 2, when you restart in Time Attack mode, the game loads you at the last Checkpoint you interacted with instead of the beginning of the level like in the mobile versions of the game. Also, when you die in Sonic 2's Time Attack mode, you get sent to the main menu instead of the Zone's time attack menu.

**Comment by MGRich** [comment]
All should be fixed in 1.1.0.
