### ISSUE TITLE
Not all time attack options correspond to the correct zone (Sonic the Hedgehog 2)

### ISSUE THREAD

**Issue by SonicMastr** [Rubberduckycooly/Sonic-1-2-2013-Decompilation#15]
When selecting the time attack mode: 

Casino Night Zone Act 1 Results in playing the Hill Top Zone Boss fight. 
Casino Night Zone Act 2 results in playing Mystic Cave Zone Act 1. 
Chemical Plant Zone Act 2 sends you straight into the Boss fight with visual glitches. 
Hill Top Zone Act 1 sends you to Oil Ocean Zone right before the Boss fight.

These are just a few examples, but the bindings for Zones and their respective Acts aren't correct.

Note: I've only tested Sonic the Hedgehog 2 for this bug

**Comment by Rubberduckycooly** [comment]
do you have any more info that you could give me (such as info about your datafile) as I cannot replicate the bug with my datafile

**Comment by ThornTSC** [comment]
While I am not having SonicMastr's issues, I am having different time attack zone correspondence issues, Importing an Android Sonic 2 save file causes best times to align with the wrong zones.

- Best times for Wing Fortress (Android) appear under Sky Chase Zone.
- Best times for Boss Attack (Android) appear under Wing Fortress Zone.
- Best times for Hidden Palace (Android) appear under Death Egg Zone.

Zones between Emerald Hill and Metropolis have correct best times, and this is not an issue when importing a Sonic 1 save file.

**Comment by Rubberduckycooly** [comment]
> While I am not having SonicMastr's issues, I am having different time attack zone correspondence issues, Importing an Android Sonic 2 save file causes best times to align with the wrong zones.
> 
> * Best times for Wing Fortress (Android) appear under Sky Chase Zone.
> * Best times for Boss Attack (Android) appear under Wing Fortress Zone.
> * Best times for Hidden Palace (Android) appear under Death Egg Zone.
> 
> Zones between Emerald Hill and Metropolis have correct best times, and this is not an issue when importing a Sonic 1 save file.

I have gone through and I have removed SCZ & DEZ as they were not selectable in the original game, this should mean that your original saves carry over perfectly, this fix will be in the next build

**Comment by ThornTSC** [comment]
Having downloaded the latest Windows x64 artifact, I can say that the best times zone correspondence is still not fully correct. Boss Attack Zone and Hidden Palace Zone best times are swapped when using a pre-Forever Android Sonic 2 save file.
