### ISSUE TITLE
B button pauses game (Sonic 2 only)

### ISSUE THREAD

**Issue by sylveon-irl** [Rubberduckycooly/Sonic-1-2-2013-Decompilation#150]
my controller's B button, which is mapped to the genesis B button in the config, pauses the game on sonic 2 only, but not sonic 1. the settings.ini files for both are identical.

using 1.1.0 win64.

**Comment by MGRich** [comment]
Not a bug, sadly. The latest revisions of the SEGA Forever RSDKs have that embedded in their scripts.
