### ISSUE TITLE
"B" button issue

### ISSUE THREAD

**Issue by RenanFlippy** [Rubberduckycooly/Sonic-1-2-2013-Decompilation#152]
I have an issue with the "B" button, normally used in game for enter Debug mode, every time press the "B" button, the respective action (Jump or Debug enter/exit) and the pause menu appears simultaneusly. This happens in the keyboard and the Xinput connected to the PC. It was good if this issue was fixed in a future update, thanks, and sorry for bad english.

https://user-images.githubusercontent.com/78128669/106086868-8ed5fd80-60e8-11eb-843d-64cd83e0dad8.mp4

**Comment by trayfellow** [comment]
unfortunately this is a known script related issue for the sega forever versions of the game, the only way to get rid of them is to find a paid version of the apk or wait for someone to make a script mode that gets rid of this

**Comment by RenanFlippy** [comment]
Oh. Thanks, fortunately, i have backup of the official paid versions apks and saves in my PC after the delisted notice for Sega Forever free release.
![Screenshot_2021-01-27-23-23-10-1](https://user-images.githubusercontent.com/78128669/106093889-bcc23e80-60f6-11eb-85d9-92fa1be4135b.png)
