### ISSUE TITLE
'include/ghc/filesystem.hpp': No such file or directory (1.2.0 branch)

### ISSUE THREAD

**Issue by danielh05** [Rubberduckycooly/Sonic-1-2-2013-Decompilation#155]
im trying to compile the 1.2.0 branch of the decomp (compiling the same way i always do) and its giving me this error:
`E:\github\Sonic-1-2-2013-Decompilation\Sonic12Decomp\Userdata.cpp(744,10): fatal error C1083: Cannot open include file: 'include/ghc/filesystem.hpp': No such file or directory`

theres no other error than this one

**Comment by danielh05** [comment]
it also seems like the new actions are having this error as well
https://github.com/Rubberduckycooly/Sonic-1-2-2013-Decompilation/runs/1790526586

**Comment by vaguerant** [comment]
Looks like this was just fixed by 447ea92.

**Comment by Rubberduckycooly** [comment]
I accidently gitignored the files, and then fixed it, autobuilds are broken rn due to all the changes we're making but we'll fix them when we're closer to completion
