### ISSUE TITLE
[Sonic 2] ducking and looking up when you shouldn't

### ISSUE THREAD

**Issue by zenoncrow** [Rubberduckycooly/Sonic-1-2-2013-Decompilation#156]
In Sonic 2 while Sonic is standing on the very edge of any platform (showing his second balancing animation) you can look up or perfom a spindash.  

https://www.youtube.com/watch?v=FI6_kTXU7_U

Maybe this isn't worth fixing because this bug present in the vanilla android version of the game.

**Comment by Rubberduckycooly** [comment]
since it was in the original 2013 ver, we wont be fixing it in the decomp
