### ISSUE TITLE
[Sonic 1, untested in Sonic 2] Minor glitch: Extreme jump momentum out of water

### ISSUE THREAD

**Issue by Steve-Bros** [Rubberduckycooly/Sonic-1-2-2013-Decompilation#158]
### Issue detected

If you jump at a point where Sonic is barely in the water (I found it at this point in Labyrinth Zone Act 1), Sonic gets far too much upward momentum.

![image](https://user-images.githubusercontent.com/40872506/106320868-13379600-6239-11eb-9bd9-36eabb608045.png)

### To replicate:

1. Enter Labyrinth Zone Act 1.
2. Go to the point as described by the image, early in the stage.
3. Wait until the water is at its lowest, then jump.

**Comment by trayfellow** [comment]
this is a script related issue in some versions of sonic 1, so it cant be fixed, you might want to try other versions and see if the bug is gone or not

**Comment by Rubberduckycooly** [comment]
this was in the original 2013 versions, so it wont be fixed here. mods will be able to fix it though
