### ISSUE TITLE
[Sonic 1] Disable Super Forms doesn't work for Saves with the 7th Emerald

### ISSUE THREAD

**Issue by jaycitypt** [Rubberduckycooly/Sonic-1-2-2013-Decompilation#159]
In saves with the 7th Chaos Emerald acquired the Super Forms aren't disabled if you set the corresponding the option

The 7th Emerald was acquired while the same option was set to enabled.

**Comment by MegAmi24** [comment]
The game doesn't check if the max emerald count is set to 7, it just checks if you have 7 emeralds. This is handled by the scripts so it can't be fixed.
