### ISSUE TITLE
Good ending of Sonic 2 has inverted colors for a split second after the still images.

### ISSUE THREAD

**Issue by FreshRoyal** [Rubberduckycooly/Sonic-1-2-2013-Decompilation#16]
I haven't tested the bad ending. The planet looks red and Super Sonic is a light blue for a split second when the pixel art first appears.

**Comment by xKizame** [comment]
Bad ending does the same thing, but sonic goes red, just like the background.

**Comment by ToruTheRedFox** [comment]
probably some sort of delay in palette loading

**Comment by ActualMandM** [comment]
From what I saw of it, seems like an issue of the game blue and red channels being swapped

**Comment by Rubberduckycooly** [comment]
> Looks to be an issue with the red and blue channels being swapped.
> <img alt="2021-01-18_11-32-41_RSDKv4_64" width="960" src="https://user-images.githubusercontent.com/15317421/104956418-ec4bab00-5980-11eb-9e1d-b2b8d531ddce.png">
> Swapping the two channels in a photo editor (like Photoshop) shows what it should look like.
> <img alt="image" width="960" src="https://user-images.githubusercontent.com/15317421/104956539-2ddc5600-5981-11eb-864f-c16835a72679.png">

this was exactly the bug, oops lol
anyways it has been fixed and the fix will be in the next build
