### ISSUE TITLE
Discord RPC implementation ?

### ISSUE THREAD

**Issue by Sword09** [Rubberduckycooly/Sonic-1-2-2013-Decompilation#160]
Hi I was wondering as someone who likes showing what game I'm playing on Discord, if it is possible for you to add Discord Rich Presence system to the program ? And adding an option in the config file to enable / disable it ? It definitely isn't needed, I would like it tho :)

**Comment by Rubberduckycooly** [comment]
someone can make a fork if they want to add it, but it will not be added to the main repo
