### ISSUE TITLE
[1.1.0] Various issues with ultrawide resolutions.

### ISSUE THREAD

**Issue by hurvithemeister** [Rubberduckycooly/Sonic-1-2-2013-Decompilation#164]
-First one can be found after beating any Act 1 stage, and is the most annoying, occurring on any resolution in which the character can be seen after the signpost. After playing the "signpost passed" sound, instead of playing the act clear the music instead the game goes back to looping the normal level music, and the player character is stuck in a running animation. The level geometry seems to loop at the end, too, and the only way to escape this (pausing didn't seem to work at all for me) is by closing the game entirely - a softlock.

-Bosses in ultrawide resolutions are able to navigate the entire width of the screen, when they clearly shouldn't be able to. One of the most noticeable examples of this is Emerald Hill's boss, in which Eggman's buggy will drive off about a quarter of the way back through the level, before hitting the screen edge and coming back. It's funny to watch, but obviously broken.

-Final issue is that, in any boss, the animal capsule can be seen if you play on ultrawide resolutions, and therefore you're able to just simply open the capsule without even attempting to fight the boss, even keeping the boss on screen and not despawning it. This isn't really game breaking (just don't hit the capsule to do the fight properly) but still weird.

I'm not sure if these can actually be patched or if this is something that can be fixed, but playing on ultrawide resolutions is really damn cool otherwise and it's a shame it has a few major issues.

Here's an example of the Act 1 issue, the most annoying of the three:
![image](https://user-images.githubusercontent.com/77669180/106391206-18851400-63e4-11eb-9e4f-a6a08b698048.png)

**Comment by scottjco** [comment]
This will be marked as invalid sadly, i've brought up this before and the answer is that the game scripts need to be modified to support these sort of things

**Comment by breakthetargets** [comment]
> I'd love to do try and fix it myself, does anyone know how I can get started editing the scripts?

Wait until the script decomps are released.
