### ISSUE TITLE
Sonic 2 Wing Fortress Zone Bug

### ISSUE THREAD

**Issue by sfkento723** [Rubberduckycooly/Sonic-1-2-2013-Decompilation#167]
The outdoor section in Wing Fortress Zone has an issue where the panels do not push Sonic into the airship properly.
![image](https://user-images.githubusercontent.com/46071185/106423465-18a60380-6426-11eb-9aef-3886513fb0da.png)
(Image taken from a Sonic 2 fansite and not mine)

**Comment by MGRich** [comment]
Needs more info. Does this happen in the original port? What decomp version were you using, and does it happen now?

**Comment by delta7890** [comment]
Seems to work fine for me.  Just ran through the stage to test.

**Comment by WylAyres** [comment]
I have same issue

Decompilation: 1.1.2 64bits (RSDKv4_64.exe)
data.rsdk from Sonic 2 v3.1.5
Game Mode: No Save Mode

![wingf](https://user-images.githubusercontent.com/90911262/133784463-7285066f-465f-44f2-91b9-8e711d3ff789.png)

**Comment by delta7890** [comment]
> 
> 
> I have same issue
> 
> Decompilation: 1.1.2 64bits (RSDKv4_64.exe)
> data.rsdk from Sonic 2 3.1.5 (Android)
> Game Mode: No Save Mode
> 
> ![wingf](https://user-images.githubusercontent.com/90911262/133784463-7285066f-465f-44f2-91b9-8e711d3ff789.png)

This seems to be an entirely different issue.  The panels have broken away but Sonic is still hanging on?

**Comment by WylAyres** [comment]
> > I have same issue
> > Decompilation: 1.1.2 64bits (RSDKv4_64.exe)
> > data.rsdk from Sonic 2 3.1.5 (Android)
> > Game Mode: No Save Mode
> > ![wingf](https://user-images.githubusercontent.com/90911262/133784463-7285066f-465f-44f2-91b9-8e711d3ff789.png)
> 
> This seems to be an entirely different issue. The panels have broken away but Sonic is still hanging on?

Yeah, Sonic is still hanging on! The panels break when press A (jump) button but Sonic doesn't let go ... then collision become crazy and Sonic can't enter to the airship properly (like  
sfkento723 said)

![2021-09-17-13-56-46](https://user-images.githubusercontent.com/90911262/133826729-c52a8f1d-aefb-447e-a620-fb6c52b526cc.gif)

**Comment by WylAyres** [comment]
-MORE BUG DETAILS-

Apparently the bug only occurs when player select is set to "Sonic & Tails" and, for some strange reason, if player destroy this invencibility monitor the bug doesn't happen

![monitor_trigger](https://user-images.githubusercontent.com/90911262/134741604-164dc845-38ee-4e94-953f-77456d0009b3.png)

Others RSDK and 32-bits version decompilation have this bug too 

Tested:
-data.rsdk 3.1.5 (pre-Sega Forever) & 1.3.1 (Sega Forever)
-decompilation 1.1.2 64-bits & 32 bits
-Game Mode: No Save Game - Sonic and Tails (Level Select cheat activated for testing) - DevMenu = OFF - Debug Cheat = OFF

**Comment by MegAmi24** [comment]
do you have any mods turned on?

**Comment by WylAyres** [comment]
> do you have any mods turned on?

In my case, I don't have any mod for this game

**Comment by Leonx254** [comment]
this issue gets fixed when enabling scripts
