### ISSUE TITLE
Can't adjust FPS setting

### ISSUE THREAD

**Issue by Anixanic** [Rubberduckycooly/Sonic-1-2-2013-Decompilation#168]
I was trying to experiment with the target FPS setting just for curiosity but it just keep changing back to 60fps whether I try to make it lower or higher. I tried disabling Vsync but it still wouldn't fix it. I don't know if the setting has been properly been implemented yet.

**Comment by breakthetargets** [comment]
https://github.com/Rubberduckycooly/Sonic-1-2-2013-Decompilation/issues/113

**Comment by MGRich** [comment]
woah 2 month ago ghost that's a fairly quick deletion
