### ISSUE TITLE
Pressing the B button the Pause is activated.

### ISSUE THREAD

**Issue by SJunyo** [Rubberduckycooly/Sonic-1-2-2013-Decompilation#169]
#I'm playing on the keyboard with Windows 10 x64, and the pause function was placed on the same jump button. I changed the keys to play in WASD JKL, but the problem is since the factory configuration.

[Keyboard 1]
; Keyboard Mappings for P1 (Based on: https://wiki.libsdl.org/SDL_Scancode)
Up=26
Down=22
Left=4
Right=7
A=13
B=14  **<=This key has the same action as the pause button.**
C=15
X=24
Y=12
Z=29
L=20
R=8
Start=40
Select=42

**Comment by breakthetargets** [comment]
Not a bug. Happens on newer Sonic 1 and 2 versions.
