### ISSUE TITLE
S1 & S2 : Tails Still joins you In Sonic Alone File

### ISSUE THREAD

**Issue by trayfellow** [Rubberduckycooly/Sonic-1-2-2013-Decompilation#17]
if you start up a game with sonic alone, pause and exit to the main menu, start up a game with sonic & tails then exit to main menu again, start up a game with sonic alone again and tails still joins you anyways

edit : i've tried testing this on sonic 1 to see if it would happen again and i was right

**Comment by Rubberduckycooly** [comment]
bug has been fixed, next build will have this bug fix in it
