### ISSUE TITLE
Knuckles glides out of screen in the good ending of the knuckles sonic 2 run

### ISSUE THREAD

**Issue by AlexY3et** [Rubberduckycooly/Sonic-1-2-2013-Decompilation#172]
When I got all the emeralds with knuckles, after I beat the game in the little cutscene he glides away from the screen until tails arrives, then he is teleported onto the tornado for the ending where he jumps at the screen

**Comment by scottjco** [comment]
https://youtu.be/A80bF7vMd9s?t=3944

Here's a clip of it in the mobile port, he definitely lands on the plane in that

**Comment by AlexY3et** [comment]
Nevermind I think it was fixed in 1.1.1
