### ISSUE TITLE
1.1.1 Sonic 2 Leaving Special Stage After Restarting Inside of it Resets Level

### ISSUE THREAD

**Issue by harper6202** [Rubberduckycooly/Sonic-1-2-2013-Decompilation#174]
When you restart inside of a special stage and leave the stage by losing or getting the emerald, returning to the main level doesn't put you at the last checkpoint but at the beginning of the level instead. This was in issue in previous versions as well.

**Comment by Rubberduckycooly** [comment]
will be fixed in v1.2.0
