### ISSUE TITLE
Can't complete Scrap Brain Act 2 in Data Folder Mode

### ISSUE THREAD

**Issue by TheWonderFromDownUnder** [Rubberduckycooly/Sonic-1-2-2013-Decompilation#175]
Every time I attempt to complete Scrap Brain Act 2 in Data Folder Mode, the barrier that appears in front of the pit trap prevents me from progressing.

![Screenshot (2267)](https://user-images.githubusercontent.com/52037295/106815746-34025000-666c-11eb-8bc2-6f05d067fc03.png)

**Comment by scottjco** [comment]
Thats very peculiar, that barrier isn't there in my copy of the game, is it using the bytecode folder or the scripts folder?
![peculiar](https://user-images.githubusercontent.com/59264362/107510467-e3bf4c80-6b9b-11eb-89ef-c8c45907f50e.png)

**Comment by Ghaleonh41** [comment]
I just ran into the same issue.

Thankfully, there's a fix for it on Gamebanana.
![Untitled](https://user-images.githubusercontent.com/78719249/107846205-d8dd0580-6daf-11eb-9447-10ab3d109b60.png)

**Comment by MGRich** [comment]
Marking as invalid *for now, * but will be checking on this.
