### ISSUE TITLE
Pause screen always highlights Continue

### ISSUE THREAD

**Issue by TheWonderFromDownUnder** [Rubberduckycooly/Sonic-1-2-2013-Decompilation#176]
As of 1.1.1, the pause screen always highlights continue even when not on the continue option.
![Screenshot (2270)](https://user-images.githubusercontent.com/52037295/106819606-f274a380-6671-11eb-82ca-6a23aba8b0d1.png)
![Screenshot (2271)](https://user-images.githubusercontent.com/52037295/106819634-fa344800-6671-11eb-939f-46f694170b5c.png)

**Comment by MGRich** [comment]
Should be fixed in 1.2.0, but as far as I can remember I'm unable to replicate this on 1.1.1.
