### ISSUE TITLE
Can't use data folder mode or modified data.rsdk

### ISSUE THREAD

**Issue by CheezyFriez12** [Rubberduckycooly/Sonic-1-2-2013-Decompilation#177]
I tried using mods on the latest version of all of your decompilations, but they didn't work. If you know what did this, please fix it in your next release.

**Comment by scottjco** [comment]
how on earth do you even use data folder mode? or unpack the rdsk for that matter, i've been looking and I really have no idea

**Comment by CheezyFriez12** [comment]
You would have to use the first version of the decompilation to use this, but if you download a tool called Retrun (Can be found on the Sonic 1 2013 Gamebanana) to unpack the .rsdk, then copy the data and bytecode (if its there) folders to the game directory, and you can use data folder mode.

**Comment by JackoboLeChocobo** [comment]
You can have the source code of Retrun, available in the Discord server of REMS, channel #tools . I tested it on Linux ( compilation and using the executable resulted by the compilation ) and it works ^^

**Comment by dilworks** [comment]
> You can have the source code of Retrun, available in the Discord server of REMS, channel #tools . I tested it on Linux ( compilation and using the executable resulted by the compilation ) and it works ^^

Could you share a link for those of us that don't use Discord? I'm interested into taking a peek into those games (particularly Sonic CD) on my Linux box...

**Comment by scottjco** [comment]
I found retrun, but it only outputs a bunch of numbered files, it knows what a few files are properly called. 

So the game will load stuff but the music is missing and so is a bunch of objects. _

**Comment by coreybruce** [comment]
What OS are you guys using? you should be able to put the executable in folder with Data.rsdk, it will be originally called ```Data.rsdk.xml`` and will just need to remove the .xml extension off the end of it to make it work.

**Comment by Alzyuzkov** [comment]
guys help me find data folder is not find data fikder in game sonic 1 decomp refresh
