### ISSUE TITLE
Cant compile Linux version

### ISSUE THREAD

**Issue by Algamerthetruealbanian** [Rubberduckycooly/Sonic-1-2-2013-Decompilation#178]
mkdir -p bin
g++ -D_REENTRANT -I/usr/include/SDL2  -DBASE_PATH='""'  objects/Sonic12Decomp/Animation.cpp.o objects/Sonic12Decomp/Audio.cpp.o objects/Sonic12Decomp/Collision.cpp.o objects/Sonic12Decomp/Debug.cpp.o objects/Sonic12Decomp/Drawing.cpp.o objects/Sonic12Decomp/Ini.cpp.o objects/Sonic12Decomp/Input.cpp.o objects/Sonic12Decomp/main.cpp.o objects/Sonic12Decomp/Math.cpp.o objects/Sonic12Decomp/Network.cpp.o objects/Sonic12Decomp/Object.cpp.o objects/Sonic12Decomp/Palette.cpp.o objects/Sonic12Decomp/PauseMenu.cpp.o objects/Sonic12Decomp/Reader.cpp.o objects/Sonic12Decomp/RetroEngine.cpp.o objects/Sonic12Decomp/RetroGameLoop.cpp.o objects/Sonic12Decomp/Scene.cpp.o objects/Sonic12Decomp/Scene3D.cpp.o objects/Sonic12Decomp/Script.cpp.o objects/Sonic12Decomp/Sprite.cpp.o objects/Sonic12Decomp/String.cpp.o objects/Sonic12Decomp/Text.cpp.o objects/Sonic12Decomp/Userdata.cpp.o -o bin/sonic2013 -lSDL2 -Wl,--no-undefined -lm -ldl -lasound -lm -ldl -lpthread -lpulse-simple -lpulse -lX11 -lXext -lXcursor -lXinerama -lXi -lXrandr -lXss -lXxf86vm -ldrm -lgbm -lwayland-egl -lwayland-client -lwayland-cursor -lxkbcommon -lpthread -lrt -lvorbisfile -lvorbis -lm -logg -pthread 
/usr/bin/ld: cannot find -ldrm
collect2: error: ld returned 1 exit status
make: *** [Makefile:42: bin/sonic2013] Error 1

**Comment by parkerlreed** [comment]
You need the libdrm developement libraries.

Debian libdrm-dev

Arch libdrm

**Comment by Algamerthetruealbanian** [comment]
> You need the libdrm developement libraries.
> 
> Debian libdrm-dev
> 
> Arch libdrm

how to install what?

**Comment by Algamerthetruealbanian** [comment]
> You need the libdrm developement libraries.
> 
> Debian libdrm-dev
> 
> Arch libdrm

i got it but i cant seem to find it on the folder
