### ISSUE TITLE
S2 : Invisible Lava in HTZ2

### ISSUE THREAD

**Issue by trayfellow** [Rubberduckycooly/Sonic-1-2-2013-Decompilation#18]
![bugreports2](https://user-images.githubusercontent.com/48515908/104915895-de6b4980-59c3-11eb-9e9a-ff821fbb545d.PNG)

this lava in hill top zone act 2 is invisible, it can still hurt you, its just not visible

**Comment by MGRich** [comment]
Closing due to duplicate.
