### ISSUE TITLE
[1.2.0] buggy start up menus

### ISSUE THREAD

**Issue by danielh05** [Rubberduckycooly/Sonic-1-2-2013-Decompilation#181]
MD5 of both games data.rsdk
f679e87477bbed17ff1bdb9a6793f49c - Sonic 1
b7339e7a4cf4ae6264449eec06465c7c - Sonic 2
https://user-images.githubusercontent.com/35849198/107124553-e15fa880-68a4-11eb-9cb4-2d6455b8e92c.mp4

**Comment by JackoboLeChocobo** [comment]
Get the Menu assets here : https://drive.google.com/drive/folders/1YhrynkayllKulmsR3VhswT2LLc7u6VHC and place it like in this screenshot. And run after sonic2013 executable ( works both on Data mode or Menu.rsdk mode )
![github](https://user-images.githubusercontent.com/42393934/107146220-fc82f480-6946-11eb-8d9f-f5450ca3cabe.jpg)

**Comment by danielh05** [comment]
that fixed it, thank you very much
