### ISSUE TITLE
Sonic 1's credits demos are out of sync.

### ISSUE THREAD

**Issue by FreshRoyal** [Rubberduckycooly/Sonic-1-2-2013-Decompilation#182]
The first Green Hill one ends in Sonic taking damage from a Crabmeat, and the second causes Sonic to be stuck in a death loop. I have tested it with a stock data.rsdk from the latest paid and Forever releases, and in Data folder mode with the decompiled scripts.

**Comment by MGRich** [comment]
Please state your version you're using.
