### ISSUE TITLE
Sonic 2 Script

### ISSUE THREAD

**Issue by Ghaleonh41** [Rubberduckycooly/Sonic-1-2-2013-Decompilation#183]
Hello!

Great job with the Decompilations & scripts so far!

I have one issue that's coming up regarding Sonic 2. When using the new Scripts, the HUD changes to the extended time display whenever I score some points. But the score counter never increases.
![Untitled](https://user-images.githubusercontent.com/78719249/107182676-2d951080-69ab-11eb-8326-be891c34b74c.png)
![Untitled-2](https://user-images.githubusercontent.com/78719249/107182682-31c12e00-69ab-11eb-85e5-3eb37a5d1895.png)

**Comment by Rubberduckycooly** [comment]
that's a script bug, though its to do with the released version of the scripts, the ones on the repo are updated to fix that, but haven't got an official release yet, if you download those it should fix that bug

**Comment by Ghaleonh41** [comment]
Thank you very much! It worked!
