### ISSUE TITLE
Playing at any aspect ratio higher than 16:9 causes you to be unable to finish levels

### ISSUE THREAD

**Issue by Patlen123** [Rubberduckycooly/Sonic-1-2-2013-Decompilation#184]
I tried to set my window width to be 570 which seems to align with a 21:9 aspect ratio and the game works fine, however when you get to the end of a stage Sonic just runs in place without the end of act stuff coming up.

The mobile version seems to support non-standard aspect ratios just fine

**Comment by Patlen123** [comment]
I haven't tested with aspect ratios below 16:9 however

**Comment by scottjco** [comment]
Thats because of the way the scripts are coded, I have made some edits to Sonic 1 and 2s scripts to try and resolve issues like this.

https://github.com/scottjco/Sonic-1-Sonic-2-2013-Script-Decompilation

**Comment by Rubberduckycooly** [comment]
its a script bug, the decomp change change that, however it can be fixed via script mods
