### ISSUE TITLE
[Sonic 2] Proto Palace Zone cheat doesn't work in v1.1.1

### ISSUE THREAD

**Issue by ViperAcidZX** [Rubberduckycooly/Sonic-1-2-2013-Decompilation#187]
For some reason I can't get the cheat code for Proto Palace Zone to work at all in the current build of the Sonic Mobile Decompilation. I did the procedures and entered the codes correctly, but no matter what I tried I couldn't get the code for Proto Palace to work in v1.1.1. I tried the procedures in the Android version of Sonic 2 and it worked fine over there.

**The procedures I used in the Mobile Decompilation:**
1. Start a game in No Save Mode in Sonic 2.
2. Entered the Level Select cheat at the title screen (↑ ↑ ↑ ↓ ↓ ↓ ← → ← →) - confirmed working.
3. Entered the Debug Mode cheat in the sound test within the Level Select menu (01, 09, 09, 02, 01, 01, 02, 04 ) - confirmed working.
4. Entered the new Proto Palace cheat for the mobile ports in the sound test within the Level Select menu (03, 03, 03, 0B, 10, 10, 10, 04) - not working.

**Comment by SenpaiSharp** [comment]
I'm not overtly familiar with these cheat codes and exactly what the expected result is, but I followed your steps above in v1.1.1 and selected Hidden Palace Zone and it did take me to a "Proto Palace Zone" that was different. When I died I got sent back to regular Hidden Palace Zone. Is this the expected result?

**Comment by ViperAcidZX** [comment]
> I'm not overtly familiar with these cheat codes and exactly what the expected result is, but I followed your steps above in v1.1.1 and selected Hidden Palace Zone and it did take me to a "Proto Palace Zone" that was different. When I died I got sent back to regular Hidden Palace Zone. Is this the expected result?

I managed to get to work, though I'm not sure why it didn't work the other times I tried entering the code. I guess I'll close this issue now that is probably a mistake on my end.
