### ISSUE TITLE
Feature request: A setting for making Restart behave like in the official version

### ISSUE THREAD

**Issue by Redyn** [Rubberduckycooly/Sonic-1-2-2013-Decompilation#189]
For those of us who would like the game to behave as close as the official release as possible, could you please add an option to settings.ini called something like "RestartingSubtractsLives" that when set to true, would cause the Restart option in the pause menu subtract a life when used?

In my particular case, the reason I would like that option is the following. In the Android version of Sonic 2 I liked to use the Restart option in a special stage when I messed up so that I could try again, but that option was limited by number of lives. Here it's unlimited, so when I do that, it feels like I'm cheating.

I also liked how it gave me more of an incentive to collect 1ups -- they would double as extra tries in special stages.

**Comment by ToruTheRedFox** [comment]
and make restarting obviously not be possible if you have 0 lives

**Comment by MGRich** [comment]
This shouldn't be a setting but is rather an issue with the decomp itself in accuracy. I'll fix this myself on 1.2.0.

**Comment by Rubberduckycooly** [comment]
This has now been fixed, it'll be in the next build
