### ISSUE TITLE
S2 : Something's Off with the title card position..

### ISSUE THREAD

**Issue by trayfellow** [Rubberduckycooly/Sonic-1-2-2013-Decompilation#19]
![titleposition](https://user-images.githubusercontent.com/48515908/104921065-6d2f9480-59cb-11eb-87ff-a8a1b2d51fda.PNG)

is it just me or is the title card positioning off?

**Comment by JakeNagare** [comment]
I think that's a problem with v1.5.1 which has a few other issues as well.  Try v1.5.0 since it doesn't have that issue.

**Comment by MGRich** [comment]
Part of the scripts, so can't fix.
