### ISSUE TITLE
[Feature Request] Libretro core

### ISSUE THREAD

**Issue by parkerlreed** [Rubberduckycooly/Sonic-1-2-2013-Decompilation#192]
Would be great to have 1-2 and CD as cores for libretro/RetroArch.

**Comment by MGRich** [comment]
The decomps are in no way emulation, and wouldn't fit into something like RetroArch at all. If someone wants to try to get it running, though, that can be done in a fork.

**Comment by Awakened0** [comment]
@MGRich just FYI, but there are several libretroizations of game engines that aren't emulation. Stuff like cannonball (Outrun), NX Engine (Cave Story), PRBoom (Doom) or Craft (Minecraft clone). Some of the main RetroArch devs would love to see even more so the ecosystem isn't seen as only useful for emulators.

**Comment by MGRich** [comment]
Oh, that's great! I didn't know that. I'm keeping this closed, though, because it would moreso fit as a port, but it'd be cool to see eventually!
