### ISSUE TITLE
Missing ")" if RETRO_USE_HAPTICS are disabled

### ISSUE THREAD

**Issue by arczi84** [Rubberduckycooly/Sonic-1-2-2013-Decompilation#195]
In here:
https://github.com/Rubberduckycooly/Sonic-1-2-2013-Decompilation/blob/0204a4b56969db75236fd757d338e302a8038c8c/Sonic12Decomp/Script.cpp#L2177

**Comment by Rubberduckycooly** [comment]
finally got around to fixing this, it'll be in the next builds
