### ISSUE TITLE
egg gauntlet wont load

### ISSUE THREAD

**Issue by 121291** [Rubberduckycooly/Sonic-1-2-2013-Decompilation#196]
it crashes when i load it, how do i fix this

**Comment by ooowoothevirtualhowler** [comment]
I found this one time too and upon researching it, it looks like the files for Egg Gauntlet were actually removed in one early version of the non Sega Forever version of the app. They didn't remove the listing of it as a level though which is why it can still be selected.

**Comment by MGRich** [comment]
Some versions of the RSDK file have it, some don't. This is entirely RSDK specific and not the fault of the decomp.
