### ISSUE TITLE
Can't do the level select cheat on Nintendo 3DS

### ISSUE THREAD

**Issue by obscurerev** [Rubberduckycooly/Sonic-1-2-2013-Decompilation#197]
Since you can't tap the top screen, you can't unlock the level select. What you normally do is that you have to tap the SEGA letters and hold both thumbs down when you hear the chime. But since this is a 3DS, you can't do this. Could you possibly implement a button of some sort you could hold down on the touch screen when entering a game?

**Comment by ThornTSC** [comment]
Do the title screen (not SEGA screen, but after that) D-pad input versions of the codes not work on 3DS? They do work on other versions of the decompilation and on controllers for the original Android/iOS releases.

Sonic 1: Up, Down, Left, Right
Sonic 2: Up, Up, Up, Down, Down, Down, Left, Right, Left, Right

**Comment by obscurerev** [comment]
Nope, those combinations don't work at all.

**Comment by MGRich** [comment]
This is both in the scripts and port specific. There is probably a script mod out there that makes the code easier to preform, but we (and the port authors) don't have control over scripts.
