### ISSUE TITLE
Is there any way to start the game on a specific scene?

### ISSUE THREAD

**Issue by SneezingCactus** [Rubberduckycooly/Sonic-1-2-2013-Decompilation#20]
I don't know if this fits here, but is there any way to start the game on a specific scene (for example, starting the game on level select)? I can see there are 2 keys on the config file (StartingScene and StartingCatergory) that seem to do this, but I don't know how to make it work.

**Comment by MGRich** [comment]
The values are integers based off of the GameConfig. E.G. for CPZ1 (3rd scene in Regular, which is the 2nd category), you'd do `StartingScene=3` and `StartingCategory=1.`
![image](https://user-images.githubusercontent.com/29069561/104969664-bb826a80-59ae-11eb-9661-eab30c07ee3c.png)

**Comment by SneezingCactus** [comment]
When I do that, nothing happens and the config vars get set back to true.

**Comment by Tyberkid967** [comment]
Could Someone provide a List Of the StartList and StartStage Values?

**Comment by MGRich** [comment]
> When I do that, nothing happens and the config vars get set back to true.

I think this is fixed in master now? Check again when we release 1.1.0.


> Could Someone provide a List Of the StartList and StartStage Values?

The list is from the Gameconfig, so category 1 scene 0 is GHZ1 in Sonic 1, category 2 scene 5 is special stage 6 in both Sonic 1 and 2, etc.
