### ISSUE TITLE
How do i change the keyboard values?

### ISSUE THREAD

**Issue by NonzeroBacon478** [Rubberduckycooly/Sonic-1-2-2013-Decompilation#204]
I want to usa D,S,A to play cause i don´t like to use Z tu jump

**Comment by MGRich** [comment]
Your `settings.ini` file should have options and a quick link as reference to setting up input configs.

**Comment by NonzeroBacon478** [comment]
Tanks!

**Comment by VoidOfficial421** [comment]
..
