### ISSUE TITLE
Add Exclusive Fullscreen Mode

### ISSUE THREAD

**Issue by Awakened0** [Rubberduckycooly/Sonic-1-2-2013-Decompilation#205]
I'm running the 1.1.1 Windows release with Fullscreen set to true and Borderless set to false in the ini. With Gsync set to work only in full screen in the driver, it does not activate. It does activate if I set Gsync to work with windowed and full screen. Which would seem to indicate the application still running in a borderless window even when that's set to false.

**Comment by Awakened0** [comment]
I was just re-reading the settings.ini file. I didn't realize that the description of the Fullscreen and Borderless options refer to how to present a window. So the Borderless option only removes the border from around the window. It's not like other games where disabling Borderless enables exclusive fullscreen, so it is working as described.

So I'll rename this issue as a request to add an exclusive fullscreen mode. 

BTW, I've tried forcing exclusive fullscreen via Special K and OmniScaler, but neither work for this.

**Comment by Awakened0** [comment]
Another possible path to this would be to use [Direct3D 9Ex](https://docs.microsoft.com/en-us/windows/win32/direct3darticles/direct3d-9ex-improvements). That supports flip model fullscreen, which basically has all the benefits of exclusive fullscreen and windowed/borderless fullscreen. D3D10-12 also support it, but SpecialK shows the decomps as using D3D9. I assume it'd be easier to upgrade it to using 9Ex than D3D10 and up.

**Comment by Leonx254** [comment]
the decomps use SDL and opengl, not D3D9. And sorry but we aren't adding exclusive fullscreen
