### ISSUE TITLE
No disabling of logging

### ISSUE THREAD

**Issue by TopHatHipster** [Rubberduckycooly/Sonic-1-2-2013-Decompilation#21]
When I try to run either Sonic 1 or 2, the game will keep a log file despite having turned off the dev menu in the settings.ini.

This feature is available in your Sonic CD decompilation, as 'EngineDebugMode=false'. Would love to see this added as well!

**Comment by Rubberduckycooly** [comment]
honestly forgot it wasn't in this since they share a core codebase, it has been added and will be in the next build
