### ISSUE TITLE
BigEndian fix

### ISSUE THREAD

**Issue by arczi84** [Rubberduckycooly/Sonic-1-2-2013-Decompilation#210]
stageCnt has to be byte  on Big Endian platforms for DevMenu to work:

https://github.com/Rubberduckycooly/Sonic-1-2-2013-Decompilation/blob/d6257818a692380f6fbd9031d80fc4870b0812ab/Sonic12Decomp/Text.cpp#L406

**Comment by Rubberduckycooly** [comment]
bug has been fixed, will be in the next build
