### ISSUE TITLE
can't build

### ISSUE THREAD

**Issue by tailsjs** [Rubberduckycooly/Sonic-1-2-2013-Decompilation#211]
```
make: pkg-config: No such file or directory
mkdir -p objects/Sonic12Decomp
make: pkg-config: No such file or directory
x86_64-w64-mingw32-g++  -static -DBASE_PATH='""' Sonic12Decomp/Animation.cpp -o objects/Sonic12Decomp/Animation.cpp.o -c
mkdir -p objects/Sonic12Decomp
make: pkg-config: No such file or directory
x86_64-w64-mingw32-g++  -static -DBASE_PATH='""' Sonic12Decomp/Audio.cpp -o objects/Sonic12Decomp/Audio.cpp.o -c
mkdir -p objects/Sonic12Decomp
make: pkg-config: No such file or directory
x86_64-w64-mingw32-g++  -static -DBASE_PATH='""' Sonic12Decomp/Collision.cpp -o objects/Sonic12Decomp/Collision.cpp.o -c
mkdir -p objects/Sonic12Decomp
make: pkg-config: No such file or directory
x86_64-w64-mingw32-g++  -static -DBASE_PATH='""' Sonic12Decomp/Debug.cpp -o objects/Sonic12Decomp/Debug.cpp.o -c
In file included from Sonic12Decomp/Animation.cpp:1:
Sonic12Decomp/RetroEngine.hpp:159:10: fatal error: SDL.h: No such file or directory
  159 | #include <SDL.h>
      |          ^~~~~~~
compilation terminated.
In file included from Sonic12Decomp/Audio.cpp:1:
Sonic12Decomp/RetroEngine.hpp:159:10: fatal error: SDL.h: No such file or directory
  159 | #include <SDL.h>
      |          ^~~~~~~
compilation terminated.
In file included from Sonic12Decomp/Collision.cpp:1:
Sonic12Decomp/RetroEngine.hpp:159:10: fatal error: SDL.h: No such file or directory
  159 | #include <SDL.h>
      |          ^~~~~~~
compilation terminated.
In file included from Sonic12Decomp/Debug.cpp:1:
Sonic12Decomp/RetroEngine.hpp:159:10: fatal error: SDL.h: No such file or directory
  159 | #include <SDL.h>
      |          ^~~~~~~
compilation terminated.
make: *** [Makefile:37: objects/Sonic12Decomp/Debug.cpp.o] Error 1
make: *** Waiting for unfinished jobs....
make: *** [Makefile:37: objects/Sonic12Decomp/Audio.cpp.o] Error 1
make: *** [Makefile:37: objects/Sonic12Decomp/Collision.cpp.o] Error 1
make: *** [Makefile:37: objects/Sonic12Decomp/Animation.cpp.o] Error 1

```

**Comment by coreybruce** [comment]
Looks like your missing SDL

**Comment by altiereslima** [comment]
$ cd Sonic-1-2-2013-Decompilation
make CXX=x86_64-w64-mingw32-g++ CXXFLAGS=-static -j9
make: pkg-config: No such file or directory
mkdir -p objects/RSDKv4
make: pkg-config: No such file or directory
x86_64-w64-mingw32-g++  -static -DBASE_PATH='""' -std=c++17 RSDKv4/Animation.cpp -o objects/RSDKv4/Animation.cpp.o -c
mkdir -p objects/RSDKv4
make: pkg-config: No such file or directory
mkdir -p objects/RSDKv4
x86_64-w64-mingw32-g++  -static -DBASE_PATH='""' -std=c++17 RSDKv4/Audio.cpp -o objects/RSDKv4/Audio.cpp.o -c
make: pkg-config: No such file or directory
x86_64-w64-mingw32-g++  -static -DBASE_PATH='""' -std=c++17 RSDKv4/Collision.cpp -o objects/RSDKv4/Collision.cpp.o -c
mkdir -p objects/RSDKv4
make: pkg-config: No such file or directory
x86_64-w64-mingw32-g++  -static -DBASE_PATH='""' -std=c++17 RSDKv4/Debug.cpp -o objects/RSDKv4/Debug.cpp.o -c
In file included from RSDKv4/Audio.cpp:1:
RSDKv4/RetroEngine.hpp:195:10: fatal error: SDL.h: No such file or directory
  195 | #include <SDL.h>
      |          ^~~~~~~
compilation terminated.
In file included from RSDKv4/Animation.cpp:1:
RSDKv4/RetroEngine.hpp:195:10: fatal error: SDL.h: No such file or directory
  195 | #include <SDL.h>
      |          ^~~~~~~
compilation terminated.
make: *** [Makefile:37: objects/RSDKv4/Animation.cpp.o] Error 1
make: *** Waiting for unfinished jobs....
make: *** [Makefile:37: objects/RSDKv4/Audio.cpp.o] Error 1
In file included from RSDKv4/Collision.cpp:1:
RSDKv4/RetroEngine.hpp:195:10: fatal error: SDL.h: No such file or directory
  195 | #include <SDL.h>
      |          ^~~~~~~
compilation terminated.
make: *** [Makefile:37: objects/RSDKv4/Collision.cpp.o] Error 1
In file included from RSDKv4/Debug.cpp:1:
RSDKv4/RetroEngine.hpp:195:10: fatal error: SDL.h: No such file or directory
  195 | #include <SDL.h>
      |          ^~~~~~~
compilation terminated.
make: *** [Makefile:37: objects/RSDKv4/Debug.cpp.o] Error 1

**Comment by altiereslima** [comment]
Windows 10

**Comment by coreybruce** [comment]
> Windows 10

Looks like your also missing SDL, please install it for Windows 10 than try again. I don't know the instructions needed for Windows as I've been building for Windows but I think it's on the readme 

https://www.libsdl.org/download-2.0.php

**Comment by jfrmilner** [comment]
I had the same issue, you need to install `mingw-w64-pkg-config` to build with MSYS2 on Windows 10. 

> pacman -S mingw-w64-pkg-config
