### ISSUE TITLE
[1.2.0] Menu.rsdk?

### ISSUE THREAD

**Issue by ViperAcidZX** [Rubberduckycooly/Sonic-1-2-2013-Decompilation#212]
I compiled an executable from the 1.2.0 branch of the mobile decompilation, and looking through its configuration file, I noticed there's a second file it loads called **Menu.rsdk**. Is there a way to get this file from the *.apk files of Sonic 1/2 or is this something being developed for the upcoming 1.2.0 release of the mobile decompilation?

**Comment by guest123guest** [comment]
Interesting, is this related with the main menu shown in the original mobile ports? I thought those were separate....
