### ISSUE TITLE
Unable to compile on Arch Linux

### ISSUE THREAD

**Issue by diamonop1234** [Rubberduckycooly/Sonic-1-2-2013-Decompilation#214]
All dependencies have been installed; yet when I run `make -j9` I get this issue:
```RSDKv4/Userdata.cpp: In function ‘void initMods()’:
RSDKv4/Userdata.cpp:823:10: error: ‘std::filesystem’ has not been declared
  823 |     std::filesystem::path modPath(modBuf);
      |          ^~~~~~~~~~
```
A full compilation log is attached:
[log.txt](https://github.com/Rubberduckycooly/Sonic-1-2-2013-Decompilation/files/6408759/log.txt)

**Comment by coreybruce** [comment]
Having the same issue on Manjaro

**Comment by Rubberduckycooly** [comment]
should be fixed now! Forgot to set the C++ ver to 17 (required for mod loader)
