### ISSUE TITLE
xbrz support

### ISSUE THREAD

**Issue by natepley** [Rubberduckycooly/Sonic-1-2-2013-Decompilation#215]
It would be really nice to have the option of xbr or xbrz scaling.  That way, we can choose whether we want sharp pixels or smooth curves.  If it's not too hard to implement, it would be greatly appreciated!

**Comment by JoeWeigmanVideo** [comment]
There's no other filters available to choose from so I don't see why there'd be any reason to implement these two, plus I'm sorry but xrbz filters look horrible LOL

**Comment by natepley** [comment]
I'm not suggesting that other filters shouldn't be added.  I only suggested these two because those are the ones that I would use and want.  Not having something is not a very logical reason to not add it.  Plus, there's no reason to shit on someone's opinion.  You don't like the filter, but I do.  That's why many different filters exist.

**Comment by JoeWeigmanVideo** [comment]
I assure you if the RSDKv4 decomp team really wanted to go through the trouble of adding filters in the first place xrbz would not be on their priorities. If you really want xrbz or any other filter for the go download reshade or some other program that can overlay filters on games.

**Comment by ClockworkBastard** [comment]
I vote for SABR shader! :) In my very professional designer opinion, it smooths cartoon graphics to perfect vector look alike.
As for me, I dunno if it is easy, like @natepley said, but I think that is rather hard! So we just sit and wait... Until someone want to donate money? I think @Rubberduckycooly wont refuse and do implement XBRZ, as long as it is easy ;)

**Comment by natepley** [comment]
SABR is pretty cool too, though I don't have as much experience with it.

**Comment by ToruTheRedFox** [comment]
hardware rendering needs to come first
