### ISSUE TITLE
Feature request: Labyrinth Act 1 upper path added ring 

### ISSUE THREAD

**Issue by Ducky27** [Rubberduckycooly/Sonic-1-2-2013-Decompilation#221]
In one of the revisions of Sonic 1 genesis they added a ring to the labyrinth zone act 1 hidden path so people could get 50 rings on it and go to the special stage. This was removed in the mobile port of Sonic 1. So I'm asking for that ring to be added back in which would be a massive qol improvement and not punish people that haven't gotten all chaos emeralds at that point for going the upper route

**Comment by JoeWeigmanVideo** [comment]
This could easily modded in, and in fact, already has. See: https://gamebanana.com/mods/150212

**Comment by Ducky27** [comment]
Well that's good but this isn't something that should be locked behind a mod, a lot of people probably won't know about this and it would just be better overall for this to be something added into the base game

**Comment by Ducky27** [comment]
Also modding this game is a lot harder than something like mania or the adventure games (I mean i can't even mod this properly) so yeah more reason to have this be in the base game

**Comment by MegAmi24** [comment]
This literally can't be added, the decomp does not control any of the games' level layouts
