### ISSUE TITLE
(Sonic 2) Loop Clipping in ARZ1

### ISSUE THREAD

**Issue by gatonegro304** [Rubberduckycooly/Sonic-1-2-2013-Decompilation#222]
I'm having an issue in Aquatic Ruin Zone, and that issue is that in the loop at the top near the end of arz1, it haves a werid collision bug that doesn't let me get to the other part of the loop, and when i'e try to spindash through it, a clip bug happens and then i've fall.

https://user-images.githubusercontent.com/83138974/118895495-a970f400-b8dc-11eb-854a-7407f033b99a.mp4

i've tried disabling all the mod i've haved enabled, but the issue still happens.

**Comment by delta7890** [comment]
Can confirm.  Definite collision issue.  If you go through the loop and then backtrack without touching any other stage geometry it's fine, but if you jump onto the terrain seen at the start of the video to the upper-right for example, you're barred from going back through the loop.  The collision issue seems to effect the entire height of the "pillar" that makes up the right wall of the loop.

**Comment by MegAmi24** [comment]
This is a bug in the original game
