### ISSUE TITLE
Scanlines

### ISSUE THREAD

**Issue by cjdw94** [Rubberduckycooly/Sonic-1-2-2013-Decompilation#226]
@Rubberduckycooly 

Is there any easy way to add scanlines into the decomps?  I know they aren't really necessary with the raw resolution support, but I just love playing these games with scanlines, and I haven't found a mod that would enable them.

**Edit:** I should probably mention I'm playing the Switch forks, but I'm hoping the answer would be universal.

**Comment by Rubberduckycooly** [comment]
There's no easy way, as the backed is based on SDL2 so there'd need to be stuff added to manage and load shaders, since they're the most efficient way of doing scanlines. However, it's not impossible to do, it just won't be done on the main branch. Maybe someone will add it to their fork/mod

**Comment by cjdw94** [comment]
Thanks for getting back so quick!   =D
