### ISSUE TITLE
Add an option to unhook the physics from the framerate?

### ISSUE THREAD

**Issue by coolpringles** [Rubberduckycooly/Sonic-1-2-2013-Decompilation#227]
I would love to see this run at 165hz but since the physics and animations are tied to the framerate, if I do that it just speeds up. Is there anything you could do, like add an option to untie it in the config? If not I completely understand.

Thanks lol

**Comment by ToruTheRedFox** [comment]
can't be done unfortunately

**Comment by coolpringles** [comment]
oh well, that's too bad
