### ISSUE TITLE
Settings.ini keeps resetting; won't recognize my controller

### ISSUE THREAD

**Issue by Malckeor** [Rubberduckycooly/Sonic-1-2-2013-Decompilation#228]
This was working fine on my desktop at home.

So I'm using a PS5 controller and I set my controller to [Wireless Controller] in place of [Controller 1] when I connect it to the computer. Problem is, on this shitty laptop, my settings.ini file resets ONLY THE CONTROLLER PART when booting up the game, thus not recognizing my controller.

I tried setting the settings.ini to read-only but it's still not recognizing my controller. What the hell is happening?! Please help!

**Comment by MegAmi24** [comment]
Make sure the decomp isn't running when you save settings.ini
