### ISSUE TITLE
Two inputs from one key on keyboard

### ISSUE THREAD

**Issue by Jaffacakelover** [Rubberduckycooly/Sonic-1-2-2013-Decompilation#229]
If I press X on my keyboard while in-game, it makes Sonic jump _and_ opens the Pause menu.
X is only bound to one function in the settings.ini.

**Comment by Rubberduckycooly** [comment]
That's a bug in the sega forever version, nothing we can do about it. Use a pre-sega forever version if you *really* need it fixed
