### ISSUE TITLE
21:9 Softlocks and other playability issues

### ISSUE THREAD

**Issue by SeventhSentinel** [Rubberduckycooly/Sonic-1-2-2013-Decompilation#23]
![image](https://user-images.githubusercontent.com/19996267/104953907-51a99700-5995-11eb-86e9-730b5c5ef4e8.png)
I was messing around to see what ridiculous resolutions I could run this at when I stumbled across this. Sonic's been walking in place for a couple minutes now. ScreenWidth is set to 570 (for 21:9 aspect) in this screenshot. Obviously this is not a big deal given the game was designed for 16:9 screens, but it's worth noting.

Softlocks:
- Player dies after breaking the Egg Capsule in SYZ3 if ScreenWidth is above 432
- Player walks in place at end of EHZ1, CPZ1, ARZ1, CNZ1, HTZ1, MCZ1, OOZ1, MZ1, MZ2 if ScreenWidth is above 504

Other issues:
- Player MAY die after passing the level end sign in SYZ2 if ScreenWidth is above 444
- Mystic Cave, Oil Ocean bosses may be completely skipped if ScreenWidth is above 512

**Comment by MGRich** [comment]
Sadly, this is a script error, and thus nothing we can do on the game's part.
