### ISSUE TITLE
How do I run sonic 1 and 2 if I bought the games already on iPadOS/iOS?

### ISSUE THREAD

**Issue by De-x** [Rubberduckycooly/Sonic-1-2-2013-Decompilation#231]
I bought the game on iPadOS or iOS and I am running windows. I am a bit confused on how I can run the game because all of the tutorials I could find are android.

**Comment by Ducky27** [comment]
As far as I know this decompilation isn't compatible with the iOS version of the game, you need the Android APK to get this to run
