### ISSUE TITLE
Having A LOT of Bugs (Sonic 2)

### ISSUE THREAD

**Issue by BaseGuyMent** [Rubberduckycooly/Sonic-1-2-2013-Decompilation#234]
There's so many things to list off:

1. [The splash of the water in Aquatic Ruins Zone is glitched and turns into bugged Sonic running sprites for some reason.](https://imgur.com/a/6J3vOf4) [Also, the boss is glitched as well](https://imgur.com/GavYQ1o).
2. Super Sonic turns into Dark Sonic (lol) when I go into the water.
3. The ending cutscene is also bugged.

I'll take screenshots and put them on Imgur as soon as I can.

**Comment by JoeWeigmanVideo** [comment]
You aren't using the most recent version of the decomp. These are all issues that were present in the very first release from last January or so.

**Comment by BaseGuyMent** [comment]
> You aren't using the most recent version of the decomp. These are all issues that were present in the very first release from last January or so.

@JoeWeigmanVideo Oops, my bad. I'm such a noob. Link to the newest version?

**Comment by JoeWeigmanVideo** [comment]
https://github.com/Rubberduckycooly/Sonic-1-2-2013-Decompilation/releases/tag/v1.1.2.1
![image](https://user-images.githubusercontent.com/77771604/123850913-ce8f5400-d8d7-11eb-8fe6-173a4fb319ed.png)
