### ISSUE TITLE
Should prevent the computer from sleeping on Linux

### ISSUE THREAD

**Issue by Kekun** [Rubberduckycooly/Sonic-1-2-2013-Decompilation#24]
I was playing and my screen started to dim to prepare the computer to go to sleep, that's because the graphics server noticed no input (I was playing with a gamepad and it doesn't check that). There are ways to make an app ask the OS to not go to sleep while it runs (e.g. video players do that) and we should do it here too.

**Comment by MGRich** [comment]
Fixed in 789e06eddf73256343c6fe7e2c2a0cd930cda6ba.
