### ISSUE TITLE
(carried from original mobile port) when jumping out of shallow water sometimes extreme vertical momentum is given to sonic

### ISSUE THREAD

**Issue by kianiscoooooool** [Rubberduckycooly/Sonic-1-2-2013-Decompilation#242]
ive experienced this one on the original mobile port, i think i know how its caused. When your under water your physics are changed, and when you breach out of water math is applied to speed you up depending on how much momentum you had under water. So when your in water your physics are made half, and when you jump out theyre made normal, but you would jump out super slow without math to make your slow momentum into fast out of water momentum. Basically when you breach the water surface your physics are multiplied to acount for being out of the water. the collision for shallow water is glitchy in the mobile port, so i think when you land in the shallow water your not in the water so your physics were never slowed down but you can still jump out, so when you jump out it multiplys your physics anyways and you go flying up. TLDR, enter water, .5 movement speed, leave water, x2 current to equal 1 movement speed, glitchyness causes leaving water without entereing water which means x2 current to equal 2 movement speed.

**Comment by Rubberduckycooly** [comment]
this is a bug in the mobile version, so it's not gonna be fixed here
