### ISSUE TITLE
Sound effects cut out

### ISSUE THREAD

**Issue by kianiscoooooool** [Rubberduckycooly/Sonic-1-2-2013-Decompilation#243]
Sometimes when doing things such as getting a extra life, the sound effect that plays before the music speeds up when you get speed shoes, or when a bomb blows up in starlight zone, the sound effect wont play which causes the whole game to go mute until the sound effect is done, then the sound goes back to normal after the sound effect has played

**Comment by Rubberduckycooly** [comment]
this has been fixed and will be in the next release
