### ISSUE TITLE
Issues with Mac

### ISSUE THREAD

**Issue by ThomasfanSQB** [Rubberduckycooly/Sonic-1-2-2013-Decompilation#248]
1. **Incorrect Color Palettes** - I know this is a nitpick, but how the color palettes translate to Mac REALLY bothers me! Can you please fix them for MacOS?
2. **Mods that use text scripts ruin the game** - When turning on a mod with "Txtscripts" set to "true", the game becomes broken and unplayable. I have no idea why this is the case, but it is (it's back to normal when the mod is off).
3. **Updating the Mac section** - The link you provided only shows Sappharad's 1.0.0 Mac build and not the later releases he did. Maybe replace that second bullet point with "or head over to Sappharad's fork".

That's all the major issues I found with this, so please fix them in the next update. 

Sincerely,
ThomasfanSQB :-)

**Comment by ThomasfanSQB** [comment]
The first two options might also be issues for Sonic CD.

**Comment by MegAmi24** [comment]
1. It's hard to know what you're talking about without any screenshots
2. [Install the decompiled scripts](https://github.com/Rubberduckycooly/Sonic-1-Sonic-2-2013-Script-Decompilation/archive/refs/heads/user.zip)
3. Will be fixed soon
