### ISSUE TITLE
Hide the mouse pointer on fullscreen

### ISSUE THREAD

**Issue by Kekun** [Rubberduckycooly/Sonic-1-2-2013-Decompilation#25]
IDK about other OSes but on Linux we can still see the mouse pointer when it's on the window, which is acceptable when the window is floating or maximized, but feels odd when it's fullscreened. We probably should hide the pointer on fullscreen.

**Comment by SeventhSentinel** [comment]
Can confirm this also happens on Windows 7.

**Comment by FreshRoyal** [comment]
Also happens on Windows 10

**Comment by Rubberduckycooly** [comment]
fixed, this will be in the next build
