### ISSUE TITLE
Newest Data.rsdk (both for s1 and s2) glitches Xinput controller behavior

### ISSUE THREAD

**Issue by ClockworkBastard** [Rubberduckycooly/Sonic-1-2-2013-Decompilation#254]
_I know reverse engineering is a semi-black alchemy, but you gotta knew the issues! Thanks for your work. You've made billions of people happier!_ 

Release v1.1.2 (_rev01 gives a "funny" softlock at the title screen. It continue to shimmer that one star with the sound and nothing ever happen more https://ibb.co/BgW71zy
Sonic1 no showing Tails near him, on button pressed fadeout and that's all folks)

The today's issue

Button mapping is totally ruined for newest Data.rsdk's

Tried firstly with s2, now tried s1, the newest one - totally the same

The issue with the Data.rsdk (from v1.4.8.b)
v1.2.9 works great!

That issue:
The button I made for (B) presses B+start button
A is fine, Start is fine, some weird Z\C even works

Some random tests even gave me turbo button... What a new way to play Sonic 2?

Gamepad is **[RETROFLAG Game Controller Classic Retro Wired USB Gamepad](https://www.amazon.com/Retroflag-Classic-Gaming-Controller-Switch/dp/B07JMQ5YFL)**
Set to XBOX Controller, showing in system like that
<<—no way! I cannot believe that!—>>
**Unplugged the controller at all and the Keyboard controls doing exactly the same!**
Bonus issue
I started it all over again today — redownloaded the newest Data.rsdk's to check if I can't run any mods because of that!.. NOPE
But that's until next time!

Best regards
Nikolai

**Comment by MegAmi24** [comment]
The b button pausing is an issue with the game's scripts, not a controller bug. You can use the [decompiled scripts](https://github.com/Rubberduckycooly/Sonic-1-Sonic-2-2013-Script-Decompilation) to fix the issue.

**Comment by MegAmi24** [comment]
Regarding your "bonus issue", what does your mod folder look like?

**Comment by ClockworkBastard** [comment]
**First of all, thanks for an instant answer!**
And yes! **90% of the issues is solved**

I downloaded the master branch archive and put the `scripts` folder (from the *-master\Sonic 2\) into the main folder where `RSDKv4_64.exe` is (so as the `mods` folder, and every mod there in a separate folder with `Mod.ini` in it. I'm quite a bit experienced dude since original half-life times)

**And yes!** now none of the mods crashed the game, almost every one tested yesterday - worked (a question to the modder)
**But** the (b)+(start) issue had **not solved running the games with no mods**. 
The "funny thing" is that mod called ["Sonic 2 Menu Recreation"](https://gamebanana.com/mods/306462) by Leonx254 fixes that (B)+(start) issue!!!
I don't want to be rude but branch-scripts looks like still imperfect.

If you wish — I will reinstall everything from the scratch to find out, what is wrong, and why (and do I) am the only who stumbled on that problem.
"_rev01" still has that very softlock glitch

I really want to help development as much as I can, and to help those poor bastards like me, who can't enjoy that very great stuff
Thank you in person - @MegAmi24 
Looks we are so close to the **decompilation Release v1.1.3** !? ;)

**Comment by MegAmi24** [comment]
the game only runs the decompiled scripts (which fixes the pause issue) if it can't find the bytecode files or when a script mod is running, you can get the game to run the scripts by either running a script mod (a script mod has "TxtScripts=true" in the mod.ini) or using data folder mode and deleting the bytecode folder

Also the next update will be 1.3.0 :)

**Comment by ClockworkBastard** [comment]
"you can get the game to run the scripts by either running a script mod (a script mod has "TxtScripts=true" in the mod.ini) or using data folder mode and deleting the bytecode folder"
Sorry I didn't get it...
Running the game with no mods activated with newer scripts folder in it not fixing a B+start issue.
Yet it do fix the game being hung while any mod loaded! So it do works.
Let's just wait for a newer version, because it's ok for me to run that one particular mod in any play.
Sorry for being away for some time.
