### ISSUE TITLE
Needs a license (kept open as a spot for legal discussion)

### ISSUE THREAD

**Issue by Kekun** [Rubberduckycooly/Sonic-1-2-2013-Decompilation#26]
What about GPL? Or MIT maybe?

**Comment by Cogboy** [comment]
From my understanding this project is a decompiling of a proprietry engine which really means the code here really shouldn't be distributed at all or relicensed. 

As much as it is great to have these ports on PC, I would not be surprised if the repos get pulled in the near future.

**Comment by sedmegreenaway** [comment]
> From my understanding this project is a decompiling of a proprietry engine which really means the code here really shouldn't be distributed at all or relicensed.
> 
> As much as it is great to have these ports on PC, I would not be surprised if the repos get pulled in the near future.

I agree on the whole thing where it shouldn't be relicensed, but SEGA usually doesn't interfere much with fan projects. I suppose in this case they might, since it renders their monetization of the Sonic 1 and 2 mobile ports somewhat moot.

**Comment by Kekun** [comment]
I'll investigate the distributability of such code.

**Comment by Cogboy** [comment]
> > From my understanding this project is a decompiling of a proprietry engine which really means the code here really shouldn't be distributed at all or relicensed.
> > As much as it is great to have these ports on PC, I would not be surprised if the repos get pulled in the near future.
> 
> I agree on the whole thing where it shouldn't be relicensed, but SEGA usually doesn't interfere much with fan projects. I suppose in this case they might, since it renders their monetization of the Sonic 1 and 2 mobile ports somewhat moot.

Less SEGA and more Christian Whitehead considering it's his product. I'm not sure his standing on redistributing his game engine code.

> I'll investigate the distributability of such code.
Copyright law is pretty clear cut methinks.

**Comment by Kekun** [comment]
Except this is neither Christian's sources not the distributed binary, and reverse engineering is allowed to some extent… but I don't know to which extent, and if we crossed the border or not.

**Comment by MGRich** [comment]
Reverse engineering it is not against copyright law. Most of the code here is more-or-less custom, anyway. Infact, we are getting subtle help from the developers from afar. I'm keeping this issue open for more discussion, however, but we are not adding a license.

**Comment by Cogboy** [comment]
> 
> 
> Except this is neither Christian's sources nor the distributed binary, and reverse engineering is allowed to some extent… but I don't know to which extent, and if we crossed the border or not.

>Reverse engineering it is not against copyright law. Most of the code here is more-or-less custom, anyway. Infact, we are getting subtle help from the developers from afar. The only way we'd get taken down is if Sonic was directly referenced in any assets. I'm keeping this issue open for more discussion, however, but we are not adding a license.

Fair dos. In my eyes though a decompliation implies that compiled binary code has be decompiled into readable source code rather than reverse-engineering. Might be worth clarifying that somewhere so that muppets like me don't misinterpreate the project.

**Comment by Clownacy** [comment]
If reverse-engineering is so exempt from copyright law then why the hell did [my decompilation get DMCA'd](https://github.com/github/dmca/blob/master/2020/11/2020-11-19-nicalis.md)?

**Comment by Rubberduckycooly** [comment]
> If reverse-engineering is so exempt from copyright law then why the hell did [my decompilation get DMCA'd](https://github.com/github/dmca/blob/master/2020/11/2020-11-19-nicalis.md)?

While reverse-engineering is pretty fair game since its not direct piracy, different companies handle this kinda stuff differently. We're greatful Sega doesn't take this down themselves, because should they want to they'd probably have every right to do so (and there wouldn't be much we could do)

**Comment by MGRich** [comment]
To add to this, this decomp is similar enough like the SM64 decomp, which is handwritten recompiled code with assets needed to run, of which Nintendo, the more typical trigger-happy company, can't take down.

**Comment by MGRich** [comment]
just realized i could just close and pin LOL

**Comment by Rings4** [comment]
> 
> 
> > From my understanding this project is a decompiling of a proprietry engine which really means the code here really shouldn't be distributed at all or relicensed.
> > As much as it is great to have these ports on PC, I would not be surprised if the repos get pulled in the near future.
> 
> I agree on the whole thing where it shouldn't be relicensed, but SEGA usually doesn't interfere much with fan projects. I suppose in this case they might, since it renders their monetization of the Sonic 1 and 2 mobile ports somewhat moot.

I'd argue that it may boost sales in the mobile ports of the games, since those are required for this decompilation to work in the first place.

**Comment by MGRich** [comment]
We are encouraging to download the mobile ports as much as we can, yes. We've had to tell people why they shouldn't just download from an APK site quite often in various Discords cause of it.

**Comment by Rings4** [comment]
> 
> 
> We are encouraging to download the mobile ports as much as we can, yes. We've had to tell people why they shouldn't just download from an APK site quite often in various Discords cause of it.

Yeah, I know a few people who bought S3&K on Steam solely because of Sonic 3 AIR. I'm sure the same can apply here, even moreso since this decompilation can apparently be made to run on multiple platforms and systems.

**Comment by Clownacy** [comment]
Update: 531e3b9c11a7e710c34bd70589036476060ee5dc added The Unlicence.

**Comment by Clownacy** [comment]
The license has now been changed to a custom non-commercial one in 2ba9236438cb12c61b00554cb056ee5d3e7f08de.

**Comment by asm95** [comment]
As @Rubberduckycooly said, every project will depend on how the original developers treat their product. In some cases, they won't tolerate this kind of derived work and it's all up to the reverse team to decide whether is worth to waste their time in legal battles. Most of them won't and simply will shutdown the project.

We have luck that SEGA have a good relationship with the modding community as it doesn't see them as threat to their business (yet).

**Comment by tedmakesstuff** [comment]
> > We are encouraging to download the mobile ports as much as we can, yes. We've had to tell people why they shouldn't just download from an APK site quite often in various Discords cause of it.
> 
> Yeah, I know a few people who bought S3&K on Steam solely because of Sonic 3 AIR. I'm sure the same can apply here, even moreso since this decompilation can apparently be made to run on multiple platforms and systems.

I was one of them.

**Comment by kia100** [comment]
> I'd argue that it may boost sales for the mobile ports of the games, since those are required for this decompilation to work in the first place.

Firstly, sorry for coming late into the discussion, and secondly, I think SEGA's main source of income from the mobile ports is the payment to remove ADs, not the download itself. You just download the game, turn it into an APK or use software like iTunes 2017 to get an iPA, and then you extract the files. And the ADs? Nope, none of those here.
