### ISSUE TITLE
MSYS2 Compilation is broken

### ISSUE THREAD

**Issue by Jackobo-Chocobo** [Rubberduckycooly/Sonic-1-2-2013-Decompilation#266]
Tested on MainMenuRewrite branch.

Compilation errors on socket libs and opengl functions.

Solutions applied :

->Use : pacman -S make git mingw-w64-i686-gcc mingw-w64-x86_64-gcc mingw-w64-x86_64-SDL2 mingw-w64-x86_64-libogg mingw-w64-x86_64-libvorbis mingw-w64-x86_64-glew

-> Modifications applied on Makefile : 
```
 CXXFLAGS_ALL = $(shell pkg-config --cflags --static sdl2 vorbisfile vorbis glew) $(CXXFLAGS) \
               -DBASE_PATH='"$(BASE_PATH)"' \
               -DGLEW_STATIC \
               -IRSDKv4/ \
               -IRSDKv4/NativeObjects/ \
               -Idependencies/all/asio/include/ \
               -Idependencies/all/stb-image/ \
               -Idependencies/all/tinyxml2/

LDFLAGS_ALL = $(LDFLAGS)
LIBS_ALL = $(shell pkg-config --libs --static sdl2 vorbisfile vorbis glew) -lopengl32 -lws2_32 -pthread $(LIBS)

SOURCES = \
          dependencies/all/tinyxml2/tinyxml2.cpp \
	  RSDKv4/Animation.cpp     \
          RSDKv4/Audio.cpp         \
          RSDKv4/Collision.cpp     \
          RSDKv4/Debug.cpp         \
          RSDKv4/Drawing.cpp       \
          RSDKv4/Ini.cpp           \
          RSDKv4/Input.cpp         \
          RSDKv4/main.cpp          \
          RSDKv4/Math.cpp          \
	  RSDKv4/ModAPI.cpp        \
	  RSDKv4/Networking.cpp	   \
          RSDKv4/Object.cpp        \
          RSDKv4/Palette.cpp       \
          RSDKv4/Reader.cpp        \
          RSDKv4/Renderer.cpp      \
          RSDKv4/RetroEngine.cpp   \
          RSDKv4/Scene.cpp         \
          RSDKv4/Scene3D.cpp       \
          RSDKv4/Script.cpp        \
          RSDKv4/Sprite.cpp        \
          RSDKv4/String.cpp        \
          RSDKv4/Text.cpp          \
          RSDKv4/Userdata.cpp      \
          RSDKv4/NativeObjects/AboutScreen.cpp \
          RSDKv4/NativeObjects/AchievementDisplay.cpp \
          RSDKv4/NativeObjects/AchievementsButton.cpp \
          RSDKv4/NativeObjects/AchievementsMenu.cpp \
          RSDKv4/NativeObjects/BackButton.cpp \
          RSDKv4/NativeObjects/CWSplash.cpp \
          RSDKv4/NativeObjects/CreditText.cpp \
          RSDKv4/NativeObjects/DialogPanel.cpp \
          RSDKv4/NativeObjects/FadeScreen.cpp \
          RSDKv4/NativeObjects/InstructionsScreen.cpp \
          RSDKv4/NativeObjects/LeaderboardsButton.cpp \
          RSDKv4/NativeObjects/MenuBG.cpp \
          RSDKv4/NativeObjects/MenuControl.cpp \
          RSDKv4/NativeObjects/ModInfoButton.cpp \
          RSDKv4/NativeObjects/ModsButton.cpp \
          RSDKv4/NativeObjects/ModsMenu.cpp \
          RSDKv4/NativeObjects/MultiplayerButton.cpp \
          RSDKv4/NativeObjects/MultiplayerHandler.cpp \
          RSDKv4/NativeObjects/MultiplayerScreen.cpp \
          RSDKv4/NativeObjects/OptionsButton.cpp \
          RSDKv4/NativeObjects/OptionsMenu.cpp \
          RSDKv4/NativeObjects/PauseMenu.cpp \
          RSDKv4/NativeObjects/PlayerSelectScreen.cpp \
          RSDKv4/NativeObjects/PushButton.cpp \
          RSDKv4/NativeObjects/RecordsScreen.cpp \
          RSDKv4/NativeObjects/RetroGameLoop.cpp \
          RSDKv4/NativeObjects/SaveSelect.cpp \
          RSDKv4/NativeObjects/SegaIDButton.cpp \
          RSDKv4/NativeObjects/SegaSplash.cpp \
          RSDKv4/NativeObjects/SettingsScreen.cpp \
          RSDKv4/NativeObjects/StaffCredits.cpp \
          RSDKv4/NativeObjects/StartGameButton.cpp \
          RSDKv4/NativeObjects/SubMenuButton.cpp \
          RSDKv4/NativeObjects/TextLabel.cpp \
          RSDKv4/NativeObjects/TimeAttack.cpp \
          RSDKv4/NativeObjects/TimeAttackButton.cpp \
          RSDKv4/NativeObjects/TitleScreen.cpp \
          RSDKv4/NativeObjects/VirtualDPad.cpp \
          RSDKv4/NativeObjects/VirtualDPadM.cpp \
          RSDKv4/NativeObjects/ZoneButton.cpp \
   
ifneq ($(FORCE_CASE_INSENSITIVE),)
	CXXFLAGS_ALL += -DFORCE_CASE_INSENSITIVE
	SOURCES += RSDKv4/fcaseopen.c
endif

objects/%.o: %
	mkdir -p $(@D)
	$(CXX) $(CXXFLAGS_ALL) -std=c++17 $^ -o $@ -c

bin/RSDKv4: $(SOURCES:%=objects/%.o)
	mkdir -p $(@D)
	$(CXX) $(CXXFLAGS_ALL) $(LDFLAGS_ALL) $^ -o $@ $(LIBS_ALL)

install: bin/RSDKv4
	install -Dp -m755 bin/RSDKv4 $(prefix)/bin/RSDKv4

clean:
	rm -r -f bin && rm -r -f objects

```

Leonx254 said no one uses linux for him ( https://github.com/Rubberduckycooly/Sonic-1-2-2013-Decompilation/commit/a2f32e3194ec6f5b812fa4570639be7938cb3c98 ). But for me, I use Windows and Linux : however no one uses Visual Studio only to compile open source projects ;)

**Comment by Jackobo-Chocobo** [comment]
VCRUNTIME is an error about compilation on Visual Studio. Here I used MSYS2 tools to compile the source code.

**Comment by Jackobo-Chocobo** [comment]
![image](https://user-images.githubusercontent.com/81476994/137528408-dc4e0a08-a8b8-46e3-86b1-e4337bcf66a2.png)

As you can see here, the compilation is the STATIC method. So libraries / dlls are included in the exe file. Follow the steps to compile the project on MSYS2 :

-> Download the newest version of the MSYS2 installer from https://www.msys2.org/ and install it.
-> Run the MINGW64 prompt (from the windows Start Menu/MSYS2 64-bit/MSYS2 MinGW 64-bit), when the program starts enter pacman -Syuu in the prompt and hit Enter. Press Y when it asks if you want to update packages. If it asks you to close the prompt, do so, then restart it and run the same command again. This updates the packages to their latest versions.
-> Now install the dependencies with the following command: pacman -S make git mingw-w64-i686-gcc mingw-w64-x86_64-gcc mingw-w64-x86_64-SDL2 mingw-w64-x86_64-libogg mingw-w64-x86_64-libvorbis mingw-w64-x86_64-glew
-> Download the MainRewrite branch source code of the project 
-> Go into the repo you just cloned with cd Sonic-1-2-2013-Decompilation-MainMenuRewrite
-> Follow the steps in .\dependencies\all : you have to download some dependencies : read the file dependencies.txt for that
-> Then run make CXX=x86_64-w64-mingw32-g++ CXXFLAGS=-static -j4 (-j switch is optional but will make building faster, it's based on the number of cores you have +1 so 8 cores wold be -j9)

**Comment by MegAmi24** [comment]
Actually, wheres tinyxml2? It's a required dependency for the mod API.

**Comment by MegAmi24** [comment]
Ah ok

**Comment by Jackobo-Chocobo** [comment]
No problem. I will continue the tests of the game from 0 to see if I meet issues with the compiled file ^^ Thanks for the pull

**Comment by MegAmi24** [comment]
The autobuild gave out this error:
/usr/bin/ld: cannot find -lopengl32
/usr/bin/ld: cannot find -lws2_32

**Comment by Jackobo-Chocobo** [comment]
Okay I fixed that but i see that your autobuild for linux is not working. I will look on that after this new pull request .

**Comment by Jackobo-Chocobo** [comment]
Pull request available here https://github.com/Rubberduckycooly/Sonic-1-2-2013-Decompilation/pull/268

**Comment by MegAmi24** [comment]
No worries, thanks for the fix
