### ISSUE TITLE
"Knuckles & Tails" Glitch (but weirder)

### ISSUE THREAD

**Issue by michael-blur** [Rubberduckycooly/Sonic-1-2-2013-Decompilation#27]
Actually this glitch can be done in the original mobile port, but here it is much weirder.

I first chose Sonic and Tails, ran through several levels, deleted the save file. Then I decided to play for Knuckles, but the same Sonic and Tails appeared again. I played around a bit, went to the same save file again and I'm playing as Knuckles and Tails now. 

After I went back to the menu, Sonic and Tails were already displayed in the save select and you are already playing for them.

**Comment by MGRich** [comment]
If it can be done in the original, I'd say this is invalid, so I'm closing this for now. If people see this as more of an issue than I'll bring it back.
