### ISSUE TITLE
SDL Error

### ISSUE THREAD

**Issue by RiverNety** [Rubberduckycooly/Sonic-1-2-2013-Decompilation#274]
I managed to build the Decomp through Android Studio. After installing apk-debug.apk from the output folder I get [this message](https://imgur.com/a/girvPfB).

**Comment by MGRich** [comment]
This error (if I remember correctly? I haven't seen this in a very long while) happens by setting up the wrong SDL version. Ensure you're using 2.0.16 and report back.
