### ISSUE TITLE
S1: Lock-up on accessing Dev Menu from Pause Menu.

### ISSUE THREAD

**Issue by PokeTogeKiss** [Rubberduckycooly/Sonic-1-2-2013-Decompilation#28]
In Sonic 1, using this decompilation, accessing the Dev Menu through the Pause menu specifically will lock up the game, and require you to close the tab.

**Comment by Mtbcooler** [comment]
This also happens in Sonic 2

**Comment by MGRich** [comment]
Already fixed in master.
