### ISSUE TITLE
ScalingMode=1 results in Bilinear filtering instead of Integer Scaling

### ISSUE THREAD

**Issue by TheGershon** [Rubberduckycooly/Sonic-1-2-2013-Decompilation#284]
![asdf](https://user-images.githubusercontent.com/6880780/138640139-445c2865-6239-4e12-9bba-810f9c7eb6d8.png)

Using version 1.3.0, setting ScalingMode to 1 results in Bilinear filtering instead of Integer Scaling. What happened to Sharp Bilinear filtering that was included in older builds? Without it, pixel sizes are uneven at any res that isn't a clean integer scale with Nearest Neighbor scaling enabled.

**Comment by TorutheRedFox** [comment]
from what I can see the software renderer still has my code

I'm not very good at modern OpenGL though, so I dunno if I can get shader support implemented

**Comment by bthomas6758** [comment]
I had this issue with Sonic Forever, a fork of the decompilation. To fix this I disabled filtering and used a bat script and Qres to change my Windows resolution to 720p, an integer scale of 240p, and launch the game and then back to 1080p once I close the game. On my 1080p monitor this produces an effect similar to a sharp-bilinear filter. This only works in fullscreen.
`@echo off
QRes.exe /x:1280 /y:720
start SonicForever.exe
SETLOCAL EnableExtensions
set EXE=SonicForever.exe
:LOOPSTART
FOR /F %%x IN ('tasklist /NH /FI "IMAGENAME eq %EXE%"') DO IF %%x == %EXE% goto FOUND
goto FIN
:FOUND
TIMEOUT /T 1
goto LOOPSTART
:FIN
QRes.exe /x:1920 /y:1080`
You can download it here, place the launcher and Qres in the same folder as the exe and change SonicForever.exe to whichever exe you need.
[Launcher & Qres.zip](https://github.com/Rubberduckycooly/Sonic-1-2-2013-Decompilation/files/9467822/Launcher.Qres.zip)
