### ISSUE TITLE
Arch Linux dependencies

### ISSUE THREAD

**Issue by X4X5** [Rubberduckycooly/Sonic-1-2-2013-Decompilation#285]
On Manjaro Linux (basically just Arch Linux), not all of the dependencies installed. Namely, the two that didn't install for me were libglew and libasio. Help.

**Comment by MegAmi24** [comment]
This issue has been fixed, though I'd like to mention libtheora isn't a dependency for the v4 decomp, only for v3. Also, you forgot tinyxml2 in the command.

**Comment by CrisisModel** [comment]
> This issue has been fixed, though I'd like to mention libtheora isn't a dependency for the v4 decomp, only for v3. Also, you forgot tinyxml2 in the command.

Well, to be fair, I didn't "forget" tinyxml2 as a dependency as it wasn't listed as a dependency when I wrote this comment. :)
