### ISSUE TITLE
Crashing in the new 1.3.0 version

### ISSUE THREAD

**Issue by jkveri2812** [Rubberduckycooly/Sonic-1-2-2013-Decompilation#287]
When I open the "RSDKv4_64_rev01.exe" file or the "RSDKv4_64_rev02.exe" the screen freezes and then pop-ups the message "RSDKv4 has stopped working... Windows is checking for a solution to the problem.".
![6](https://user-images.githubusercontent.com/69863828/142924642-c1c86686-ad9b-40de-9760-59de0d32492f.PNG)
 

Even if I wait a few seconds just to see if something happens, the game still crashes. I don't have any mods, or scripts.
![7](https://user-images.githubusercontent.com/69863828/142924727-122af0bf-6ae0-44cd-b81e-d95a435b8edd.PNG) 

And I have, obviously, the Data.rsdk file. 
It's happening the same issue in the new version of the Sonic CD decompilation.

**Comment by MegAmi24** [comment]
Needs more information. "It crashes" is all I can gather from this.

**Comment by jkveri2812** [comment]
> Needs more information. "It crashes" is all I can gather from this.

Ok. But I don't know what else can I say. I just download the zip win_x64, because my Windows it's an 64 bit version; then, I extract it, I put the "Data.rsdk" file into the folder. Then, I open "RSDKv4_64_rev01.exe" file, it crashes. Then, I open the "RSDKv4_64_rev02.exe" file, it also crashes. What else do you need?

**Comment by MegAmi24** [comment]
Are you using an RSDK file from Sonic 1 or 2?

**Comment by MegAmi24** [comment]
Reread the original post. If you're trying to play Sonic CD, use the RSDKv3 Decompilation. https://github.com/Rubberduckycooly/Sonic-CD-11-Decompilation

**Comment by jkveri2812** [comment]
> Are you using an RSDK file from Sonic 1 or 2?

Obviously no. That's why I'm asking here ._.

**Comment by jkveri2812** [comment]
> Are you using an RSDK file from Sonic 1 or 2?

Obviously, yes, I'm using the RSDK file from the Sonic 1 and 2. That's why I'm asking here -_-

**Comment by jkveri2812** [comment]
> Reread the original post. If you're trying to play Sonic CD, use the RSDKv3 Decompilation. https://github.com/Rubberduckycooly/Sonic-CD-11-Decompilation

What? I was just saying that the same thing happened in the Sonic CD decompilation. Not that I was using the RSDK file from CD, or something like that.

**Comment by MegAmi24** [comment]
My apologies, I glanced over the original post.
Unfortunately, the most I can tell you at this point is to try reinstalling the decomp and re-extracting the RSDK files.

**Comment by jkveri2812** [comment]
> My apologies, I glanced over the original post. Unfortunately, the most I can tell you at this point is to try reinstalling the decomp and re-extracting the RSDK files.

Don't worry, it's ok.
I already tried reinstalling. In fact, actually, I have two separate folders. One with the older version of the decompilation (it works), and the other one have the last version (with the problem). I even extracted again the Data.rsdk from the original apk, and still don't work.
So, I have a theory; do you know if the Windows version influences the decompilation? I have Windows 7 (Yes, I still have Windows 7 in 2021).

**Comment by MegAmi24** [comment]
I tested the decomp using a Windows 7 machine and it worked fine, so I can rule that out.

**Comment by jkveri2812** [comment]
> I tested the decomp using a Windows 7 machine and it worked fine, so I can rule that out.

Ahh, ok. So, I don't know what else to do. I will wait until a new patch is released.
Anyway, thanks for the help.

**Comment by jkveri2812** [comment]
I found something! **(Sorry for the captures, I needed a way to express better what I found)**
Well, I was searching in the REMS for news about a patch (btw, it looks like there aren't going to be more updates, what a shame) and I found something that WORKS.
![1](https://user-images.githubusercontent.com/69863828/142737291-d5e3b067-f40f-47bf-be26-74c3afbb1802.PNG)
First, I found this on the channel "decomp-announcements" I downloaded first the RSDKv4 one. I had no hope this was going to work, because these files are beta versions. But, look:
![2](https://user-images.githubusercontent.com/69863828/142737376-638d94cc-2d72-4b08-848a-336b5b4c4bd2.PNG)
Works with Sonic 1.
![3](https://user-images.githubusercontent.com/69863828/142737384-db44bb22-f985-480f-bf74-6e6cf4ee5fad.PNG)
And with Sonic 2.
Then, I found an update, it was just for fixing something of the servers, or something like that, but, hey, at least I can test if the crashing issues starts in this update. So, I downloaded it, and still working. I don't give you a capture, because is basically the same.
![4](https://user-images.githubusercontent.com/69863828/142737505-0a2037c4-43a9-4ed5-9b30-f8d08ad99808.PNG)


Then, I tried with the RSDKv3 one, but, sadly, it's still having the problem. 
![5](https://user-images.githubusercontent.com/69863828/142737526-7fd238fe-ba7b-4165-9cfb-8a78604e35c5.PNG)

_**I know, I know. It's not THAT amazing, but at least, it's progress in the searching for a solution.**_

**Comment by jkveri2812** [comment]
> I tested the decomp using a Windows 7 machine and it worked fine, so I can rule that out.

### I have more progress about this issue:
1. Tested my Data.rsdk file in another computer, it works. So I can rule out that my Data.rsdk is corrupted or something like that. It looks like the issue is more related to my PC.
2. I used the Computer Management from my Windows 7, I went to Event Viewer/Windows Logs/Application; and found this:
### To clear, I caused a recent crash in the decompilation, so that explains why the dates are so recent.
![image](https://user-images.githubusercontent.com/69863828/144720403-e997e698-314f-4a0b-8d22-4bfafca75bc1.png)

Then, I checked first one of the level 'Error' by just clicking on it:
![image](https://user-images.githubusercontent.com/69863828/144720464-853b7ff7-de22-46ed-8ccf-62d0774e016c.png)
I made double-click to see more information and here it is:
### **I don't know if this information could some kind of useful, but whatever**
`Faulting application name: RSDKv4_64_rev01.exe, version: 1.0.0.0, time stamp: 0x61723781
Faulting module name: unknown, version: 0.0.0.0, time stamp: 0x00000000
Exception code: 0xc0000005
Fault offset: 0x0000000000000000
Faulting process id: 0xea0
Faulting application start time: 0x01d7e93ba324ed99
Faulting application path: C:\Users\o2jkveri2812\Downloads\win_x64\RSDKv4_64_rev01.exe
Faulting module path: unknown
Report Id: e24345fc-552e-11ec-8f43-0027134c6528`

Next, I went to one of the level 'Information'
![image](https://user-images.githubusercontent.com/69863828/144720659-1f6462c7-dad6-4d5d-a480-e811ed149f33.png)
I made double-click to also see more information and here it is:
`Log Name:      Application
Source:        Windows Error Reporting
Date:          04/12/2021 01:20:44 p.m.
Event ID:      1001
Task Category: None
Level:         Information
Keywords:      Classic
User:          N/A
Computer:      o2jkveri2812-PC
Description:
Fault bucket , type 0
Event Name: BEX64
Response: Not available
Cab Id: 0
Problem signature:
P1: RSDKv4_64_rev01.exe
P2: 1.0.0.0
P3: 61723781
P4: StackHash_1dc2
P5: 0.0.0.0
P6: 00000000
P7: 0000000000000000
P8: c0000005
P9: 0000000000000008
P10: 
Attached files:
These files may be available here:
C:\Users\o2jkveri2812\AppData\Local\Microsoft\Windows\WER\ReportQueue\AppCrash_RSDKv4_64_rev01._ad91c1622196dc556557cb179c2b9757edfd8f_1f98fcb5
Analysis symbol: 
Rechecking for solution: 0
Report Id: e24345fc-552e-11ec-8f43-0027134c6528
Report Status: 4`
### **The other levels 'Error' and 'Information' give me the same information, but this time with the "RSDKv4_64_rev02.exe"**

The direction 'C:\Users\o2jkveri2812\AppData\Local\Microsoft\Windows\WER\ReportQueue\AppCrash_RSDKv4_64_rev01._ad91c1622196dc556557cb179c2b9757edfd8f_1f98fcb5' leads me to an .wer file. I can read it with a Notepad, but It says almost the same as the information I found in the Computer Management. But, If you want, I can provide them to you.

3) I don't know if I can provide you my crash dump files
![image](https://user-images.githubusercontent.com/69863828/144720980-b3e53b87-0d20-4efe-bb3b-b4beec4aaa4d.png)
(Deleted a lot of them, but still having some)
I can't find a way to read them, and I don't know if this could be useful for you.
