### ISSUE TITLE
S2: Invisible rising lava in HTZ2

### ISSUE THREAD

**Issue by PokeTogeKiss** [Rubberduckycooly/Sonic-1-2-2013-Decompilation#29]
In Hill Top Zone Act 2, in Sonic 2, enter the vertical cave with the rising lava. The shaking effects do start, and the lava does collide with & damage the player character, but said lava is invisible. I do not know what causes this issue - a similar area in Act 1 has visible lava.

**Comment by Rubberduckycooly** [comment]
this bug has been fixed, the fix will be in the next build
