### ISSUE TITLE
stb error when compiling under Linux.

### ISSUE THREAD

**Issue by MavisCelus19201** [Rubberduckycooly/Sonic-1-2-2013-Decompilation#295]
Here's what I get, running with just Make also does the same outcome

make CXXFLAGS="-O2 -Idependencies/all/tinyxml2/" LIBS=-lstdc++fs -j2

Package stb was not found in the pkg-config search path.
Perhaps you should add the directory containing `stb.pc'
to the PKG_CONFIG_PATH environment variable
Package 'stb', required by 'virtual:world', not found
mkdir -p objects/RSDKv4
Package stb was not found in the pkg-config search path.
Perhaps you should add the directory containing `stb.pc'
to the PKG_CONFIG_PATH environment variable
Package 'stb', required by 'virtual:world', not found
g++  -O2 -Idependencies/all/tinyxml2/ -DBASE_PATH='""' -IRSDKv4/ -IRSDKv4/NativeObjects/ -Idependencies/all/asio/include/ -Idependencies/all/stb-image/ -Idependencies/all/tinyxml2/ -std=c++17 RSDKv4/Animation.cpp -o objects/RSDKv4/Animation.cpp.o -c
mkdir -p objects/RSDKv4
Package stb was not found in the pkg-config search path.
Perhaps you should add the directory containing `stb.pc'
to the PKG_CONFIG_PATH environment variable
Package 'stb', required by 'virtual:world', not found
g++  -O2 -Idependencies/all/tinyxml2/ -DBASE_PATH='""' -IRSDKv4/ -IRSDKv4/NativeObjects/ -Idependencies/all/asio/include/ -Idependencies/all/stb-image/ -Idependencies/all/tinyxml2/ -std=c++17 RSDKv4/Audio.cpp -o objects/RSDKv4/Audio.cpp.o -c
In file included from RSDKv4/Animation.cpp:1:
RSDKv4/RetroEngine.hpp:230:10: fatal error: SDL.h: No such file or directory
  230 | #include <SDL.h>
      |          ^~~~~~~
In file included from RSDKv4/Audio.cpp:1:
RSDKv4/RetroEngine.hpp:230:10: fatal error: SDL.h: No such file or directory
  230 | #include <SDL.h>
      |          ^~~~~~~
compilation terminated.
compilation terminated.
make: *** [Makefile:83: objects/RSDKv4/Animation.cpp.o] Error 1
make: *** Waiting for unfinished jobs....
make: *** [Makefile:83: objects/RSDKv4/Audio.cpp.o] Error 1

I followed the instructions and cloned the dependencies, and made sure they were installed for things like tinyxml2, and it still throws this error up. I got Sonic CDs working using the command at the very top but not 1-2.

**Comment by MegAmi24** [comment]
This was an issue related to stb not working properly when installed through pkg-config, it should be fixed now.
