### ISSUE TITLE
Game crashing when i enter a level

### ISSUE THREAD

**Issue by Imperialnysus** [Rubberduckycooly/Sonic-1-2-2013-Decompilation#296]
There is a black screen when i enter a act from the normal menu and the dev menu, it happens in both Sonic 1 and 2

**Comment by MegAmi24** [comment]
Do you have mods enabled?

**Comment by Imperialnysus** [comment]
No, i didn't

**Comment by Imperialnysus** [comment]
Also, i just got it fixed some minutes ago by using RSDKv4_64_rev02.
