### ISSUE TITLE
Game crashes when opening it

### ISSUE THREAD

**Issue by ZtrukRuhtra** [Rubberduckycooly/Sonic-1-2-2013-Decompilation#298]
When i open sonic 2, it crashes without even showing anything.
Here's a video that shows what happens:
[Video](https://pipe.miroware.io/5d963f65b72a043564fd82b7/2021-12-05%2022-49-56.mp4)

**Comment by MegAmi24** [comment]
did you try using the rev02 exe?

**Comment by jkveri2812** [comment]
Try using rev02. If still don't work; welcome to the club.
