### ISSUE TITLE
Hangs when selecting Dev Menu on pause screen

### ISSUE THREAD

**Issue by soniccd123** [Rubberduckycooly/Sonic-1-2-2013-Decompilation#3]
First, amazing job! The best way to play Sonic 2 on the PC for sure!

Not something game breaking, but the game hangs when selecting the dev Menu option on the pause menu. The Dev Menu opens but the program just hangs. I don't know if the controller (keyboard in my case) does not work on the menu or if the program really crashed. Was using the release version and Win 10;

**Comment by Rubberduckycooly** [comment]
this issue has been fixed and will be in the next build
