### ISSUE TITLE
(Sonic 2): Super Knuckles speed and jump persisting after opening animal capsule

### ISSUE THREAD

**Issue by Radicalicious** [Rubberduckycooly/Sonic-1-2-2013-Decompilation#30]
I was only able to pull this off twice, once in CPZ2 and once in CNZ2, but after popping the capsule after the boss while Super, Knuckles reverted to normal while still having the same speed and jump as Super Knuckles. I think this might have to do with gliding/falling onto the capsule, as I was not able to pull it off in HTZ2 when I jumped on the capsule normally. I don't know if this affects other characters as well.

**Comment by MGRich** [comment]
This should be in the original.
