### ISSUE TITLE
The window is not visible

### ISSUE THREAD

**Issue by pauloplaygames71** [Rubberduckycooly/Sonic-1-2-2013-Decompilation#302]
From some reason, in some point went i go play sonic 2, he dont open, and sonic 1 have the same effect

**Comment by MegAmi24** [comment]
Can you show a screenshot of your decomp folder?

**Comment by pauloplaygames71** [comment]
[image: AA.png]
I open the game but the window is not visible
MegAmi ***@***.***> escreveu no dia sexta, 24/12/2021 à(s)
18:45:

**Comment by MegAmi24** [comment]
I don't think the image embed worked.

**Comment by pauloplaygames71** [comment]
OH, THE GAME WINDOW OPEN AFTER 30 MINUTES

MegAmi ***@***.***> escreveu no dia sexta, 24/12/2021 à(s)
19:47:

**Comment by pauloplaygames71** [comment]
I WAS PLAYING ANGRY BIRDS 2, AND THE WINDOW BECOME VISBLE

paulo o animator ***@***.***> escreveu no dia sexta, 24/12/2021
à(s) 20:01:
