### ISSUE TITLE
Build error on Fedora

### ISSUE THREAD

**Issue by X4X5** [Rubberduckycooly/Sonic-1-2-2013-Decompilation#303]
I got this output when running `make -j5`

/usr/bin/ld: cannot find -lglib-2.0
/usr/bin/ld: cannot find -lgobject-2.0
/usr/bin/ld: cannot find -lgio-2.0
/usr/bin/ld: cannot find -libus-1.0
/usr/bin/ld: cannot find -ldbus-1

Can't find the files that `make` is looking for

**Comment by MGRich** [comment]
Run `yum install glib2-devel` and report back.

**Comment by X4X5** [comment]
Finally revisiting this *2 months later* because I was busy with stuff, and I gotta reinstall all the dependencies again. Can't find that list anywhere

**Comment by MegAmi24** [comment]
Read the readme

**Comment by X4X5** [comment]
Does the readme still have Fedora dependencies and I missed them? I wound up finding them in the Sonic CD decomp, but not for this decomp

**Comment by MegAmi24** [comment]
It's pretty much the same list except you can get rid of libtheora

**Comment by X4X5** [comment]
Ah. I guess, having run that list and the command I was told to above, I'm left with the two other dependencies:

/usr/bin/ld: cannot find -libus-1.0
/usr/bin/ld: cannot find -ldbus-1

**Comment by MegAmi24** [comment]
Install those dependencies and try again.

**Comment by X4X5** [comment]
Here is where I'm gonna draw a blank, as I'll admit that I have no idea what these dependencies refer to in terms of packages

**Comment by X4X5** [comment]
Okay, after having searched Fedora's repositories, the packages don't actually exist. Does that just make decomp impossible to build on said distro?

**Comment by MegAmi24** [comment]
You can remove the "--static" in lines 1 and 10 of the Makefile, but that's more of a workaround than a proper fix.

**Comment by X4X5** [comment]
Compiled and seems to work just fine, for now

**Comment by MegAmi24** [comment]
This never got closed, whoops
