### ISSUE TITLE
Build error with flatpak: "fatal error: GL/glew.h: No such file or directory"

### ISSUE THREAD

**Issue by doliveira4** [Rubberduckycooly/Sonic-1-2-2013-Decompilation#304]
Hi there,

- How to enable flatpak-builder to find GLEW?

Many thanks & happy New Year!

**Comment by MegAmi24** [comment]
Why did you open two issues? You could've just put both of your problems into one.

**Comment by doliveira4** [comment]
The issues are different:

1. this is for Flatpak (can't find GLEW);

2. The other is for Ubuntu 18.04 (can't find assets file)

**Comment by MegAmi24** [comment]
Did you follow the instructions in flatpak/README.md in the repository?

**Comment by doliveira4** [comment]
I did.
(installed FreeDesktop.org 20.08 SDK  
and
renamed + placed assets file.)

After all this, running 
"sudo flatpak-builder --install --force-clean sonic1 com.sega.Sonic1.json" 
yelds:
«
(...)
Package 'glew', required by 'virtual:world', not found
In file included from RSDKv4/Animation.cpp:1:
RSDKv4/RetroEngine.hpp:173:10: fatal error: GL/glew.h: No such file or directory
  173 | #include <GL/glew.h>
(...)
»

- Any ideas?

**Comment by MegAmi24** [comment]
I just checked, the flatpak installation is broken. I'll see what I can do to fix it.

**Comment by MegAmi24** [comment]
I merged a pull request that should fix flatpak, try again

**Comment by doliveira4** [comment]
That did it - thanks a lot!
