### ISSUE TITLE
Build error: "fatal error: filesystem: No such file or directory"

### ISSUE THREAD

**Issue by doliveira4** [Rubberduckycooly/Sonic-1-2-2013-Decompilation#305]
Hi there,
Getting the build error:

_RSDKv4/ModAPI.cpp:23:10: fatal error: filesystem: No such file or directory
 #include <filesystem>
          ^~~~~~~~~~~~_

where exactly to put the assets file "Data.rsdk"?

Many thanks & happy New Year!

**Comment by MegAmi24** [comment]
You put the Data.rsdk file in the same location as the decomp exe after it's built.

**Comment by doliveira4** [comment]
Ok - but how to fix the 
Build error: "fatal error: filesystem: No such file or directory"?

on Ubuntu 18.04 - thanks again.

**Comment by doliveira4** [comment]
Progress:

on **Ubuntu 18.04**, install g++-8 with:
`sudo apt install g++-8`

now make with:
`make CXX=g++-8 LIBS=lstdc++fs`


However, this results in a new error further ahead in the build process.
Opening a new issue about it.

**Comment by MegAmi24** [comment]
Can you please just stop making new issues? It's hard to keep track of everything that way.

**Comment by doliveira4** [comment]
Now the build goes much further but it errors on:

`mkdir -p objects/RSDKv4
g++-8 -D_REENTRANT -I/usr/include/SDL2 -I/usr/include/libdrm  -DBASE_PATH='""' -IRSDKv4/ -IRSDKv4/NativeObjects/ -Idependencies/all/asio/include/ -Idependencies/all/stb-image/ -std=c++17 RSDKv4/Networking.cpp -o objects/RSDKv4/Networking.cpp.o -c
RSDKv4/Networking.cpp:32:36: error: expected ‘)’ before ‘&’ token
     NetworkSession(asio::io_context &io_context, const tcp::resolver::results_type &endpoints) : io_context_(io_context), socket_(io_context)
                   ~                ^~
                                    )
RSDKv4/Networking.cpp:70:42: error: ‘results_type’ in ‘asio::ip::tcp::resolver’ {aka ‘class asio::ip::basic_resolver<asio::ip::tcp>’} does not name a type
     void do_connect(const tcp::resolver::results_type &endpoints)
                                          ^~~~~~~~~~~~
RSDKv4/Networking.cpp:160:11: error: ‘io_context’ in namespace ‘asio’ does not name a type
     asio::io_context &io_context_;
           ^~~~~~~~~~
RSDKv4/Networking.cpp:160:5: note: suggested alternative: ‘connect’
     asio::io_context &io_context_;
     ^~~~
     connect
RSDKv4/Networking.cpp: In member function ‘void NetworkSession::close()’:
RSDKv4/Networking.cpp:54:19: error: ‘post’ is not a member of ‘asio’
             asio::post(io_context_, [this]() { socket_.close(); });
                   ^~~~
RSDKv4/Networking.cpp:54:19: note: suggested alternative: ‘posix’
             asio::post(io_context_, [this]() { socket_.close(); });
                   ^~~~
                   posix
RSDKv4/Networking.cpp:54:24: error: ‘io_context_’ was not declared in this scope
             asio::post(io_context_, [this]() { socket_.close(); });
                        ^~~~~~~~~~~
RSDKv4/Networking.cpp:54:24: note: suggested alternative: ‘cl_context’
             asio::post(io_context_, [this]() { socket_.close(); });
                        ^~~~~~~~~~~
                        cl_context
RSDKv4/Networking.cpp: At global scope:
RSDKv4/Networking.cpp:171:7: error: ‘io_context’ in namespace ‘asio’ does not name a type
 asio::io_context io_context;
       ^~~~~~~~~~
RSDKv4/Networking.cpp:171:1: note: suggested alternative: ‘connect’
 asio::io_context io_context;
 ^~~~
 connect
RSDKv4/Networking.cpp: In function ‘void initNetwork()’:
RSDKv4/Networking.cpp:177:32: error: ‘io_context’ was not declared in this scope
         tcp::resolver resolver(io_context);
                                ^~~~~~~~~~
RSDKv4/Networking.cpp:177:32: note: suggested alternative: ‘cl_context’
         tcp::resolver resolver(io_context);
                                ^~~~~~~~~~
                                cl_context
RSDKv4/Networking.cpp:179:87: error: no matching function for call to ‘asio::ip::basic_resolver<asio::ip::tcp>::resolve(char [64], std::__cxx11::string, asio::error_code&)’
         auto endpoints = resolver.resolve(networkHost, std::to_string(networkPort), ec);
                                                                                       ^
In file included from /usr/include/asio.hpp:62,
                 from RSDKv4/Networking.cpp:12:
/usr/include/asio/ip/basic_resolver.hpp:98:12: note: candidate: ‘asio::ip::basic_resolver<InternetProtocol, ResolverService>::iterator asio::ip::basic_resolver<InternetProtocol, ResolverService>::resolve(const query&) [with InternetProtocol = asio::ip::tcp; ResolverService = asio::ip::resolver_service<asio::ip::tcp>; asio::ip::basic_resolver<InternetProtocol, ResolverService>::iterator = asio::ip::basic_resolver_iterator<asio::ip::tcp>; asio::ip::basic_resolver<InternetProtocol, ResolverService>::query = asio::ip::basic_resolver_query<asio::ip::tcp>]’
   iterator resolve(const query& q)
            ^~~~~~~
/usr/include/asio/ip/basic_resolver.hpp:98:12: note:   candidate expects 1 argument, 3 provided
/usr/include/asio/ip/basic_resolver.hpp:123:12: note: candidate: ‘asio::ip::basic_resolver<InternetProtocol, ResolverService>::iterator asio::ip::basic_resolver<InternetProtocol, ResolverService>::resolve(const query&, asio::error_code&) [with InternetProtocol = asio::ip::tcp; ResolverService = asio::ip::resolver_service<asio::ip::tcp>; asio::ip::basic_resolver<InternetProtocol, ResolverService>::iterator = asio::ip::basic_resolver_iterator<asio::ip::tcp>; asio::ip::basic_resolver<InternetProtocol, ResolverService>::query = asio::ip::basic_resolver_query<asio::ip::tcp>; asio::error_code = std::error_code]’
   iterator resolve(const query& q, asio::error_code& ec)
            ^~~~~~~
/usr/include/asio/ip/basic_resolver.hpp:123:12: note:   candidate expects 2 arguments, 3 provided
/usr/include/asio/ip/basic_resolver.hpp:187:12: note: candidate: ‘asio::ip::basic_resolver<InternetProtocol, ResolverService>::iterator asio::ip::basic_resolver<InternetProtocol, ResolverService>::resolve(const endpoint_type&) [with InternetProtocol = asio::ip::tcp; ResolverService = asio::ip::resolver_service<asio::ip::tcp>; asio::ip::basic_resolver<InternetProtocol, ResolverService>::iterator = asio::ip::basic_resolver_iterator<asio::ip::tcp>; asio::ip::basic_resolver<InternetProtocol, ResolverService>::endpoint_type = asio::ip::basic_endpoint<asio::ip::tcp>]’
   iterator resolve(const endpoint_type& e)
            ^~~~~~~
/usr/include/asio/ip/basic_resolver.hpp:187:12: note:   candidate expects 1 argument, 3 provided
/usr/include/asio/ip/basic_resolver.hpp:214:12: note: candidate: ‘asio::ip::basic_resolver<InternetProtocol, ResolverService>::iterator asio::ip::basic_resolver<InternetProtocol, ResolverService>::resolve(const endpoint_type&, asio::error_code&) [with InternetProtocol = asio::ip::tcp; ResolverService = asio::ip::resolver_service<asio::ip::tcp>; asio::ip::basic_resolver<InternetProtocol, ResolverService>::iterator = asio::ip::basic_resolver_iterator<asio::ip::tcp>; asio::ip::basic_resolver<InternetProtocol, ResolverService>::endpoint_type = asio::ip::basic_endpoint<asio::ip::tcp>; asio::error_code = std::error_code]’
   iterator resolve(const endpoint_type& e, asio::error_code& ec)
            ^~~~~~~
/usr/include/asio/ip/basic_resolver.hpp:214:12: note:   candidate expects 2 arguments, 3 provided
RSDKv4/Networking.cpp: In function ‘void networkLoop()’:
RSDKv4/Networking.cpp:202:9: error: ‘io_context’ was not declared in this scope
         io_context.stop();
         ^~~~~~~~~~
RSDKv4/Networking.cpp:202:9: note: suggested alternative: ‘cl_context’
         io_context.stop();
         ^~~~~~~~~~
         cl_context
RSDKv4/Networking.cpp: In function ‘void disconnectNetwork(bool)’:
RSDKv4/Networking.cpp:236:14: error: ‘io_context’ was not declared in this scope
         if (!io_context.stopped())
              ^~~~~~~~~~
RSDKv4/Networking.cpp:236:14: note: suggested alternative: ‘cl_context’
         if (!io_context.stopped())
              ^~~~~~~~~~
              cl_context
In file included from /usr/include/asio/impl/io_service.hpp:18,
                 from /usr/include/asio/io_service.hpp:765,
                 from /usr/include/asio/basic_io_object.hpp:19,
                 from /usr/include/asio/basic_socket.hpp:20,
                 from /usr/include/asio/basic_datagram_socket.hpp:20,
                 from /usr/include/asio.hpp:19,
                 from RSDKv4/Networking.cpp:12:
/usr/include/asio/impl/connect.hpp: In instantiation of ‘typename asio::async_result<typename asio::handler_type<ComposedConnectHandler, void(std::error_code, Iterator)>::type>::type asio::async_connect(asio::basic_socket<Protocol, DatagramSocketService>&, Iterator, ComposedConnectHandler&&) [with Protocol = asio::ip::tcp; SocketService = asio::stream_socket_service<asio::ip::tcp>; Iterator = int; ComposedConnectHandler = NetworkSession::do_connect(const int&)::<lambda(std::error_code, asio::ip::tcp::endpoint)>; typename asio::async_result<typename asio::handler_type<ComposedConnectHandler, void(std::error_code, Iterator)>::type>::type = void]’:
RSDKv4/Networking.cpp:80:10:   required from here
/usr/include/asio/impl/connect.hpp:332:3: error: static assertion failed: ComposedConnectHandler type requirements not met
   ASIO_COMPOSED_CONNECT_HANDLER_CHECK(
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/asio/impl/connect.hpp:332:3: error: no match for call to ‘(NetworkSession::do_connect(const int&)::<lambda(std::error_code, asio::ip::tcp::endpoint)>) (const std::error_code&, const int&)’
   ASIO_COMPOSED_CONNECT_HANDLER_CHECK(
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
RSDKv4/Networking.cpp:72:89: note: candidate: ‘NetworkSession::do_connect(const int&)::<lambda(std::error_code, asio::ip::tcp::endpoint)>’
         asio::async_connect(socket_, endpoints, [this](std::error_code ec, tcp::endpoint) {
                                                                                         ^
RSDKv4/Networking.cpp:72:89: note:   no known conversion for argument 2 from ‘const int’ to ‘asio::ip::tcp::endpoint’ {aka ‘asio::ip::basic_endpoint<asio::ip::tcp>’}
In file included from /usr/include/asio.hpp:18,
                 from RSDKv4/Networking.cpp:12:
/usr/include/asio/async_result.hpp: At global scope:
/usr/include/asio/async_result.hpp:59:12: error: ‘asio::detail::async_result_init<Handler, Signature>::async_result_init(Handler&&) [with Handler = NetworkSession::do_connect(const int&)::<lambda(std::error_code, asio::ip::tcp::endpoint)>; Signature = void(std::error_code, int)]’, declared using local type ‘NetworkSession::do_connect(const int&)::<lambda(std::error_code, asio::ip::tcp::endpoint)>’, is used but never defined [-fpermissive]
   explicit async_result_init(ASIO_MOVE_ARG(Handler) orig_handler)
            ^~~~~~~~~~~~~~~~~
In file included from /usr/include/asio/connect.hpp:821,
                 from /usr/include/asio.hpp:41,
                 from RSDKv4/Networking.cpp:12:
/usr/include/asio/impl/connect.hpp:181:5: error: ‘asio::detail::connect_op<Protocol, SocketService, Iterator, ConnectCondition, ComposedConnectHandler>::connect_op(asio::basic_socket<Protocol, DatagramSocketService>&, const Iterator&, const Iterator&, const ConnectCondition&, ComposedConnectHandler&) [with Protocol = asio::ip::tcp; SocketService = asio::stream_socket_service<asio::ip::tcp>; Iterator = int; ConnectCondition = asio::detail::default_connect_condition; ComposedConnectHandler = NetworkSession::do_connect(const int&)::<lambda(std::error_code, asio::ip::tcp::endpoint)>]’, declared using local type ‘NetworkSession::do_connect(const int&)::<lambda(std::error_code, asio::ip::tcp::endpoint)>’, is used but never defined [-fpermissive]
     connect_op(basic_socket<Protocol, SocketService>& sock,
     ^~~~~~~~~~
`

Any ideas?
[ gcc version 8.4.0 (Ubuntu 8.4.0-1ubuntu1~18.04) ]

**Comment by doliveira4** [comment]
Just for sanity check,
how to build without networking?

**Comment by MegAmi24** [comment]
set RETRO_USE_NETWORKING to 0 in RetroEngine.hpp (line 12)

**Comment by doliveira4** [comment]
Did so - seems Ubuntu 18.04 has an incompatible older version of Boost.

Btw, is Ubuntu 18.04 supported?

**Comment by doliveira4** [comment]
I think we'll just keep finding further out-of-date packages in Ubuntu 18.04.

Hoping for that Flatpak build to get sorted  🙏:
#304
