### ISSUE TITLE
Sonic 1 crash

### ISSUE THREAD

**Issue by epicsause21** [Rubberduckycooly/Sonic-1-2-2013-Decompilation#306]
Sonic 1 crashes upon loading a stage (at least green hill zone) sonic 2 ran fine

**Comment by MegAmi24** [comment]
Are you using rev01 or rev02?

**Comment by TazerTaz123** [comment]
I have the same issue. I use rev01 and I've tried 5 different APK sites. It just doesn't work. I'll load the game fine but as soon as I try to load into a zone, my screen goes black, and sonic 1 crashes. I've sat at the not responding screen for minutes on end but no luck. This might be a simple fix for the dev to make, but I'm not sure. I really hope they fix it. (sorry if my tone is rude, I promise it's not).

**Comment by MegAmi24** [comment]
We won't provide support to anyone who didn't obtain their apk files through official sources.
