### ISSUE TITLE
Game crashes when I enter a stage.

### ISSUE THREAD

**Issue by TazerTaz123** [Rubberduckycooly/Sonic-1-2-2013-Decompilation#307]
When I play sonic 2 everything is fine it works perfectly but when I switch the Data.rsdk to sonic 1's and open rev01 it works fine. Well, that is until I boot up an empty save it just goes to black. Unplugging my main, higher-res monitor to show it on my laptop reveals the Genisis Sonic 1 title screen on a freeze-frame. If I click it a window pops up showing it's unresponsive. I've tried everything, I ran it in compatibility mode which made it worse because I would have to restart my pc to close the window. I also made a new folder just for Sonic 1 but that had no effect. (I'm using an android APK with the no ads thing bought).

**Comment by MegAmi24** [comment]
Use the rev02 exe
