### ISSUE TITLE
Sonic 1 Green lines onscreen visual glitch?

### ISSUE THREAD

**Issue by JonSpeedArts** [Rubberduckycooly/Sonic-1-2-2013-Decompilation#309]
I built the game like normal, even played with all the settings to try and fix this, but I'm still getting this visual glitch, any help?
(I also reinstalled intel graphics drivers to the latest version, didn't work either)
![image](https://user-images.githubusercontent.com/78990823/149836779-38a6cbe5-d00d-4332-aef8-40d58ba464cb.png)
![image](https://user-images.githubusercontent.com/78990823/149836830-66419e83-51d5-49ab-bad7-a6e595f7ed27.png)

**Comment by MegAmi24** [comment]
We don't know the exact cause, but it's something to do with Intel integrated graphics drivers. Would you mind running [this tool](https://www.realtech-vr.com/home/glview) and showing a screenshot of the summary page?

**Comment by JonSpeedArts** [comment]
> We don't know the exact cause, but it's something to do with Intel integrated graphics drivers. Would you mind running [this tool](https://www.realtech-vr.com/home/glview) and showing a screenshot of the summary page?

here it is!
![image](https://user-images.githubusercontent.com/78990823/149845005-33e41c3e-eb57-423e-8107-8920536101c8.png)

**Comment by MGRich** [comment]
Some have reported this as fixed by updating their Intel drivers. If I remember correctly, this is a driver-version-specific bug that happens on and off.
