### ISSUE TITLE
S1 and S2: Documentation Update - Transferring saves from mobile version

### ISSUE THREAD

**Issue by peter4432** [Rubberduckycooly/Sonic-1-2-2013-Decompilation#31]
As these ports are decomplication of the mobile release, I wonder if it would be possible to transfer my progress from the mobile version to these ports.

I had a back-up of a save from both games:
> ...\Android\data\com.sega.sonic1\SGame.bin
> ...\Android\data\com.sega.sonic2\SGame.bin

and I saw that the exe was saving its own save as **SData.bin**, so I simply copied the save backup to the folder and rename it **SData.bin** (old was kept as **SData.bin.bak** in case of issues).

As far I can see this work perfectly and all the progress I had on each mobile game is now available on the PC.

It would therefore be worth updating the readme file and/or front-end page to make others aware of this feature.

**Comment by MGRich** [comment]
I wasn't able to get it from my version of which was (com.sega.sonic1px and com.sega.sonic2.runner), so I'm assuming this is pre-forever.
