### ISSUE TITLE
egg gauntlet in sonic 2 doesn't work

### ISSUE THREAD

**Issue by minuteworld1** [Rubberduckycooly/Sonic-1-2-2013-Decompilation#310]
it's just a black screen. also, tails and knuckles are blacked out. also, on the continue screen, you press start and it brings up the menu as well and continue. might wanna make it so pressing a face button on that screen will continue.

**Comment by MegAmi24** [comment]
- Not all Data.rsdk files for Sonic 2 have Egg Gauntlet's files in them. You're probably using a Data.rsdk file that doesn't have them.
- If you're using a save file from previous versions of the decompilation, you'll have to edit your save file to unlock Tails and Knuckles.
- The start button bringing up the pause menu in the continue screen is a script bug, there's not much we can do about it.

**Comment by MegAmi24** [comment]
I pushed a commit for what should fix Tails and Knuckles not unlocking in S2, what I said about the other two points still applies though.
