### ISSUE TITLE
[Arch Linux] No settings.ini or other files in bin

### ISSUE THREAD

**Issue by TechnoDTF** [Rubberduckycooly/Sonic-1-2-2013-Decompilation#312]
Game plays just fine but after the build, the only file in the bin folder is the executable, this makes me unable to load mods or configure the game.

**Comment by X4X5** [comment]
If you can find where your save file is, that's where the other files are, which are normally in `home/[username]/.local/share/RSDKv4. I'm curious about this as well, because I was under the impression that all of the said files would be in the bin folder, rather than the save directory

**Comment by MegAmi24** [comment]
The game saves all of its data in one single folder, however that folder varies depending on several factors, such as your settings and platform.

**Comment by TechnoDTF** [comment]
They were there. Thanks!

> If you can find where your save file is, that's where the other files are, which are normally in `home/[username]/.local/share/RSDKv4. I'm curious about this as well, because I was under the impression that all of the said files would be in the bin folder, rather than the save directory
