### ISSUE TITLE
Color palette issues on macOS

### ISSUE THREAD

**Issue by slashvalkyrie** [Rubberduckycooly/Sonic-1-2-2013-Decompilation#313]
On the macOS build of the game, blues seem to be darker. In levels like Emerald Hill or Aquatic Ruin this makes the level look like it's happening at night. In Chemical Plant, the blues are noticeably darker as well. These aren't the only places that this occurs, but they are the most noticeable.

Screenshots:
![image](https://user-images.githubusercontent.com/63067831/155804870-fd3f3523-a423-43be-a958-463874fc0622.png)
![image](https://user-images.githubusercontent.com/63067831/155806504-3c6a5df9-001e-4737-87fd-63d4edb9c640.png)
![image](https://user-images.githubusercontent.com/63067831/155807905-5cdf3a0b-6cc4-418d-a6d2-5d62593e09a1.png)

**Comment by MegAmi24** [comment]
You seem to be using a mod in these screenshots. Please make sure the issue happens without any mods before reporting it.

**Comment by slashvalkyrie** [comment]
I can confirm it happens without any mods installed or enabled. I am indeed using Sappharad’s build, so I’ll try building it myself and report back.

**Comment by MegAmi24** [comment]
I'm gonna need more screenshots with no mods then. Comparing the screenshots you gave with ones from me shows your game is actually brighter.
![image](https://user-images.githubusercontent.com/7158344/155822919-eb66b785-9e48-4344-825d-f5c357c7f062.png)

**Comment by slashvalkyrie** [comment]
Wait, it seems like I've made a mistake. I could have sworn that the skies were supposed to be brighter, but a quick Google and playing the game on my table is telling me otherwise. Sorry!

**Comment by MegAmi24** [comment]
The RSDK version uses the raw color palette ripped directly from the game. The brighter sky you're thinking of is likely from the Genesis version of the game, as the hardware brightens the palette when rendered on console or in an emulator.

**Comment by slashvalkyrie** [comment]
How could I go about editing the palettes to fix it, then?

**Comment by MegAmi24** [comment]
[Install this mod.](https://gamebanana.com/mods/289700)

**Comment by slashvalkyrie** [comment]
No longer works

**Comment by MegAmi24** [comment]
What no longer works?

**Comment by slashvalkyrie** [comment]
The mod you linked. As noted by the most recent comment on the Gamebanana page, an error occurs when applying it and trying to start the game. I can confirm it happens to me as well.
