### ISSUE TITLE
Act doesn't finish on mobile on sonic 2

### ISSUE THREAD

**Issue by Mizzix8156** [Rubberduckycooly/Sonic-1-2-2013-Decompilation#314]
In specifically sonic 2 whenever i clear an act the act clear pop up never appears, and the game soft locks there with sonic walking forever. For some reason sonic 1 works just fine so im not sure what the issue is.

**Comment by MegAmi24** [comment]
Script bug, not the fault of the decomp

**Comment by MegAmi24** [comment]
To be a bit more specific, this is happening because your phone's screen is too wide. Newer autobuilds should fix this issue.

**Comment by Mizzix8156** [comment]
Okay, thank you.
