### ISSUE TITLE
(UWP) 26 warnings and 1 error when compiling

### ISSUE THREAD

**Issue by ToadRoasted** [Rubberduckycooly/Sonic-1-2-2013-Decompilation#316]
When trying to build the UWP I get 1 error that says

Error	C2664	'char *strcat(char *,const char *)': cannot convert argument 2 from 'char [4096][128]' to 'const char *'	Sonic1Decomp.UWP

And 26 errors are relating to different things like

Warning	C4244	'=': conversion from 'float' to 'int', possible loss of data	Sonic1Decomp.UWP

and

Warning	C4459	declaration of 'globalSFXCount' hides global declaration	Sonic1Decomp.UWP

**Comment by MegAmi24** [comment]
The UWP version of the decomp has been deprecated, closing
