### ISSUE TITLE
What is "dimming"?

### ISSUE THREAD

**Issue by Davedson-debug** [Rubberduckycooly/Sonic-1-2-2013-Decompilation#317]
What's dimming and what does it do? English is not my native language so i went to the internet to find out what does this word mean, by the help of the Google Translator i realized that dimming has something to do with the screen going black, but changing the dimming value in the .ini file, or even turning it off altogether doesn't seem to change anything, or at least i wasn't able to find any difference by myself, would you guys be so kind to explain what dimming is and how is it used in the game?

**Comment by MegAmi24** [comment]
Dimming, in this context, refers to making the screen slightly darker. The option in the decomp determines how long it takes in seconds for the window to dim when there's no controller input (setting the option to -1 disables the dim).
