### ISSUE TITLE
POV Hat Binding

### ISSUE THREAD

**Issue by SylvWulf** [Rubberduckycooly/Sonic-1-2-2013-Decompilation#318]
Maybe I'm missing something obvious, but is there a way to bind a POV hat in the settings? The dpad of the DirectInput controller I'm using is setup as one and I can't seem to get it to work.

**Comment by MegAmi24** [comment]
Have you tried changing the controller settings in settings.ini? Up, Down, Left, and Right should be numbers 12, 13, 14, and 15 respectively.

**Comment by SylvWulf** [comment]
Yes, those are all indeed set. The buttons on this particular controller work fine, and everything works on a 360 pad, so I assumed the problem was the POV hat. Just for reference the dpad works in other programs like RetroArch, Sonic 3 AIR, and AntiMicro, recognized as a POV hat.

**Comment by MegAmi24** [comment]
It'd probably be helpful to know what controller you're having this issue with.

**Comment by SylvWulf** [comment]
Oh, sorry, it's an 8BitDo M30. I've also tested an SN30 Pro that does the same POV hat dpad thing, and that had the same result (no dpad response, buttons work).
