### ISSUE TITLE
How to add touch inputs on mods?

### ISSUE THREAD

**Issue by Hereward-GH** [Rubberduckycooly/Sonic-1-2-2013-Decompilation#320]
It's been a few days i'm testing this decomp on Android, and it works (without mods).
Now i've installed the Forever mod and i have a good and a bad news: it works but i cannot use touch controls to play.
Is it possible add touch controls support in mods manually by myself?
Thank you!

**Comment by Hereward-GH** [comment]
BTW, which version of GLES is used in the apk?

**Comment by MegAmi24** [comment]
The developers of Sonic 1 Forever deliberately removed touch controls from the mod because it wasn't designed with touch controls in mind. The mod is exclusively designed for use with a controller.

To answer the followup question, version 2.0 is used.

**Comment by Hereward-GH** [comment]
Thank you for the answer.
So, which file i need to modify?

**Comment by Hereward-GH** [comment]
Changing argument, i've discovered something weird about RSDKv3 decomp.
I tried to use SDL 2.0.20 to build Windows and Android executables, and for the first one it works but for Android it give me an error screen (it not happen on RSDKv4 decomp).
I create a fork to test this and i simply modify the build.yml file.

**Comment by Hereward-GH** [comment]
This erro
![Screenshot_2022-04-13-10-15-33-440_com miui gallery](https://user-images.githubusercontent.com/16437893/163132118-9d3c536b-907c-42d8-bb5a-4717779868b5.jpg)
r
