### ISSUE TITLE
Error when trying to build flatpak

### ISSUE THREAD

**Issue by Espio419** [Rubberduckycooly/Sonic-1-2-2013-Decompilation#322]
Failed to download sources: module glu: server certificate verification failed. CAfile: none CRLfile: none

**Comment by Jack0b0Tori** [comment]
Since Sonic Origins is officially announced for 23th June 2022, I suggest you to wait for that and try with Proton on Steam for instance ( or with Wine ). More informations here : https://origins.sonicthehedgehog.com/

**Comment by MegAmi24** [comment]
> Since Sonic Origins is officially announced for 23th June 2022, I suggest you to wait for that and try with Proton on Steam for instance ( or with Wine ). More informations here : https://origins.sonicthehedgehog.com/

As much as we support Sonic Origins and encourage everyone to support it as well, the decomps can still coexist alongside it. There's no reason to tell people to "just wait for Origins".

**Comment by Espio419** [comment]
Answered on r/linuxquestions

It seems this is an issue with GnuTLS, a library used by flatpak-builder (https://github.com/flatpak/flatpak-builder/issues/468). tl;dr: it's not your fault, this is something that is yet to be fixed by someone outside from the decomp staff
