### ISSUE TITLE
Can't Open

### ISSUE THREAD

**Issue by Terong** [Rubberduckycooly/Sonic-1-2-2013-Decompilation#324]
When I Execute The File It's Won't Open Also I Tried All With Run With Administrator 

Fix This :

https://user-images.githubusercontent.com/72803556/167228301-5beb561d-b868-44bd-8603-7a2ab835a5e2.mp4

**Comment by Terong** [comment]
I Need The APK?

**Comment by parkerlreed** [comment]
You need the game data.

**Comment by Terong** [comment]
Thank You!
