### ISSUE TITLE
GameOptions like Fullscreen on Linux Versions

### ISSUE THREAD

**Issue by Super-JoConnell** [Rubberduckycooly/Sonic-1-2-2013-Decompilation#325]
Compiled on Manjaro Successfully, Runs great but compared to the windows versions there's no configurable .ini file.
wish to play in fullscreen natively on linux without using wine/proton if possible
cheers

**Comment by MegAmi24** [comment]
There is a settings.ini, it's located in `~/.local/share/RSDKv4/`.

**Comment by Super-JoConnell** [comment]
excellent thank you, i didn't realize that sorry i'll close the issue thanks
