### ISSUE TITLE
SaveRAM Redirection not working properly

### ISSUE THREAD

**Issue by MegAmi24** [Rubberduckycooly/Sonic-1-2-2013-Decompilation#326]
Enabling/disabling a mod that uses SaveRAM Redirection in the mod menu and then exiting it does not set the save file path properly. This results in erratic behavior from the game. Closing the decomp and reopening it sets the save path properly, however. This bug is in both the 1.3.0 release and the current source build.

**Comment by Rubberduckycooly** [comment]
should be fixed in https://github.com/Rubberduckycooly/Sonic-1-2-2013-Decompilation/commit/50ec57a7360eb1a735f3097e923444d6b86c555c
