### ISSUE TITLE
(Sonic 1) Program shuts down after Game Over despite having multiple Continues

### ISSUE THREAD

**Issue by TopHatHipster** [Rubberduckycooly/Sonic-1-2-2013-Decompilation#33]
I had multiple continues because of the Special Stages, went game over by losing lives in Scrap Brain Zone before the program suddenly quits instead of giving me the option to continue so it's possibly a bug?

MD5 hash of my Data file: F679E87477BBED17FF1BDB9A6793F49C

**Comment by MGRich** [comment]
I'm (surprisingly) unable to replicate this. Maybe it's fixed in master?
![image](https://user-images.githubusercontent.com/29069561/105123892-881f0900-5a9e-11eb-9383-7b698e7e4af9.png)

**Comment by TopHatHipster** [comment]
> I'm (surprisingly) unable to replicate this. Maybe it's fixed in master?
> ![image](https://user-images.githubusercontent.com/29069561/105123892-881f0900-5a9e-11eb-9383-7b698e7e4af9.png)

I used the initial published version (the first proper 'release'), just tried replicating the issue by going through Green Hill Zone Act 1, grabbing a continue by getting enough rings in the Special Stage before Game Over'ing myself in Act 2. Seems to go to the CONTINUE screen just fine. Might be something else that could have triggered it. If I manage to replicate the bug, I'll try to open it up again with more information!
