### ISSUE TITLE
Script decomp doesn't work if RETRO_USE_MOD_LOADER isn't used

### ISSUE THREAD

**Issue by TorutheRedFox** [Rubberduckycooly/Sonic-1-2-2013-Decompilation#333]
![image](https://user-images.githubusercontent.com/15708278/172067703-d4ae429b-7ea0-437b-9743-3f5bac53ec62.png)
if mod loader is used in build, the game runs fine

**Comment by TorutheRedFox** [comment]
yes

the game runs fine with the bytecode, and with text scripts if mod loader is used

**Comment by Rubberduckycooly** [comment]
did some fixes in 5e07d4e, did these fix the issues you were having?

**Comment by TorutheRedFox** [comment]
yep, that fixed it
