### ISSUE TITLE
Score Issue

### ISSUE THREAD

**Issue by Shrekster01** [Rubberduckycooly/Sonic-1-2-2013-Decompilation#338]
When I get 50,000 score or a multiple of 50,000 in Sonic the Hedgehog 1, I do not get an extra life unlike the mobile port.

**Comment by MegAmi24** [comment]
Are you using any mods?

**Comment by Thomashub24** [comment]
I'm just wanna put the movie sonic in my game help me

**Comment by Rubberduckycooly** [comment]
No further info and unable to reproduce, closing this

**Comment by Thomashub24** [comment]
I don't know how to put the mod in my phone
Help me
