### ISSUE TITLE
Opens in a proper widescreen window, but becomes pillarboxed in Fullscreen.

### ISSUE THREAD

**Issue by vic-viper-001** [Rubberduckycooly/Sonic-1-2-2013-Decompilation#343]
When first opening Sonic 1 or 2, the game will display in a proper widescreen window.  As soon as I switch the game to Fullscreen using "F4", the graphics become pillar-boxed... big black bars are displayed on the left and right sides.  

It basically looks the same as just playing the vanilla game on an emulator, because with full-screen pillar-boxing, you don't get the benefits of a wider screen at all.

To be fair, my laptop screen resolution is a bit uncommon at a 2650x1600 16:10 ratio, but every 16:9 ratio game I've played thus far has been able to display fine, albeit with very minor black bars on the top and bottom of the screen. 

I've tried looking at "settings.ini". I set fullscreen to "true" and still have pillar-boxing. I've tried adjusting WIDTH, but changing this value only makes things worse. For example, I tried typing 1920 for width and this makes the window FAR wider than my screen. With this 1920 value in place, full screen video is now a misshapen tiny column in the center of the screen.

**Comment by Leonx254** [comment]
The correct width value for 16:10 is 384, try that

**Comment by vic-viper-001** [comment]
This fixes the issue, and now the game displays properly. Thank you!
