### ISSUE TITLE
Can't press start on the sonic 1 title screen?

### ISSUE THREAD

**Issue by RhythmLunatic** [Rubberduckycooly/Sonic-1-2-2013-Decompilation#344]
I compiled the latest git commit on linux, the start button and the other buttons work in the menu screen but I can't press it on the title screen of sonic 1. I have to click the screen for the game to start.
Maybe it's because I have a touch screen? I tried with a controller but the controller's start button also doesn't work outside of the menu.

I'm using the android rsdk with `b0a17e35bbc95b00ede921c1c0b80d40` (v3.7.1).

**Comment by Espio419** [comment]
Same issue on Linux
