### ISSUE TITLE
Menu showing Achievements and Leaderboards when compiled for Linux

### ISSUE THREAD

**Issue by Zandengoff** [Rubberduckycooly/Sonic-1-2-2013-Decompilation#349]
I compiled from source on Ubuntu 18.04 and was able to complete it successfully. After which I found that the menus in Sonic 1 and 2 showed both Achievements and Leaderboards. Both options do not connect (obviously) and seem to have been intentionally hidden from the Windows release. Is there something I need to change either in compile or config to hide these menu items?

**Comment by Rubberduckycooly** [comment]
That means the game thinks it has online support (which it may do, I dunno for sure) but it sounds like there's no real issue here atm so I'll close this for now
