### ISSUE TITLE
Native function to change mod priorities?

### ISSUE THREAD

**Issue by ElspethThePict** [Rubberduckycooly/Sonic-1-2-2013-Decompilation#350]
SwapModPriority(int mod, bool up or down)

Swpas the priority of the stated mod with either the one above it or below it.
Or something. Please?

**Comment by Rubberduckycooly** [comment]
added as of 9a3d237fb716a61040aa244a906b21ccdeea827a, tested it and it should work as described. Please re-open the issue if there's any problems, thanks!
