### ISSUE TITLE
Usage instructions

### ISSUE THREAD

**Issue by Slider-Whistle** [Rubberduckycooly/Sonic-1-2-2013-Decompilation#351]
It would be ideal for the binary to print some usage instructions when it doesn't find the file it's looking for. Maybe a list of default paths, or even an option to specify where it is? I've run "make install" and I'm utterly lost as to where to go from here. The information on the unofficial (?) GameBanana guide only pertains to the Windows build.

**Comment by Rubberduckycooly** [comment]
Added a simple usage text file in 9a3d237fb716a61040aa244a906b21ccdeea827a that gets output in the event assets can't be loaded, hopefully this is what you were describing! It'll be in the next major release and any future autobuilds! Feel free to re-open this issue in the event more needs to be done!

**Comment by Slider-Whistle** [comment]
I deleted my ~/.local/share/RSDKv4 and ran it again just to check, but no window or message seems to be coming up?
I know personally now that "Data.rsdk" has got to be in $HOME/.local/share/RSDKv4, but maybe a note in the README.md, or printing an error message might help users figure that out more quickly.
![rsdk](https://user-images.githubusercontent.com/33862922/181658119-84458c35-9924-4009-a897-1d787b0ed157.png)
