### ISSUE TITLE
S1 Special Stage time attack stays locked

### ISSUE THREAD

**Issue by scalliano-the1st** [Rubberduckycooly/Sonic-1-2-2013-Decompilation#352]
Hi, I've just signed up as I haven't been able to find anything about this issue online. I've beaten the game twice (once with Sonic, once with Tails) and played through the entire regular Time Attack, but the Special stages are still showing up as locked. Is this a bug or is there something I've missed?

I'm running latest version, x64 rev02. Any help would be appreciated.

**Comment by Rubberduckycooly** [comment]
That is indeed a bug, it looks like S1 Special Stages aren't handled correctly by the time attack menu, apologies! I have fixed it in 0ab0d70a15cb8d68be05e950912fe0c23b233f82, and it will be in any future auto builds and the next major release!
