### ISSUE TITLE
Unplayable Decompilation?

### ISSUE THREAD

**Issue by Sonicthe06** [Rubberduckycooly/Sonic-1-2-2013-Decompilation#353]
How Can I Play This Decompilation On Steam If Its Removed?

![Screenshot 2022-07-08 192901](https://user-images.githubusercontent.com/105401700/178088286-327d3292-0d5c-487b-ba82-c623aadc9293.png)

![Screenshot 2022-07-08 193651](https://user-images.githubusercontent.com/105401700/178088533-9307e6c4-a62f-430f-826a-350f769fb349.png)

**Comment by MegAmi24** [comment]
The Steam version of Sonic 1 was just the original Genesis ROM, which doesn't work with the decomp

**Comment by peterclaudius** [comment]
Sonic 1 & 2 (Windows) Via Steam, from [Sonic Origins] don´t work
