### ISSUE TITLE
Coin counter resets after completing special stage

### ISSUE THREAD

**Issue by Zandengoff** [Rubberduckycooly/Sonic-1-2-2013-Decompilation#356]
On the latest source build as of early July, when completing a special stage on Sonic 2 when returning back to the main stage, the number of rings returns to 0 regardless of how many you entered the special stage with.

**Comment by DamianS-eng** [comment]
This was always the case in the original Genesis version, at least Sonic 2 alone. Knuckles in Sonic 2 may not have had the counter reset, but need to confirm, as well as if this is the case in the actual mobile ports.

If any of these are true, maybe have a toggle option in the settings to allow or prevent the coins to reset after special stages, but not a priority.
