### ISSUE TITLE
NON-WORKING DATAFILES

### ISSUE THREAD

**Issue by MGRich** [Rubberduckycooly/Sonic-1-2-2013-Decompilation#36]
If your data file SHA-256 hash (unless otherwise specified) is ONE OF THE FOLLOWING: 
- S1 2.0.5 `749D6369867CDD73075959A7832C0394662BB7A5E8C9702C5AF20F8E0D0D979E`
- S1 2.0.4 MD5 `6C6881E3DBDE73D4DD0B37F68996A700C1186B1F`
- S2 3.1.0 `90991207BFEFA09CF4DD0EE57365DFD2047172D531BE93AFC8FFF196078E034F`
- S2 3.0.2 `787E022A40FE2B3017DAE176ECC294CC752E2B765ED486B1C841C0F9F873334F`
- S2 ????? `168B5490771F5C6DB5BCD12A194A2A6367ABC0A4645F165127F6F4831AE097BC`

then they **will crash** upon loading a level and **hang on the title screen (if S2.)**

**Comment by Rubberduckycooly** [comment]
as an update to this we are working on a solution that'll allow these datafiles to be run in the next builds, as we have confirmed the issue and developed a solution for it

**Comment by MGRich** [comment]
If these still occur to you, ensure you are using the `_rev01` build.
