### ISSUE TITLE
Super Sonic visible in the top left corner of the screen in Sonic 2's ending.

### ISSUE THREAD

**Issue by AbnormalPoof** [Rubberduckycooly/Sonic-1-2-2013-Decompilation#360]
Tested on Debian 11 using the master branch.
After beating the Death Egg Robot with all 7 Chaos Emeralds, Super Sonic can be seen on the top left while the ending cutscene is playing.

This does NOT happen in the original mobile port, nor in the normal Sonic ending

Refer to image below:
![Screenshot 2022-07-28 11 54 25 PM](https://user-images.githubusercontent.com/86753001/181685969-715876b5-7e2f-4c4a-9a03-aa64518387d7.png)

**Comment by MGRich** [comment]
Is this on bytecode or base scripts?

**Comment by AbnormalPoof** [comment]
Bytecode
