### ISSUE TITLE
[Feature request] Allow for non-square pixel aspect

### ISSUE THREAD

**Issue by awe444** [Rubberduckycooly/Sonic-1-2-2013-Decompilation#364]
I have a display with resolution 720x240, but the pixels are “tall and skinny” such that the pixel aspect ratio is about 1:2 (width:height). I would like to be able to set the game’s width at 360px and have it apply a 2x integer scale horizontally while keeping it at 1x scale vertically. Currently the scaling engine forces the scale factors to be the same in both dimensions, so this is not possible.

By hacking various parts of the code, I’ve managed achieve this in the main game but the menus still seem to expect 1:1 pixel aspect ratio. I’d be interested if separate scaling factors could be set for horizontal and vertical and have these apply correctly to the main game as well as menus.

**Comment by MegAmi24** [comment]
We aren't adding any more major features like this, sorry

**Comment by awe444** [comment]
Fair enough—thanks anyways for your work on this project!
