### ISSUE TITLE
Stuck on fetching room code when I try to make a lobby

### ISSUE THREAD

**Issue by RealPogger** [Rubberduckycooly/Sonic-1-2-2013-Decompilation#366]
When I try to run the server it gets stuck on starting.
![Screenshot 2022-08-04 120835](https://user-images.githubusercontent.com/92672257/182895862-a22579ee-b538-4995-bae5-11d1e548ca38.png)

**Comment by MGRich** [comment]
That means it started just fine. It will not output anything until a connection is made.

**Comment by RealPogger** [comment]
I even checked if I can join when I put in the right information in the settings file but it just gets stuck at fetching room code
