### ISSUE TITLE
Hosting a lobby makes it get stuck at room code fetching

### ISSUE THREAD

**Issue by RealPogger** [Rubberduckycooly/Sonic-1-2-2013-Decompilation#369]
I have the server setup the right way and even put the server information in the settings.ini file but it still wont let me host a lobby.

**Comment by RealPogger** [comment]
Another note is that when I try to access the 2P VS menu without the Sonic 2 Remastered EX mod it says Unable to connect

**Comment by MegAmi24** [comment]
Are you using a release version of the decomp?

**Comment by RealPogger** [comment]
Yeah, I'm using the latest version of the sonic 2 decomp

**Comment by MegAmi24** [comment]
The current servers don't with 1.3.0, wait for an update

**Comment by RealPogger** [comment]
Should I try a older version then for 2 player versus
