### ISSUE TITLE
S1: specific tube interactions temporarily remove player control

### ISSUE THREAD

**Issue by Decidetto** [Rubberduckycooly/Sonic-1-2-2013-Decompilation#37]
When entering a tube at a low enough speed to be pushed back out while holding the "inwards" direction, control is temporarily removed from the player upon exiting the tube.

Illustrated below, I am holding left for the entire duration of the GIF, yet you can see that Sonic stands still for a while upon exiting the tube despite the direction being held.
![tube](https://user-images.githubusercontent.com/5384177/104970214-fbffd980-59ea-11eb-8e29-4d59b63cb402.gif)

In the original mobile version you can move immediately after exiting the tube.

(Using Data.rsdk from v2.0.8)

**Comment by MGRich** [comment]
Possibly a control lock timer issue with scripts?

**Comment by Rubberduckycooly** [comment]
tested on my android device, seems to be intentional behaviour, there can be a script mod to fix this made later down the line but it is not a core issue with the decomp/engine itself

**Comment by Decidetto** [comment]
The game at version 2.0.8 on my IOS device doesn't exhibit the control removal in the same situation. Is it something that would have come from an engine update in a subsequent version, then, rather than the RSDK file?
