### ISSUE TITLE
Can't override controller mappings

### ISSUE THREAD

**Issue by Willicious** [Rubberduckycooly/Sonic-1-2-2013-Decompilation#370]
I'd ideally like to be able to set up a controller with my own mappings.

I'm using a DualShock4 and Antimicro, which I use to map the DS4 to various preferred keyboard inputs.

However, when I start up the decompilation it just rewrites the controller mappings so that I have to use the in-game defaults. I'd prefer to either override them or disable them altogether tbh.

Any suggestions?

**Comment by slambo311** [comment]
I'd also prefer remappable buttons. Literally just a few minutes ago I was trying to play Sonic Forever on android. So I whipped out my Joy-cons, only to realize that I can't remap the buttons.

**Comment by MegAmi24** [comment]
You can, just edit the Controller 1 category in settings.ini. Use [this page](https://github.com/libsdl-org/sdlwiki/blob/main/SDL_GameControllerButton.mediawiki) to find the buttons you want to map.
