### ISSUE TITLE
Where is Tails in Sonic 2???

### ISSUE THREAD

**Issue by WillLem** [Rubberduckycooly/Sonic-1-2-2013-Decompilation#371]
OK, maybe I'm missing something really obvious here... but, where is Tails in Sonic 2? Isn'the is meant to be following Sonic around as a ring-collecting companion?

The character select screen only shows Sonic, whilst both Tails and Knuckles are greyed out. And there seems to be no option to group Sonic and Tails together to play in co-op.

I'm guessing it's probably the APK I'm using?

(I have a legit copy of Sonic 2 on my iPhone, and the character select screen does indeed give the option to link Sonic and Tails together in co-op).

**Comment by RealPogger** [comment]
Is there a plus that connects sonic and tails on the player select menu?

**Comment by RealPogger** [comment]
I'm trying my best, I don't know how this works.

**Comment by WillLem** [comment]
> Is there a plus that connects sonic and tails on the player select menu?

No, unfortunately not. There is on the mobile version (which I have), but not on the decompiled version

**Comment by Rubberduckycooly** [comment]
Sometimes sonic 2 will lock tails and knux since it thinks its sonic 1, you can delete your save file and it should fix it
