### ISSUE TITLE
Android: Add "launcher" option for Sonic 1 and 2?

### ISSUE THREAD

**Issue by Shockwave508** [Rubberduckycooly/Sonic-1-2-2013-Decompilation#380]
In RSDKv4's current state, you can only have either Sonic 1 or 2 installed, not both. Would it be possible to add a "launcher" feature to the Android build, so the Sonic 1 and 2 data have their own separate folders and configs, so you don't have to keep swapping out files if you want to switch games?

**Comment by MegAmi24** [comment]
No, that'd take more effort than it's worth
