### ISSUE TITLE
Android: Script parsing always fails if mods try to load.

### ISSUE THREAD

**Issue by Shockwave508** [Rubberduckycooly/Sonic-1-2-2013-Decompilation#381]
When attempting to start a game within the Sonic 1 & 2 decompilations, I always run into this error when I attempt to load any mods whatsoever.
![Screenshot_2022-10-09-03-02-34-491_com decomp rsdkv4](https://user-images.githubusercontent.com/32436386/194745184-d0cccffc-8237-4360-af0e-8149c15f54ab.jpg)
The only way to remove this error is to yank out the Scripts folder, set TxtScripts=false, and manually set every installed mod to false.

I am using the latest GitHub builds of both the decompilation and the required script packages.

**Comment by MegAmi24** [comment]
You're using a mod that hasn't been updated to work with the latest version of the scripts yet
