### ISSUE TITLE
Camera Inaccuracies

### ISSUE THREAD

**Issue by RulerOfWaffles** [Rubberduckycooly/Sonic-1-2-2013-Decompilation#382]
When releasing a spindash in the decomp, the camera is completely stationary for a split second then catches up to the player, when it should only be stationary on the x axis like in the mobile/Origins releases. You can see in the video I recorded that after releasing a spindash, the camera doesn't pan up to where Sonic is in the decomp.

https://www.youtube.com/watch?v=6pvFLcDshFw

Also shown, the camera lags behind vertically when the player is at top speed and running over a steep hill, or in the case of Sonic 2, running through the corkscrew in Emerald Hill. This doesn't happen in the mobile/Origins versions. This affects both games(same with the spindash issue).

**Comment by LittlePlanetCD** [comment]
This should be fixed in the current commits, just letting you know this.
