### ISSUE TITLE
No controller input (DirectInput)

### ISSUE THREAD

**Issue by TopHatHipster** [Rubberduckycooly/Sonic-1-2-2013-Decompilation#4]
I tried rebinding the controller inputs from the SDL config in settings.ini to match my controller's but it does not react in game or in the menu.

Turned Dev Mode off
No other application was running that took the controller input
It involves the SEGA Mega Drive/Genesis Mini 3B Controller (that is compatible with Windows natively as a DInput device, that should work with SDL)

Also, there seems to be no way of mapping axis?

My config:
A = 3
B = 2
C = 6
Start = 10
Up/Down/Left/Right should be -a4, +a4, -a3, +a3 but they get zeroed out upon initialising.  (D-Pad is X/Y axis based, no buttons)

Also tried having them set at a lower button number to take a 0-index start into account, made no difference.

Edit:
For clarity, according to Windows, the following button layout is present with the 3B Controller:
A = 3, B = 2, C = 6, Start = 10, Up = Y up, Down = Y down, Left = X left, Right = X right. Only one analog stick was visible.

**Comment by TopHatHipster** [comment]
Little update:

Tested a wired Xbox One controller and that works just fine with the game with standard bindings. But it seemingly does not detect any DirectInput controller input.

**Comment by SeventhSentinel** [comment]
A wrapper such as x360ce may be a good workaround.

**Comment by TopHatHipster** [comment]
> A wrapper such as x360ce may be a good workaround until DirectInput is supported.

Yeah, currently I'm launching the decompilations through Steam to assign the Xbox/XInput buttons to my Mega Drive Mini 3B Controller. But native support (if possible) would be preferred!

**Comment by blawar** [comment]
you can use steam to wrap the controller as well.
