### ISSUE TITLE
S1 Credits Crash

### ISSUE THREAD

**Issue by BubbyNE** [Rubberduckycooly/Sonic-1-2-2013-Decompilation#40]
After the Star Light Zone fadeaway, Nakamura's name popped up, but the next cutscene (Scrap Brain) failed to load and my game crashed.

I have a recording of this occurring here: https://youtu.be/mg4FFN7tzfg (Xbox Game Bar made it look crappy, my b on that end)

I also attached the log if that helps.
[log.txt](https://github.com/Rubberduckycooly/Sonic-1-2-2013-Decompilation/files/5832886/log.txt)

**Comment by FreshRoyal** [comment]
I experienced this as well. If you're using the data file from a paid APK, that could be the issue. I swapped it for the latest version of the Sega Forever release, and it worked fine.

**Comment by MGRich** [comment]
Needs to be tested further, but is likely to be RSDK specific.

**Comment by Rubberduckycooly** [comment]
looked into this, it turned out to be a memory leak that would occur if the game was played for too long, will be fixed in the next build
