### ISSUE TITLE
mod loader(s, built-in and RSDKMM) do not work

### ISSUE THREAD

**Issue by ThatCesarMan** [Rubberduckycooly/Sonic-1-2-2013-Decompilation#401]
hi
i'm trying to develop a mod (decomp version 1.3.0) and it doesn't show anything on the mod menu built-in
![image](https://user-images.githubusercontent.com/80134534/217117027-9ae8e072-0711-4bb9-83a4-7d4e61647d4b.png)
RSDKMM does absolutely nothing
the mod was formatted using MegAmi's tutorial

**Comment by LittlePlanetCD** [comment]
the mod loader does work, you did something wrong on your end.

can you send a pic of your mod's folder?

**Comment by ThatCesarMan** [comment]
> the mod loader does work, you did something wrong on your end.
> 
> can you send a pic of your mod's folder?
is there supposed to be an ini showing the mods or not?
![image](https://user-images.githubusercontent.com/80134534/217320095-2e10be9f-b1a7-44b1-b1f7-068a9c854618.png)
also this name is temporary af

**Comment by ThatCesarMan** [comment]
oh wait
you meant mod's folder not mods folder @LittlePlanetCD 
there's a mod.ini that says this:
`Name=Sonic the Hedgehog MyCut
Description=Just some things i felt like inserting.
Author=CesarGrim
Version=1.0.0
TxtScripts=true`

**Comment by MegAmi24** [comment]
you need line breaks between each tag

**Comment by ThatCesarMan** [comment]
@MegAmi24 i have those in unix lf
it's just github that fucked it up
