### ISSUE TITLE
RSDKv4 crashes when pressing START in-game (Sonic The Hedgehog Classic)

### ISSUE THREAD

**Issue by IPeluchito** [Rubberduckycooly/Sonic-1-2-2013-Decompilation#404]
1.Enter the game (Pass Title Menu)
2.Press START button (Xbox360 Controller)
3.Crash
![snip_00006](https://user-images.githubusercontent.com/64821708/222553380-4ebaa816-6f82-4ec8-b667-5ae0b0c61d2c.png)

**Comment by MegAmi24** [comment]
What game? What version of it? Are you using the decompiled scripts?

**Comment by IPeluchito** [comment]
Sonic The Hedgehog Classic (Data.rsdk Version 3.7.1 Android)
RSDKv4 latest build (01/03/23)

Windows 11 build 22000.1516 / GTX 1660Ti / DS4 with DS4Windows

**Comment by MegAmi24** [comment]
There's been plenty of changes made in the repository since January. Can you test this on the most recent commit?

**Comment by IPeluchito** [comment]
Sonic The Hedgehog Classic (Data.rsdk Version 3.7.1 Android)
RSDKv4 latest build (03/01/23)

Windows 11 build 22000.1516 / GTX 1660Ti / DS4 with DS4Windows

**Comment by IPeluchito** [comment]
Latest version that works correctly the controls:
https://github.com/Rubberduckycooly/Sonic-1-2-2013-Decompilation/commit/b59c2d65c62a4fc1798d5a7a51d73e867ae2cc17

After that version the controls in one way or another are broken until today... you should start from there...

**Comment by MrRumbleRoses** [comment]
i've been having this kinda issue as well. i got the latest version, and whenever i press start. the game freezes and then crashes

**Comment by IPeluchito** [comment]
Fixed !!! although I also noticed that the B button is assigned the function to jump and go back at the same time...Is it the same in the original version with gamepad?

**Comment by MegAmi24** [comment]
Yeah it's just like that normally, using script mods will fix it though.
