### ISSUE TITLE
Modifying Characters.ani files breaks the collision

### ISSUE THREAD

**Issue by SonicOrbinautFramework** [Rubberduckycooly/Sonic-1-2-2013-Decompilation#406]
I'm trying to make a mod to convert Sonic 2 into Sonic 3, but every once I modify a character.ani file (Currently Sonic and Tails), the collision offsets break.

Original(no mods):

https://user-images.githubusercontent.com/111817133/227798423-d9ed4a57-5bc5-4c6f-9db8-d3f9b8b3d313.mp4

S3K Mod: 
[https://www.mediafire.com/file/69wvfa21jdp8zq0/Sonic_3_%2526_Knuckles_%2528Using_Data_Folder%2529_2023-03-26_14-07-10.mp4/file]

I'm using both the RSDK Animation Editor 2.0 Beta and the 1.2.2 version (The old one)

**Comment by MegAmi24** [comment]
Both of those versions of the animation editor are outdated, and 2.0 specifically is what's breaking the hitboxes, use [1.5.0](https://github.com/Rubberduckycooly/RSDK/releases/latest) instead.
Also, this isn't the place for modding support.
