### ISSUE TITLE
Cannot Pause both of the games.

### ISSUE THREAD

**Issue by UckyDuckyYT** [Rubberduckycooly/Sonic-1-2-2013-Decompilation#407]
For both Sonic 1 and 2 there seems to be a bug that stops me from pausing, if i press enter in game then i hear the pause noise and then it just crashes. ( it also crashes if you click on the area where the pause button would be for mobile users )

**Comment by MegAmi24** [comment]
This is a known bug, we've fixed it in master but for the release build of 1.3.1 the workaround is to enable the Dev Menu in ``settings.ini``.
