### ISSUE TITLE
Sharp Bilinear Missing?

### ISSUE THREAD

**Issue by Danhanado** [Rubberduckycooly/Sonic-1-2-2013-Decompilation#409]
Just updated and the game no longer scales cleanly, it's fully sharp with uneven pixels.
Looking at the Settings.ini the option for sharp bilinear is not there, only nearest and linear, is there a workaround to this?

**Comment by MegAmi24** [comment]
Sharp bilinear broke due to the rendering backend revamp from 1.3.0, because of this as well as the fact that it wasn't supposed to be added in the first place (the pull request that added it was merged by accident), we decided to remove it altogether.
