### ISSUE TITLE
Game crashes when pause is pressed.

### ISSUE THREAD

**Issue by Reapley** [Rubberduckycooly/Sonic-1-2-2013-Decompilation#410]
### Expected Behavior

The game should not crash when pressing x to jump

### Actual Behavior

The game crashes when pressing x to jump

### Steps to Reproduce

In windows, after entering a game, if you press x, sonic jumps for a second and then the game crashes.

### Decompilation Version

1.3.1

### Game

Sonic 1

### Game Version

Mobile (Pre-Sega Forever)

### Platform

Windows 11

**Comment by Reapley** [comment]
It also crashes when enter is pressed to pause the game, in both sonic 1 and sonic 2

**Comment by MegAmi24** [comment]
This has been fixed in master, the workaround for the release build is to enable DevMenu in settings.ini.
