### ISSUE TITLE
Blank screen sonic 1 and sonic 2 on SDL2 but I hear the music

### ISSUE THREAD

**Issue by MSHectorCM** [Rubberduckycooly/Sonic-1-2-2013-Decompilation#418]
### Expected Behavior

Be able to see the screen

### Actual Behavior

Running RSDKv4 with the Data.rsdk of Sonic1 or Sonic2 I have a blank screen

### Steps to Reproduce

- Compile with the flags -DRETRO_SDL_VERSION=2 -DRETRO_USE_HW_RENDER=OFF
- Put the Data.rsdk on the same folder as RSDKv4 
- Run RSDKv4 
- There is no video (blank screen) but the background music is working fine.
- Issue seems to be in the prebuilt menu before the game.

### Log File

Sonic1
[log.txt](https://github.com/Rubberduckycooly/Sonic-1-2-2013-Decompilation/files/12647191/log.txt)

### Decompilation Version

autobuild

### Game

Sonic 1

### Game Version

Mobile (Sega Forever)

### Game Revision

3.9.2

### Platform

Linux

### Additional Comments

- In blank screen, if I manage to select start the game . The game starts as and I can see the sega screen the main menu and I can play.

**Comment by MegAmi24** [comment]
The main menu depends on the HW Renderer, so disabling it means that the menu won't work properly. You'll have to build with the HW Renderer enabled, or you can disable the main menu entirely and skip straight to the game by enabling `SkipStartMenu` in `settings.ini`.

**Comment by MSHectorCM** [comment]
Cool thx I didn't know about SkipStartMenu . Is it any side effects of using skipstartmenu? thx
