### ISSUE TITLE
Slight error in RSDKv3 & 4 readme

### ISSUE THREAD

**Issue by nickbailuc** [Rubberduckycooly/Sonic-1-2-2013-Decompilation#419]
### Expected Behavior

-

### Actual Behavior

-

### Steps to Reproduce

-

### Decompilation Version

-

### Game

Sonic 1

### Game Version

Mobile (Pre-Sega Forever)

### Platform

-

### Additional Comments

README for both S 1,2 and CD decomp repos
under compiling for Debian, `sdl2-dev` should be `libsdl2-dev` otherwise apt will refuse all installs.

I'm sure a new person to Linux will come across this simple error and end up not being able to compile later on.

Sorry, didn't want to create 2 pull requests just for this tiny issue

**Comment by MegAmi24** [comment]
Fixed that, thanks for telling us
