### ISSUE TITLE
(Feature request) StartingSaveSlot in config

### ISSUE THREAD

**Issue by SneezingCactus** [Rubberduckycooly/Sonic-1-2-2013-Decompilation#42]
Could you add a config key that makes the game start in a specific save slot, similar to StartingCategory and StartingScene?

**Comment by MGRich** [comment]
Do you mean like if it was previously defined it'll just boot straight into it?

**Comment by Rubberduckycooly** [comment]
this has been fixed, the fix will be avaliable in the next build
