### ISSUE TITLE
Error when trying to install the dependencies

### ISSUE THREAD

**Issue by Springfall89** [Rubberduckycooly/Sonic-1-2-2013-Decompilation#423]
### Expected Behavior

Download the dependencies successfully

### Actual Behavior

Trying to download openGL : x64-windows-static and got BUILD-FAILED

### Steps to Reproduce

1. Download the latest version of Visual Studio **(1.17.6 around this time)** with **Desktop Development with C++**
2. Download **Git 2.42.0.2** and **CMake 3.27.5  (with system path for ALL users)**
3. Install the Sonic 1 & 2 repositories and vcpkg **(I used the [2023.08.09 Release)**
4. Install the dependencies for Sonic 1 & 2
5. While I was trying to install openGL : x64-windows-static, I suddenly got an error saying **BUILD_FAILED** and other stuff

### Screenshots

Here's the error in full detail
![Screenshot 2023-11-06 185903](https://github.com/Rubberduckycooly/Sonic-1-2-2013-Decompilation/assets/150023618/e9fe98f4-6531-4962-be18-38da442e083d)

Here's the text version:
Microsoft Windows [Version 10.0.22621.2361]
(c) Microsoft Corporation. All rights reserved.

C:\Users\**Name**\vcpkg>vcpkg.exe install glew sdl2 libogg libvorbis --triplet=x64-windows-static
Computing installation plan...
The following packages will be built and installed:
  * egl-registry:x64-windows-static -> 2022-09-20
    glew:x64-windows-static -> 2.2.0#3
    libogg:x64-windows-static -> 1.3.5#1
    libvorbis:x64-windows-static -> 1.3.7#2
  * opengl:x64-windows-static -> 2022-12-04#3
  * opengl-registry:x64-windows-static -> 2022-09-29#1
    sdl2[base,core]:x64-windows-static -> 2.28.3
  * vcpkg-cmake:x64-windows -> 2023-05-04
  * vcpkg-cmake-config:x64-windows -> 2022-02-06#1
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-windows-static...
Detecting compiler hash for triplet x64-windows...
A suitable version of 7zip was not found (required v23.1.0) Downloading portable 7zip 23.1.0...
Downloading 7zip...
https://www.7-zip.org/a/7z2301-extra.7z->C:\Users\**Name**\vcpkg\downloads\7z2301-extra.7z
Downloading https://www.7-zip.org/a/7z2301-extra.7z
Extracting 7zip...
Restored 0 package(s) from C:\Users\**Name**\AppData\Local\vcpkg\archives in 811 us. Use --debug to see more details.
Installing 1/9 egl-registry:x64-windows-static...
Building egl-registry:x64-windows-static...
-- Downloading https://github.com/KhronosGroup/EGL-Registry/archive/af97e2c27b49a090a335fc6ed5040c780ad9fec8.tar.gz -> KhronosGroup-EGL-Registry-af97e2c27b49a090a335fc6ed5040c780ad9fec8.tar.gz...
-- Extracting source C:/Users/**Name**/vcpkg/downloads/KhronosGroup-EGL-Registry-af97e2c27b49a090a335fc6ed5040c780ad9fec8.tar.gz
-- Using source at C:/Users/**Name**/vcpkg/buildtrees/egl-registry/src/780ad9fec8-51aa70c4bd.clean
-- Installing: C:/Users/**Name**/vcpkg/packages/egl-registry_x64-windows-static/share/egl-registry/copyright
-- Performing post-build validation
Stored binaries in 1 destinations in 187 ms.
Elapsed time to handle egl-registry:x64-windows-static: 10 s
Installing 2/9 opengl-registry:x64-windows-static...
Building opengl-registry:x64-windows-static...
-- Downloading https://github.com/KhronosGroup/OpenGL-Registry/archive/5bae8738b23d06968e7c3a41308568120943ae77.tar.gz -> KhronosGroup-OpenGL-Registry-5bae8738b23d06968e7c3a41308568120943ae77.tar.gz...
-- Extracting source C:/Users/**Name**/vcpkg/downloads/KhronosGroup-OpenGL-Registry-5bae8738b23d06968e7c3a41308568120943ae77.tar.gz
-- Using source at C:/Users/**Name**/vcpkg/buildtrees/opengl-registry/src/120943ae77-d1a12ea691.clean
-- Installing: C:/Users/**Name**/vcpkg/packages/opengl-registry_x64-windows-static/share/opengl-registry/copyright
-- Performing post-build validation
Stored binaries in 1 destinations in 1.6 s.
Elapsed time to handle opengl-registry:x64-windows-static: 8.2 min
Installing 3/9 opengl:x64-windows-static...
Building opengl:x64-windows-static...
CMake Error at ports/opengl/portfile.cmake:13 (message):
  Portfile not yet configured for Windows SDK with version:
Call Stack (most recent call first):
  ports/opengl/portfile.cmake:46 (copy_from_windows_sdk)
  scripts/ports.cmake:147 (include)

error: building opengl:x64-windows-static failed with: BUILD_FAILED
Elapsed time to handle opengl:x64-windows-static: 203 ms
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+opengl
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?title=[opengl]+Build+error&body=Copy+issue+body+from+C%3A%2FUsers%2F**Name**%2Fvcpkg%2Finstalled%2Fvcpkg%2Fissue_body.md

### Decompilation Version

1.3.2 Plus

### Game

Sonic 1

### Game Version

Sonic Origins

### Platform

Windows 11

**Comment by MegAmi24** [comment]
"opengl" is not an actual dependency you're supposed to install. Make sure you're reading the building steps in the readme.
