### ISSUE TITLE
I finally compiled the origins decomp but when i tried to setup sonic 1 and opened the .exe file it crashed

### ISSUE THREAD

**Issue by Springfall89** [Rubberduckycooly/Sonic-1-2-2013-Decompilation#424]
### Expected Behavior

after launching the .exe it should be playable

### Actual Behavior

launched it and i was met with a start menu of sega and christian whitehead just like the old remastered decomps but it crashed after the start menu dissappeared

### Steps to Reproduce

1. compile the decomp (I tried both release and debug)
2. setup the data mods and scripts (I used the Origins data folder)
3. launch RSDKv4.exe
4. see the start menus
5. crash

### Screenshots

https://github.com/Rubberduckycooly/Sonic-1-2-2013-Decompilation/assets/150023618/f7230311-4c00-4185-8e1b-339dc19b67ce

### Decompilation Version

1.3.2 Plus

### Game

Sonic 1

### Game Version

Sonic Origins

### Platform

Windows 11

### Additional Comments

Heres my settings.ini data if u need it

[Dev]
; Enable this flag to activate dev menu via the ESC key
DevMenu=true
; Enable this flag to activate features used for debugging the engine (may result in slightly slower game speed)
EngineDebugMode=false
; Enable this flag to force the engine to load from the scripts folder instead of from bytecode
TxtScripts=false
; Sets the starting category ID
StartingCategory=255
; Sets the starting scene ID
StartingScene=255
; Sets the starting player ID
StartingPlayer=255
; Sets the starting save file ID
StartingSaveFile=255
; Determines how fast the game will be when fastforwarding is active
FastForwardSpeed=8
; Determines if applicable rendering modes (such as 3D floor from special stages) will render in "High Quality" mode or standard mode
UseHQModes=true
; Determines where the first RSDK file will be loaded from
DataFile=Data.rsdk

[Game]
; Sets the game language (0 = EN, 1 = FR, 2 = IT, 3 = DE, 4 = ES, 5 = JP, 6 = PT, 7 = RU, 8 = KO, 9 = ZH, 10 = ZS)
Language=0
; Determines game type in scripts (0 = Standalone/Original releases, 1 = Origins release)
GameType=0
; If set to true, disables the start menu
SkipStartMenu=false
; Handles pausing behaviour when focus is lost
; 0 = Game focus enabled, engine focus enabled
; 1 = Game focus disabled, engine focus enabled
; 2 = Game focus enabled, engine focus disabled
; 3 = Game focus disabled, engine focus disabled
DisableFocusPause=0

[Network]
; The host (IP address or "URL") that the game will try to connect to.
Host=127.0.0.1
; The port the game will try to connect to.
Port=50

[Window]
; Determines if the window will be fullscreen or not
FullScreen=false
; Determines if the window will be borderless or not
Borderless=false
; Determines if VSync will be active or not (not recommended as the engine is built around running at 60 FPS)
VSync=false
; Determines what scaling is used. 0 is nearest neighbour, 1 is linear.
ScalingMode=0
; How big the window will be
WindowScale=2
; How wide the base screen will be in pixels
ScreenWidth=424
; Determines the target FPS
RefreshRate=60
; Determines the dim timer in seconds, set to -1 to disable dimming
DimLimit=300

[Audio]
BGMVolume=1.000000
SFXVolume=1.000000

[Keyboard 1]
; Keyboard Mappings for P1 (Based on: https://github.com/libsdl-org/sdlwiki/blob/main/SDL2/SDLScancodeLookup.mediawiki)
Up=82
Down=81
Left=80
Right=79
A=29
B=27
C=6
X=4
Y=22
Z=7
L=20
R=8
Start=40
Select=43

[Controller 1]
; Controller Mappings for P1 (Based on: https://github.com/libsdl-org/sdlwiki/blob/main/SDL2/SDL_GameControllerButton.mediawiki)
; Extra buttons can be mapped with the following IDs:
; CONTROLLER_BUTTON_ZL             = 16
; CONTROLLER_BUTTON_ZR             = 17
; CONTROLLER_BUTTON_LSTICK_UP      = 18
; CONTROLLER_BUTTON_LSTICK_DOWN    = 19
; CONTROLLER_BUTTON_LSTICK_LEFT    = 20
; CONTROLLER_BUTTON_LSTICK_RIGHT   = 21
; CONTROLLER_BUTTON_RSTICK_UP      = 22
; CONTROLLER_BUTTON_RSTICK_DOWN    = 23
; CONTROLLER_BUTTON_RSTICK_LEFT    = 24
; CONTROLLER_BUTTON_RSTICK_RIGHT   = 25
Up=11
Down=12
Left=13
Right=14
A=0
B=1
C=2
X=3
Y=22
Z=23
L=9
R=10
Start=6
Select=5
; Deadzones, 0.0-1.0
LStickDeadzone=0.300000
RStickDeadzone=0.300000
LTriggerDeadzone=0.300000
RTriggerDeadzone=0.300000

**Comment by MegAmi24** [comment]
This happens because the Origins version of the game is missing the model files for the main menu. Read [this guide](https://gamebanana.com/tuts/16686#H1_4) for more information.
