### ISSUE TITLE
[Android] No controller button to bring up dev menu

### ISSUE THREAD

**Issue by nonremittal** [Rubberduckycooly/Sonic-1-2-2013-Decompilation#428]
### Expected Behavior

A default/assignable button in settings.ini would bring up the dev menu

### Actual Behavior

Requires use of a physical keyboard or the first entry in Help & Options

### Steps to Reproduce

1, Enable `DevMenu=true` in settings.ini
2. Only method of accessing dev menu is via a physical Esc key or the in-app menu.

Similar to the optional extra buttons in settings.ini, would it be possible for an assignable dev menu button? SDL_GameControllerButton has options for `SDL_CONTROLLER_BUTTON_BACK`, `SDL_CONTROLLER_BUTTON_GUIDE`, and `SDL_CONTROLLER_BUTTON_MISC1`. 

### Decompilation Version

N/A

### Game

Sonic 1

### Game Version

Mobile (Sega Forever)

### Platform

Android 11

**Comment by MegAmi24** [comment]
There is no dev menu button on controllers, nor do we plan to add one. Also, this is not a bug report.
