### ISSUE TITLE
StartingScene and StartingCategory not working

### ISSUE THREAD

**Issue by SneezingCactus** [Rubberduckycooly/Sonic-1-2-2013-Decompilation#43]
Every time I set StartingCategory and StartingScene to some ID and start the game, I get sent to the start menu instead of the specified scene. After this, StartingCategory and StartingScene automatically get set to true. I have tried different IDs and got the same result every time.

**Comment by Rubberduckycooly** [comment]
this has been fixed, this fix as well as `startingPlayer` and `startingSaveFile` will be avaliable in the next build
