### ISSUE TITLE
Could NOT find Vorbis (missing: Vorbis_DIR)

### ISSUE THREAD

**Issue by shoober420** [Rubberduckycooly/Sonic-1-2-2013-Decompilation#432]
### Expected Behavior

Build completion

### Actual Behavior

Build error

### Steps to Reproduce

Run MSYS2 (mingw64.exe)
Clone repo
cmake -B build

### Log File

# cmake -B build
-- Building for: Ninja
-- The C compiler identification is GNU 13.2.0
-- The CXX compiler identification is GNU 13.2.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/msys64/mingw64/bin/cc.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/msys64/mingw64/bin/c++.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
found libogg
-- Could NOT find Vorbis (missing: Vorbis_DIR)
libvorbis not found, attempting to build from source
found GLEW
-- Configuring done (0.4s)
CMake Error at CMakeLists.txt:127 (add_library):
  Cannot find source file:

    dependencies/windows/libvorbis/lib/analysis.c

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .mpp .m .M .mm .ixx .cppm
  .ccm .cxxm .c++m .h .hh .h++ .hm .hpp .hxx .in .txx .f .F .for .f77 .f90
  .f95 .f03 .hip .ispc

CMake Error at CMakeLists.txt:127 (add_library):
  No SOURCES given to target: libvorbis

CMake Generate step failed.  Build files cannot be regenerated correctly.

### Decompilation Version

https://github.com/Rubberduckycooly/Sonic-1-2-2013-Decompilation/commit/f9972d7f75b9f27db7e9f30578510c02d62edf18

### Game

Sonic 1

### Game Version

Sonic Origins

### Platform

Windows 11

**Comment by MegAmi24** [comment]
Please do not report compiler errors as an issue in this repo. Ask in the #decomp-support channel of the Retro Engine Modding Server if you need help with compiling.
