### ISSUE TITLE
Sonic 1 2.0.4 Does not work. 

### ISSUE THREAD

**Issue by Rings4** [Rubberduckycooly/Sonic-1-2-2013-Decompilation#45]
Sonic 1 2.0.4: SHA-1 - 6c6881e3dbde73d4dd0b37f68996a700c1186b1f

Title screen loads but crashes once level tries to load. Time Attack crashes when any level is chosen. You can add this version to the pinned issue.

**Comment by MGRich** [comment]
Thank you for the added hash. We're working to get the different opcodes working as quick as possible.
