### ISSUE TITLE
Game is a stutter-fest, any way currently to address that?

### ISSUE THREAD

**Issue by Rings4** [Rubberduckycooly/Sonic-1-2-2013-Decompilation#47]
I'm running the game in Fullscreen mode and tried with vsync both enabled and disabled, as well as limiting my framerate to 60 via RTSS, but the game stutters a lot. Happens in both Sonic 1 and Sonic 2.

Is there some setting I should be enabling to get smooth, stutter-free 60fps, or is this currently being worked on?

**Comment by MGRich** [comment]
I'm closing this, but what are your specs? It really doesn't take much to run it, so unless you're on an extremely low end PC, there really shouldn't be any lag.

**Comment by Rings4** [comment]
> 
> 
> I'm closing this, but what are your specs? It really doesn't take much to run it, so unless you're on an extremely low end PC, there really shouldn't be any lag.

Ryzen 7 1800x, GTX 1080TI, 16 GB 3000MHz DDR4 RAM. I really shouldn't have any issue running this.

**Comment by MGRich** [comment]
you're right what the hell i'm reopening this

**Comment by Rubberduckycooly** [comment]
does this happen on anything else? the game is software rendered, with us copying those pixels to an SDL texture for rendering to the screen so im not sure what could be stuttering

**Comment by Rings4** [comment]
> 
> 
> does this happen on anything else? the game is software rendered, with us copying those pixels to an SDL texture for rendering to the screen so im not sure what could be stuttering

Neither am I. I would have blamed it on it not being fullscreen exclusive, but there's a distinct "fullscreen" option as well as "borderless" options, so I'm pretty sure "fullscreen" here means fullscreen exclusive. 

I've tried setting my monitor refresh rate down from 120hz to 60 and it still happens. Also made sure power management in nVidia control panel is set to "prefer maximum performance". Tried setting max pre-rendered virtual reality frames to 3 but no diff, so set it back to default (1).

**Comment by trayfellow** [comment]
btw just a question, where did you get the data.rsdk file? was it from the playstore app itself or somewhere else?

**Comment by cheatfreak47** [comment]
Playing on a monitor at 60hz with a GTX 1650 and not having too many noticeable stutters here with Vsync and Fullscreen on, although I did turn devmenu off. My CPU is a i3 3450S.

That said, without Vsync on, the game does become a stuttery mess.

**Comment by BubbyNE** [comment]
i7-6700K and GTX 1080 here, I consistently noticed a lot of skipped frames when going through the loops of Emerald Hill Zone, but other stutters seemed more random.

**Comment by ffoxD** [comment]
Pentium T4200 user here, I am not noticing any stutters. I am a Linux user. Running the windows version throught Wine does stutter a lot thought.

**Comment by boj6987** [comment]
i7-8750H RTX 2070 and 16GB of RAM here. Also having stuttering and general lagginess in both games.

**Comment by synergic0084** [comment]
i5-7500, GTX 1650 Super and 24GB of RAM here, game runs fine

**Comment by arczi84** [comment]
Uhm, really ? I planned to port this to 200Mhz platform...

**Comment by cheatfreak47** [comment]
It's 

> 
> 
> Uhm, really ? I planned to port this to 200Mhz platform

From what I can tell this issue is probably specific to the current Windows build, and certain hardware or even software configurations. I wouldn't take this into account for attempting to make ports.

**Comment by MGRich** [comment]
People have been able to port stuff to lower-range consoles, like [CD on the 3DS](https://twitter.com/hisaturn_v/status/1353233182766878720?s=20), so you'll be fine.

**Comment by arczi84** [comment]
Thanks, I wasn't really convinced but wanted to be sure before I spend few hours for port.

**Comment by MGRich** [comment]
It works completely. Just make sure you don't define `RETRO_USING_SDL2` and define `RETRO_USING_SDL1`.

**Comment by BlueSwordM** [comment]
Yeah, this looks like to be an issue with the Windows builds.

I do not have any issues on a 3700X with an RX 580 on OpenManDriva 4.2 even at 4k.

**Comment by MANGOM1LK** [comment]
I've had this issue exactly once with the CD port and never again, weirdly enough? It was the 1.0 release so this might be fixed.

**Comment by Awakened0** [comment]
According to RTSS, the game runs at 62FPS which seems odd and could be causing frame pacing issues. GSync also doesn't activate even when exclusive fullscreen is enabled, so my display stays running at 144hz instead of matching the game's FPS.

**Comment by Trevor-Z** [comment]
It also runs with really bad frame pacing here, a Windows 10 machine with i5 8500 CPU and an RTX 2060.

I tried limiting the frame rate with RTSS, turning vsync on, dialing the refresh rate down to 60hz, and nothing made a difference.

Like Awakened0 said, RTSS shows the frame rate constantly varying from 60 to 62 fps, which is pretty weird.

Also, correct me if I'm wrong here, but I guess GSync is not really supposed to work, since the game uses software rendering. I wonder if the frame pacing issues are also related to this...?

**Comment by BlueSwordM** [comment]
@Trevor-Z I don't think it's related to adaptive sync technologies. Otherwise, I'd notice this issue on my Freesync enabled display.

**Comment by VinMannie** [comment]
Running on a Raspberry Pi 4B overclocked to 2.14ghz and the game has slowdown and dropped frames

**Comment by Awakened0** [comment]
Using [Special K](https://discourse.differentk.fyi/)'s framerate limiter set to 60FPS, I get a super smooth framerate combined with my monitor set to 60hz.

**Comment by MegAmi24** [comment]
closing this but shoutouts to bubby with the marle pfp

**Comment by Awakened0** [comment]
There hasn't been a new release with the fix in it yet, but a 60FPS lock was added that should do it: https://github.com/Rubberduckycooly/Sonic-1-2-2013-Decompilation/commit/9aa0ef661d4e743503796ad111e9ce5f64ac7968

**Comment by Rings4** [comment]
> There hasn't been a new release with the fix in it yet, but a 60FPS lock was added that should do it: [9aa0ef6](https://github.com/Rubberduckycooly/Sonic-1-2-2013-Decompilation/commit/9aa0ef661d4e743503796ad111e9ce5f64ac7968)

Awesome! Any eta on when a release will include this fix?
