### ISSUE TITLE
Log: Unable to open audio device: WASAPI can't initialize audio client:

### ISSUE THREAD

**Issue by EspeonScottie** [Rubberduckycooly/Sonic-1-2-2013-Decompilation#48]
Don't know what this is but it's preventing the application from running.

**Comment by Rubberduckycooly** [comment]
it appears to be an issue with SDL opening an audio device, I'll make a change so it doesn't crash the game, but I have no clue what's preventing it from opening the device

**Comment by EspeonScottie** [comment]
I mean my PC audio works fine so I'm not really sure why it's saying that.

**Comment by EspeonScottie** [comment]
Here's the whole [log.txt](https://github.com/Rubberduckycooly/Sonic-1-2-2013-Decompilation/files/5838510/log.txt) if you wanna take a look at it.

**Comment by EspeonScottie** [comment]
Okay I just figured out whole problem. It's because I'm using a PS4 controller with DS4Windows and by default when connected windows wants to use the headset audio jack on the controller as the output (which is only available when connected via USB). So if try to launch the game with a different audio device selected other than that it won't work. But once the application is open I can set my audio device back to the regular one and audio will play out of the computer as normal. So I can only enable audio if I play using a wired controller connection and select the controller as the output source before launching the game and then change it back.
