### ISSUE TITLE
Speed Shoes restart the music

### ISSUE THREAD

**Issue by PutoML** [Rubberduckycooly/Sonic-1-2-2013-Decompilation#49]
Picking up speed shoes restart the BGM instead of speeding up the music from the point where you were at the time.

**Comment by Decidetto** [comment]
This must be an issue either with your machine, or with your RSDK file(s).
Could you share your specs, OS, and version(s) of the game(s) that you got the RSDK file(s) from?

It's completely fine on my end, on both Win8.1 and 10 with RSDK files from v2.0.8 (Sonic 1) and v3.1.0 (Sonic 2). The music transitions into and out of speedup, without interruption or reset.

**Comment by hkight** [comment]
It's doing the same thing for me. I'm on the latest Android version of both games.
CPU: Intel Core i9-9900k
GPU: Nvidia GeForce RTX 2070 Super
OS: Windows 10 20H2 (latest version)
Sonic 1: Android 3.6.3 (f679e87477bbed17ff1bdb9a6793f49c)
Sonic 2: Android 1.4.4 (b7339e7a4cf4ae6264449eec06465c7c)

**Comment by PutoML** [comment]
macOS 11.2
CPU: M1
RSDK files from the latest iOS versions.

**Comment by hkight** [comment]
It's doing the same thing for me. I'm on the latest iOS version of both games.
CPU: Intel Core i9-9900k
GPU: Nvidia GeForce RTX 2070 Super
OS: Windows 10 20H2 (latest version)
Sonic 1: iOS 3.7.0 (f679e87477bbed17ff1bdb9a6793f49c)
Sonic 2: iOS 4.6.0 (b7339e7a4cf4ae6264449eec06465c7c)

**Comment by SupakugaiGames** [comment]
Can confirm this happens with me too. Tested using the RSDK files from Sonic 1 iOS 3.7.0 and Sonic 2 iOS 4.6.0 on both:
MacBook Air 2020 / macOS 11.1 / Apple M1 (Native and Rosetta)
MacBook 12" 2015 / macOS 10.14.6 / Intel Core M
On both systems and both games, the speed shoes restart the music when activating and deactivating.

Are there known incompatibility issues with the latest RSDK files?

**Comment by MGRich** [comment]
Both latest forever versions work for me. I've been unable to replicate this.

**Comment by Kurausukun** [comment]
Sorry, didn't see there was an issue already open. Anyway, here are the SHA1s for my rsdk files:
S1: 3B49570C26B469B05BD01EF43995310E7066989E
S2: 8C7B963B3591C27E43DC27CD25B3C07735BE575C

I got these from the latest versions on my phone, which were 2.1.1 for S1 and 3.1.5 for S2. Are these not the correct versions?

**Comment by Rubberduckycooly** [comment]
I've been able to replicate this bug more recently, so I'll get to work fixing it

**Comment by Rubberduckycooly** [comment]
I've been able to fix it to the point of no longer being able to replicate it, this bug should be fixed now bug I'll leave this open for now in case anyone using the latest artifacts on git can replicate this still

**Comment by PutoML** [comment]
I can confirm it's fixed for me too now.

**Comment by hkight** [comment]
Can confirm that it has been fixed for me on both games. Tested in both first zones.

**Comment by MGRich** [comment]
Due to multiple people saying this is fixed, I will close this.
