### ISSUE TITLE
S1: Disabling spindash does not disable it

### ISSUE THREAD

**Issue by Decidetto** [Rubberduckycooly/Sonic-1-2-2013-Decompilation#5]
Attempting to disable the spindash in the game options does not actually disable it.
This happens with the dev menu enabled or disabled, even when item type is set to exclusively S1.

MD5 of my Data.rsdk: 10E320E8B3C1BA3B87B1E8EE01B2492C (v2.0.8, pre-Sega Forever)

**Comment by MGRich** [comment]
For some reason, loading a zone seems to reset it?? There's nothing in the engine about it, so I don't know what's going on. (tested on 3.1.0)
![image](https://user-images.githubusercontent.com/29069561/104975551-90a11200-59c0-11eb-818f-afe75fb210ad.png)

**Comment by Rubberduckycooly** [comment]
fixed it, it was an issue with how the game options are set, the fix will be in the next build
