### ISSUE TITLE
Sonic 1+2 Fullscreen rendering issue: texture seam from top left to bottom right at 1080p

### ISSUE THREAD

**Issue by DangusTaargus** [Rubberduckycooly/Sonic-1-2-2013-Decompilation#50]
Thanks for the great work on this!

I've tested this on two different AMD machines, and can reproduce it on both - when running at 1080p and using fullscreen mode, the game render texture has a triangle seam bisecting the image from top left to bottom right, which slightly shifts the pixels. This was present on two separate machines - one with a 1080p monitor, and another with a 1440p monitor. Leaving the 1440p monitor at native res, the issue isn't present (maybe it's a direct multiple of the base game res? I haven't done the math) but when switching to 1080p it then behaves exactly like the machine with a native 1080p display: seam is present.

I'm assuming this is because the render buffer is being stretched, but only made up of two triangles? Or maybe it's a just a quirk of the renderer this uses and can be fixed? Think of the PS1 affine texture distortion but not nearly as bad. 

Hope that's clear.

**Comment by Rubberduckycooly** [comment]
I'll look into this, the backend renderer uses SDL_Renderer & SDL_Texture to render to the window (and SDL choses whatever it thinks works best for the platform iirc) so we dont have direct control over exactly how the image is rendered to the window but I'll do the best I can to fix it up

**Comment by ToruTheRedFox** [comment]
does this still occur with enhanced scaling?

**Comment by MGRich** [comment]
I cannot replicate this, assuming enhanced scaling fixed it.
