### ISSUE TITLE
S1 & S2 (Probably): Invincibility & Speed Shoes pause the game briefly to load music.

### ISSUE THREAD

**Issue by PokeTogeKiss** [Rubberduckycooly/Sonic-1-2-2013-Decompilation#52]
I think it's a bit bothersome. If it's possible, could this be fixed in a later build?

**Comment by Rubberduckycooly** [comment]
we'll definitely look into fixing it, as it does align with other audio bugs we've encountered and are wanting to fix

**Comment by trayfellow** [comment]
> I think it's a bit bothersome. If it's possible, could this be fixed in a later build?

lol i thought that issue was just me, thankfully someone else noticed it too

**Comment by Rubberduckycooly** [comment]
this has now been fixed, I rewrote the way music is loaded so there wont be a slowdown anymore hopefully
