### ISSUE TITLE
S2 Oil Ocean Zone Boss Battle crashes the game.

### ISSUE THREAD

**Issue by zayJax** [Rubberduckycooly/Sonic-1-2-2013-Decompilation#54]
The boss fight was going on as usual, but when i defeated Robotnik, i quickly went to the capsule pod to push the button so i could finish the stage, but the game crashed as soon as i pushed the button.

Maybe it was because Robotnik hadn't gotten out of his "explosion state" or whatever. Or maybe i was too fast.

**Comment by MGRich** [comment]
Likely audio, so closing this. If it still happens when we release 1.1.0, please request it to be re-opened.
