### ISSUE TITLE
Game doesn't load mappings from gamecontrollerdb.txt

### ISSUE THREAD

**Issue by DanTheMan827** [Rubberduckycooly/Sonic-1-2-2013-Decompilation#55]
There's no call to load additional mappings, so the game will just use the ones included with SDL2.

This is also the case with the Sonic CD code.

Something like this would load the mappings (place it before SDL_Init)

    // try loading an external gamecontroller mapping file
    int nummaps = SDL_GameControllerAddMappingsFromFile("gamecontrollerdb.txt");
    if (nummaps >= 0)
        printf("loaded %d controller mappings from 'gamecontrollerdb.txt'\n", nummaps);

**Comment by Rubberduckycooly** [comment]
the ability to load controller mappings from `controllerdb.txt` has been added, and will be in the next build, and all future artifacts (I've also added it to CD as well)
