### ISSUE TITLE
Chemical Plant Zone purple water drawing one line in wrong place

### ISSUE THREAD

**Issue by psyalemao** [Rubberduckycooly/Sonic-1-2-2013-Decompilation#56]
Hello there,

I would like to report what it seems to be a bug on level Chemical Plant Zone. When you're seeing the purple water on your screen, it draws a purple line on top of the window just like this screenshot
![Untitled1](https://user-images.githubusercontent.com/61525284/105126409-6bde9480-5abd-11eb-8f56-24990c1771b4.png)
but when it's not showing, the purple line disappears.
![Untitled2](https://user-images.githubusercontent.com/61525284/105126415-6e40ee80-5abd-11eb-8ec1-33201b714ab5.png)

**Comment by MGRich** [comment]
Fixed in recent push to master.

**Comment by ThornTSC** [comment]
Using the latest Windows x64 artifact and pre-Forever versions of both games, it seems that this problem is now inverted: if the entire screen should be using underwater palettes, then the top line of the screen will show the dry palette.
