### ISSUE TITLE
S1&2: Jumping immediately after a spindash causes camera jerk

### ISSUE THREAD

**Issue by Decidetto** [Rubberduckycooly/Sonic-1-2-2013-Decompilation#6]
If in a position where camera Y is not against the bottom edge of the stage, when jumping immediately after releasing a spindash (in the time before the camera has finished catching up to Sonic) in either game, the camera starts tracking Sonic's jump at a height that is too low and as a result snaps down rather jarringly at the moment of the jump. This happens in either game.

This does not occur in the original mobile version of either game.

My checksums (both are pre-Sega Forever):
S1 Data.rsdk MD5: 10E320E8B3C1BA3B87B1E8EE01B2492C (v2.0.8)
S2 Data.rdsk MD5: 6F1244F8D6E3822778F69BCE2D1E8558 (v3.1.5)

**Comment by Alazizi1982** [comment]
https://www.pscp.tv/naygrajalss
