### ISSUE TITLE
Title cards don't adapt to 4:3

### ISSUE THREAD

**Issue by ToruTheRedFox** [Rubberduckycooly/Sonic-1-2-2013-Decompilation#61]
They should adapt to 4:3 considering the fact that Christian Whitehead himself debugged the game in 4:3, and the fact that the game came out at a time where most iPads in existence were 4:3

**Comment by MGRich** [comment]
This is a game script issue: can't do much about it in-engine. Updated scripts from updated versions most likely changed the title screens.
