### ISSUE TITLE
Data folder mode doesn't work due to missing line of code

### ISSUE THREAD

**Issue by ToruTheRedFox** [Rubberduckycooly/Sonic-1-2-2013-Decompilation#63]
the missing line is "StrCopy(fileInfo->fileName, filePath);" at LoadFile() in Reader.cpp

**Comment by MGRich** [comment]
Can you please make a pull request or tell me what line it's supposed to be in?

**Comment by ToruTheRedFox** [comment]
line 156 in Reader.cpp
![image](https://user-images.githubusercontent.com/15708278/105208351-83ab2c80-5b40-11eb-80b5-789694e45735.png)

**Comment by MGRich** [comment]
Missing line of code appears to mitigate the issue, but eventually crashes anyway, as far as I'm aware.

**Comment by MGRich** [comment]
Fixed in 0b89c104b75e8d09ea2ba2c9031c222203b624e2.

**Comment by ToruTheRedFox** [comment]
the crash happens due to a different issue, as it happens with the RSDK too, and the log doesn't say that it failed to load something
