### ISSUE TITLE
Graphical Glitch in aquatic Ruin Zone

### ISSUE THREAD

**Issue by Snowy-Folfsky** [Rubberduckycooly/Sonic-1-2-2013-Decompilation#64]
The splashing sprite is being replaced with a sprite of Sonic's lower half running animation, and Dr. Eggman is replaced with 2 angled Sonic Sprites. The splashing happens in aquatic ruin 1. Anyone else have this issue? 

[https://youtu.be/qDQcKreeezs](url)

**Comment by MGRich** [comment]
Fxed in 1.1.0, releasing in the weekend.
