### ISSUE TITLE
ScreenWidth question

### ISSUE THREAD

**Issue by mvp113** [Rubberduckycooly/Sonic-1-2-2013-Decompilation#65]
This might be a really silly question, but I had a question regarding ScreenWidth? The standard is 424, and if you enable fullscreen, it looks great on my 1920x1080 monitor. But for fun I turned ScreenWidth=1080 to see how that'd look, and man you can really see a lot more! Only problem is the height doesn't adapt. I tried to add a new parameter ScreenHeight=1920 but it didn't change anything. So my question is, is there any way to change this, or should it just remain at 424? I don't know if the WindowScale=2 option is doing anything regards to this... I tried at 0 and at 1 and didn't change anything. I also have FullScreen=True and Bordless=True if that helps

Most importantly though, thanks so much for this! Uninstalling BlueStacks was a great moment haha. You've all really done amazing work on making this experience much better!

**Comment by MGRich** [comment]
Height is hardcoded to a define due to how the renderer works. I actually tried native 720p myself in Sonic 2 which was fun. You can compile it with a height of 1080, but as for config it's very difficult.
