### ISSUE TITLE
Broken Splash Sprites (Sonic 2 ARZ)

### ISSUE THREAD

**Issue by SinexPtsGAMING** [Rubberduckycooly/Sonic-1-2-2013-Decompilation#66]
A minor bug, which is that periodically sprites of water splash on the Aquatic Ruin Zone bugs, and instead of normal sprites appears Sonic's spritesheet. 

https://user-images.githubusercontent.com/52968560/105195837-99831680-5b6d-11eb-81d7-bbd514ec719c.mp4

**Comment by MGRich** [comment]
Fixed in 1.1.0, releasing Saturday.
