### ISSUE TITLE
S1: weird collision with the marble hill moving grass blocks

### ISSUE THREAD

**Issue by danielh05** [Rubberduckycooly/Sonic-1-2-2013-Decompilation#68]
![Q7tfhZJrqg](https://user-images.githubusercontent.com/35849198/105200205-dfc18100-5b3f-11eb-9bca-1212d8c62fa1.gif)

**Comment by MGRich** [comment]
Can replicate extremely easily.

**Comment by Rubberduckycooly** [comment]
it was a very minor bug, but it has been fixed now fortunately
