### ISSUE TITLE
Special Stage diamonds are able to miss collision

### ISSUE THREAD

**Issue by MasterGamingRo** [Rubberduckycooly/Sonic-1-2-2013-Decompilation#71]
Sonic 1
Sometimes in Special Stages you go through the breakable diamond things.
In the result screen the New Life sounds gets stopped.

Sonic 2
In the result screen the New Life sounds gets stopped.
Some Eggman sprites are Sonic.

**Comment by MGRich** [comment]
Most of these are known and fixed in 1.1.0, however the special stage bug is new, so I'll edit the title and keep it up.

**Comment by Rubberduckycooly** [comment]
I've made a change that fixes a bug relating to platforms where the collision would be wonky, I haven been unable to replicate this bug so I assume it's probably fixed, but I am not entirely sure

**Comment by MasterGamingRo** [comment]
Thank you!
This is the be best thing that happened to Sonic fans in 2021 :)
Good job <3
