### ISSUE TITLE
Explicitly defining window height

### ISSUE THREAD

**Issue by WumboSpasm** [Rubberduckycooly/Sonic-1-2-2013-Decompilation#73]
I can change the window width in settings.ini, but the height is locked to 480 pixels and can only be modified by scaling the entire window. Is it possible for the ability to define a custom height to be added, or are there engine limitations in place that prevent it from happening?

**Comment by MGRich** [comment]
Engine limitations, sadly. Stuff with how it renders makes it hard to make any sort of custom height.
