### ISSUE TITLE
S1 Scrap Brain Act 2 Opening the Invincibility Monitor made the music mute and shortly after, crash the game.

### ISSUE THREAD

**Issue by zayJax** [Rubberduckycooly/Sonic-1-2-2013-Decompilation#75]
![image](https://user-images.githubusercontent.com/77703141/105257849-9df00500-5b56-11eb-84df-617ea6b8f03d.png)
Said invincibility monitor was in the image shown.

**Comment by MGRich** [comment]
Audio bug, fixed in 1.1.0.
