### ISSUE TITLE
Sonic 2: Death Egg Doors To Mecha Sonic Boss Don't Close Correctly

### ISSUE THREAD

**Issue by GrayCatTheMemeMachine** [Rubberduckycooly/Sonic-1-2-2013-Decompilation#76]
The yellow and black lined strips/doors leading to Mecha Sonic Boss (Death Egg Zone) end up going back up after Sonic moves right a bit and the screen scrolls, Which leaves a gap in the left side. This isn't really too big of an issue, But still makes it possible to cheese the boss in some bits. (The game also crashed one time, But crashes are semi-common so I'm not sure if this is the real reason)

**Comment by ThornTSC** [comment]
I can confirm that this happens on the latest SEGA Forever version but not on a pre-Forever version.
