### ISSUE TITLE
S1 : weird collision bug at SBZ3

### ISSUE THREAD

**Issue by trayfellow** [Rubberduckycooly/Sonic-1-2-2013-Decompilation#77]
![ivegotthefunkycol](https://user-images.githubusercontent.com/48515908/105280419-4c8a5900-5bdc-11eb-8a64-c9a3bd4be042.PNG)

the collision seen here at this screenshot is off, try to position yourself like i did in the screenshot and do a simple spindash, sonic somehow rolls up a bit instead of going straight, 

ive tested this on my mobile phone to make sure this wasnt a script related issue and sonic rolls straight perfectly fine

**Comment by GrayCatTheMemeMachine** [comment]
Yea I tested it on PC, For some weird reason the first 3 blocks of the platform (Including the kinda broken ones) Seem to be a bit bumpy for some reason and makes Sonic have trouble going over them

**Comment by MGRich** [comment]
Fixed in e890d63f22e456f7a1157f16f86f10c22e9452b0.
