### ISSUE TITLE
Bugged Time Attack Mode on 32-bit Release

### ISSUE THREAD

**Issue by TheWonderFromDownUnder** [Rubberduckycooly/Sonic-1-2-2013-Decompilation#81]
The Time Attack level select has become bugged in the newest update for both games. Emerald Hill Act 1 and Green Hill Act 1 work as they should, but Emerald Hill Act 2 sends you to Egg Gauntlet, Chemical Plant to Mystic Cave send you to the Boss Attack Rooms, Oil Ocean Act 1 sends you to Proto Palace, and everything after hangs the game. Same for Sonic 1, except the post Green Hill levels that work send you to the Special Stages.

**Comment by Rubberduckycooly** [comment]
upon further investigations, this is an issue with the git autobuilding rather than the codebase itself, so I'm going to have RMG look into why it's different and investigate further fixes

**Comment by Enbika** [comment]
Can confirm on Linux, regardless of whether it's built via GitHub Actions or on my machine

**Comment by MGRich** [comment]
Can confirm it is EXCLUSIVELY Release x86 on Windows.

**Comment by MGRich** [comment]
(Probably) fixed in 9d0ff00f427c7b8412f0145fcaf813407ffa3df3.
