### ISSUE TITLE
pausing is both on the start button and on one of the jump buttons

### ISSUE THREAD

**Issue by danielh05** [Rubberduckycooly/Sonic-1-2-2013-Decompilation#82]
something that has been bothering me is that on both keyboard and controller the pause button is located on one of the jump buttons and i feel like that should be changed (i accidentally hit that button a lot)
keyboard: X
controller (xbox): B

gif below is me hitting the three jump buttons
![6nUrsd0D6E](https://user-images.githubusercontent.com/35849198/105340942-d0dddb80-5bde-11eb-88a3-97b9ded8d096.gif)

**Comment by Rubberduckycooly** [comment]
this isn't somthing we can change via the engine, it is apparently an intentional "feature" one of the sega forever dev added to the game (and its super annoying ik), the options are either to get an earlier rsdk file without it or to wait for a script mod to patch it out
