### ISSUE TITLE
Problem with achievements 

### ISSUE THREAD

**Issue by EspeonScottie** [Rubberduckycooly/Sonic-1-2-2013-Decompilation#87]
I'm trying to get some of the ones I missed on my cleared save file but it's not updating for some reason. Like it won't give me Blast Processing even though I was able to beat GHZ Act 1 in under 30 seconds.

**Comment by danielh05** [comment]
is it even possible to get achievevements? ive gotten all chaos emeralds and i still dont have the chaos connoisseur achievement

**Comment by EspeonScottie** [comment]
> is it even possible to get achievevements? ive gotten all chaos emeralds and i still dont have the chaos connoisseur achievement

For me It's says I have some of them including Chaos Connoisseur. But it won't let me get some of the other ones.

**Comment by MGRich** [comment]
Achievements are possible, just not _obvious_. Achievements will have a pop-up in 1.2.0, so we can test again there for more obvious responses.

**Comment by BlueSpikeball** [comment]
Achievements work, but half of them are mislabeled up in the Sonic 1 achievements screen. For example, fulfilling the conditions for Blast Processing will set Ramp Ring Acrobatics to achieved and vice versa. I've compiled a list of the ones are mixed up with each other:

Blast Processing <> Ramp Ring Acrobatics
Secret of Labyrinth Zone is <> Ring King
Chaos Connoisseur <> Hidden Transporter

The ones I didn't list seem to be properly labeled.

**Comment by MGRich** [comment]
Fixed by #196.
