### ISSUE TITLE
S1: Sprites glitched on dev menu

### ISSUE THREAD

**Issue by BigNate60** [Rubberduckycooly/Sonic-1-2-2013-Decompilation#9]
Whenever you pause the game on any level in Sonic 1, then go to the dev menu, the sprites for the letters will become garbled up sonic sprites, and the game locks up.

**Comment by MGRich** [comment]
Possibly fixed in master?? More info is needed for the Sonic sprite issue.

**Comment by MGRich** [comment]
Confirmed to be fixed in master from recent push.
