### ISSUE TITLE
no controller input (Xinput)

### ISSUE THREAD

**Issue by minuteworld1** [Rubberduckycooly/Sonic-1-2-2013-Decompilation#91]
I have tried my 8bitdo sn30+, xbox one and xbox 360 pads. all xinput pads and i've been told that the games automatically pick them up. friends have tested, they have no issue but i just cannot get any controller to work atleast with the release build (tried to build from github, have no idea how) 

I have windows 10, an I7 8700k cpu and 2 1070's in sli if you needed that infomation.

**Comment by Bluesfire** [comment]
Same issue here. Using the Razer Wolverine Tournament Edition Xbox One controller. Gets picked up by everything else.

My workaround is to use a button mapping software to map my controller buttons to the keyboard keys.

**Comment by minuteworld1** [comment]
> Same issue here. Using the Razer Wolverine Tournament Edition Xbox One controller. Gets picked up by everything else.
> 
> My workaround is to use a button mapping software to map my controller buttons to the keyboard keys.

yeah I used joy2key but I don't wanna have to use it. hopefully this gets fixed next build.

**Comment by SergeyLatyshev** [comment]
Probably this: https://github.com/Rubberduckycooly/Sonic-CD-11-Decompilation/issues/24

**Comment by deepfriedfilth** [comment]
I've had similar controller issues on older builds running on win7 that I remedied with joy2key before seeing this issue: https://github.com/Rubberduckycooly/Sonic-1-2-2013-Decompilation/issues/35 after unplugging/replugging 360 controller while game is open, all is well (and joy2key is no longer needed as a workaround)

**Comment by cheatfreak47** [comment]
Another workaround if you happen to already be familiar with it, is adding the game to steam as a non-steam game for use with Steam Input API.

**Comment by JackoboLeChocobo** [comment]
Steam is not necessary and must not be a solution. Program is made with SDL2 so the solution is the var SDL_GAMECONTROLLERCONFIG. I used GamepadTool (https://generalarcade.com/gamepadtool/) to create the contents for SDL_GAMECONTROLLERCONFIG. With my USB Nintendo Switch Controller I get that :
```
"030000006f0e00008501000011010000,Performance Designed Products Wired Fight Pad Pro for Nintendo Switch,platform:Linux,a:b1,b:b2,x:b0,y:b3,back:b8,guide:b13,start:b9,leftstick:b10,rightstick:b11,leftshoulder:b4,rightshoulder:b5,dpup:h0.1,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,-leftx:a0,-lefty:a1,rightx:+a2,-righty:a3,lefttrigger:b6,righttrigger:b7,"
```

And I use this command under Linux to load the game : 
```
SDL_GAMECONTROLLERCONFIG="030000006f0e00008501000011010000,Performance Designed Products Wired Fight Pad Pro for Nintendo Switch,platform:Linux,a:b1,b:b2,x:b0,y:b3,back:b8,guide:b13,start:b9,leftstick:b10,rightstick:b11,leftshoulder:b4,rightshoulder:b5,dpup:h0.1,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,-leftx:a0,-lefty:a1,rightx:+a2,-righty:a3,lefttrigger:b6,righttrigger:b7," ./sonic2013 
```

And now, gamepad works ! Happy I am :3

**Comment by MGRich** [comment]
Closing for now, may have RDC check this again later.
