### ISSUE TITLE
Restarting/Exiting/Dying in Time Attack Mode Acts Improperly

### ISSUE THREAD

**Issue by ThornTSC** [Rubberduckycooly/Sonic-1-2-2013-Decompilation#92]
(Tested using pre-Forever APKs for both games and the latest Windows x64 artifact 390f745)

On Android, restarting a Time Attack ignores star posts and places the player at the beginning of the level. In the decompilation, restarting a time attack places the player at the previous lamp/star post.

On Android, leaving an act in Time Attack by any method sends the player to the menu displaying best times. In the decompilation, finishing a level sends the player to the correct menu, pausing and exiting or dying sends the player back to the start menu for the entire game, and finishing a Sonic 1 special stage (whether by emerald or by GOAL) returns the player to the correct menu but displays 0:00:00 for all times. In the special stage case, the 0s do not overwrite the save file's actual times, but the game also does not save new best times even if the emerald was collected.

**Comment by Rubberduckycooly** [comment]
relating to the 0:00:00 time issue, it somehow thinks you've gotten 0 seconds in time so any future time is always lower than that, we will investigate these issues asap

**Comment by MGRich** [comment]
Fixed in 53a5bd5d9d8b7245e97515600904b7844bda1570.
