### ISSUE TITLE
Cannot do sound test.

### ISSUE THREAD

**Issue by Sasytoremember** [Rubberduckycooly/Sonic-1-2-2013-Decompilation#95]

**Comment by ToruTheRedFox** [comment]
it works fine for me in Sonic 2 but it's fairly unresponsive

**Comment by trayfellow** [comment]
which apk version of sonic 1 or 2 did you use to get the data.rsdk files?

**Comment by MGRich** [comment]
I'm just gonna close this: there wasn't enough info to start off anyway.
