### ISSUE TITLE
Sonic 2: Super Sonic Palette Broken in Chemical Plant/Hidden Palace underwater

### ISSUE THREAD

**Issue by TrackerTD** [Rubberduckycooly/Sonic-1-2-2013-Decompilation#97]
After transforming into Super Sonic, Sonic's underwater palette breaks. All the yellow on him becomes solid black instead. Seems similar to Mania's issue with Super Mighty, but that's just speculative.  
![HPZwater](https://user-images.githubusercontent.com/71041044/105424298-06b2ac80-5c3f-11eb-9a26-e1b136f56e3a.png)
![CPZwater](https://user-images.githubusercontent.com/71041044/105424300-074b4300-5c3f-11eb-8cad-98a878bce0bb.png)

**Comment by Sasytoremember** [comment]
Cool, probably it couldn't find the pallete

**Comment by Rubberduckycooly** [comment]
this has been fixed, super palettes (and probably some other palette effects) will now work perfectly
