### ISSUE TITLE
Sonic 1 & 2: Some Settings Only Affect No Save & Save Slot 1 

### ISSUE THREAD

**Issue by TrackerTD** [Rubberduckycooly/Sonic-1-2-2013-Decompilation#98]
Currently the Game Config menu only seems to be reflected in Save Slot 1 and No Save, to an extent.

Loading the Sonic 2 + S3 Items setting will give Sonic the insta-shield but none of the S2/S3 items will appear.

I believe this also affects settings like the Emeralds in Sonic 1, though I need to do more testing on this front. The other day I did a run of Sonic 1 where I collected 6 emeralds, but did not get the good ending, and Giant Rings had stopped spawning. I had Super Forms enabled, so I'm assuming this was also down to the settings glitch.

Video Example: [https://www.youtube.com/watch?v=Bdu6dqZtLIU](url)

UPDATE: Tested further, settings such as Spike Bug do seem to affect all files. Still need to test Super Forms properly. 

UPDATE 2: Able to confirm the Super Form setting is bugged as I described. The Emeralds use their modern palette, but there's only six able to be collected, and no "Got them All" message.

**Comment by Rubberduckycooly** [comment]
I found what was setting the values back to `0` on save slots and I have made a patch that allows the options to carry over while on save slots 2-4, while I haven't properly tested the 7 emerald option, I would bet that it has likely been fixed, the fix is avaliable in the next build & artifact
