### ISSUE TITLE
Please add Linux instruction for users

### ISSUE THREAD

**Issue by coreybruce** [Rubberduckycooly/Sonic-1-2-2013-Decompilation#99]
Hi I just wanted to nicely ask if you could put Linux instructions for users as they are very simple and easy.

``
git clone https://github.com/Rubberduckycooly/Sonic-1-2-2013-Decompilation
``
``
cd Sonic-1-2-2013-Decompilation
``
``
make
``

Once that is done just follow the same directions as the video on copying and renaming the Data.rsdk.xmf file to Data.rsdk and run sonic2013 inside the bin folder

**Comment by chunkyjackson** [comment]
Probably should add this to keep it noob friendly.
In Ubuntu (Mint, Pop!_OS, etc...) use the following command: sudo apt install build-essential git libsdl2-dev libvorbis-dev libogg-dev
Arch Linux: sudo pacman -Sy base-devel git sdl2 libvorbis libogg
Then: git clone https://github.com/Rubberduckycooly/Sonic-1-2-2013-Decompilation.git
cd Sonic-1-2-2013-Decompilation
make -j4

**Comment by coreybruce** [comment]
I agree, good to keep it noob friendly you know :D :+1:
